### ISSUE TITLE
Audio playback collection

### ISSUE THREAD

**Issue by halx99** [adxeproject/adxe#159]
1. https://github.com/kcat/openal-soft, excellent, but LGPL ![GitHub stars](https://img.shields.io/github/stars/kcat/openal-soft.svg?label=Stars)
2. https://github.com/dr-soft/miniaudio, public domain or MIT No Attribution. ![GitHub stars](https://img.shields.io/github/stars/dr-soft/miniaudio.svg?label=Stars)

**Comment by halx99** [comment]
1. https://github.com/kcat/openal-soft, excellent, but LGPL ![GitHub stars](https://img.shields.io/github/stars/kcat/openal-soft.svg?label=Stars)
2. https://www.icculus.org/mojoAL, zlib license, based on SDL2
3. https://github.com/andrewrk/libsoundio, MIT license ![GitHub stars](https://img.shields.io/github/stars/andrewrk/libsoundio.svg?label=Stars)
4. https://github.com/dr-soft/miniaudio, public domain or MIT No Attribution. ![GitHub stars](https://img.shields.io/github/stars/dr-soft/miniaudio.svg?label=Stars)
5. Apple Open Source OpenAL: https://opensource.apple.com/tarballs/OpenAL/OpenAL-64.tar.gz

**Comment by halx99** [comment]
Build openal-soft as dynamic framework bundle for osx, ios:
https://cmake.org/cmake/help/v3.5/prop_tgt/FRAMEWORK.html
https://github.com/kcat/openal-soft/issues/326

**Comment by wbbtcool** [comment]
@halx99  
When I run this command to compile the dynamic library, an error occurs.  

Platform：Xcode 12.2  macOS Big Sur 11.0.1

`cmake -S . -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_CXX_EXTENSIONS=OFF -DALSOFT_REQUIRE_COREAUDIO=ON -DALSOFT_OSX_FRAMEWORK=ON -DALSOFT_EMBED_HRTF_DATA=YES -DALSOFT_UTILS=OFF -DALSOFT_EXAMPLES=OFF -DALSOFT_INSTALL=OFF -B build_x64 -DCMAKE_OSX_SYSROOT=iphonesimulator` 

Error:
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
CMake Error at CMakeLists.txt:30 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:30 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "/Users/wangbin/work/Github/openal-soft/build_x64/CMakeFiles/CMakeOutput.log".

Did you encounter this problem?

**Comment by halx99** [comment]
please refer to engine-x README.md guide, you needs use ios.mini.cmake toolchain file for build with xcode11/12

**Comment by halx99** [comment]
@wbbtcool for xcoe12+, you needs specific arch manually for building ios simualtor, such as:
```
cmake -S . -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_CXX_EXTENSIONS=OFF -DALSOFT_REQUIRE_COREAUDIO=ON -DALSOFT_OSX_FRAMEWORK=ON -DALSOFT_EMBED_HRTF_DATA=YES -DALSOFT_UTILS=OFF -DALSOFT_EXAMPLES=OFF -DALSOFT_INSTALL=OFF -B build_x64 -DCMAKE_OSX_SYSROOT=iphonesimulator -DCMAKE_OSX_ARCHITECTURES=x86_64
```

**Comment by wbbtcool** [comment]
@halx99 I try, but still an error occurred. 
Error:
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- broken
CMake Error at /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/wangbin/work/Github/openal-soft/build_x64/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/xcodebuild -project CMAKE_TRY_COMPILE.xcodeproj build -target cmTC_a1f5b -configuration Debug -hideShellScriptEnvironment && Command line invocation:
        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project CMAKE_TRY_COMPILE.xcodeproj build -target cmTC_a1f5b -configuration Debug -hideShellScriptEnvironment
    
    User defaults from command line:
        HideShellScriptEnvironment = YES
    
    Prepare build
    note: The Legacy Build System will be removed in a future release. You can configure the selected build system and this deprecation message in File > Project Settings.
    === BUILD TARGET cmTC_a1f5b OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===
    
    Check dependencies
    No architectures to compile for (ARCHS=x86_64, VALID_ARCHS=arm64 arm64e armv7 armv7s).
    
    ** BUILD FAILED **
    
    The following build commands failed:
    	Check dependencies
    (1 failure)
    
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:30 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/wangbin/work/Github/openal-soft/build_x64/CMakeFiles/CMakeOutput.log".
See also "/Users/wangbin/work/Github/openal-soft/build_x64/CMakeFiles/CMakeError.log".

No architectures to compile for (ARCHS=x86_64, VALID_ARCHS=arm64 arm64e armv7 armv7s). How to set VALID_ARCHS using Cmake？

**Comment by halx99** [comment]
I can confirm, xcode12 remove x86_64 for iphonesimulator target

**Comment by halx99** [comment]
or maybe xcode12.2 too new, needs a newer release of CMake

**Comment by halx99** [comment]
I have tested, the cmake-3.19.0 final release works well

**Comment by wbbtcool** [comment]
@halx99 Thank you.  It is my mistake. The cmake version I use is too old,  and the problem was solved after upgrading.

**Comment by aismann** [comment]
I belive thats issue is more a Wiki entry. Right?

**Comment by aismann** [comment]
Can this issue closed?

**Comment by halx99** [comment]
Since adxe auto build openal-soft as embed dynamic framework for ios, this issue can be close currently.
