### ISSUE TITLE
Question: How can I scroll the  e.g.: UIScrollViewTest_Vertical like a wheel?

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#207]
Question: How can I scroll the  e.g.: UIScrollViewTest_Vertical like a wheel?

**Comment by halx99** [comment]
maybe needs listen mouse event

**Comment by aismann** [comment]
I mean the graphic effect likeca Slot machine

**Comment by halx99** [comment]
Reuse scroll item, and change item display

**Comment by aismann** [comment]
Its no longer on the focus.

**Comment by aismann** [comment]
Its no longer on the focus.
