### ISSUE TITLE
What is the reason for such a differnt behavior: Android vs Windows?

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#218]
Developing is on Windows.

![IMG_20200924_191949](https://user-images.githubusercontent.com/8652787/94179068-45f10c80-fe9c-11ea-8938-6f8a17206536.jpg)
![Screenshot_2020-09-24-19-20-56-812_org cocos2dx cpp_empty_test](https://user-images.githubusercontent.com/8652787/94179206-79cc3200-fe9c-11ea-99d0-bf5ef19b7aa7.jpg)

**Comment by aismann** [comment]
IT IS a Site Problem bereden Handy and Monitor.
So what should i usw dir both?

**Comment by aismann** [comment]
I know it is the different resolution.
But what can I use for both?
or which is to use for android and what for windows and IOS

**Comment by halx99** [comment]
You need set design resoultion policy

**Comment by aismann** [comment]
It seems only this one is the "safety car":
`Rect safeArea = Director::getInstance()->getSafeAreaRect();`

**Comment by halx99** [comment]
please check setDesignResolution at AppDelegate.cpp

**Comment by halx99** [comment]
you can use ui/LayoutHelper.h setDesignResolution to adapte device screebn more properly

**Comment by aismann** [comment]
Is there a "good" example on cpp-tests (with/without) adaption?
=> maybe good idea to have an example on cpp-tests too?

**Comment by halx99** [comment]
I think there is no both of cocos2dx serials engine currently

**Comment by halx99** [comment]
different project may have different screen adapte policy

**Comment by aismann** [comment]
no prob, only an idea

**Comment by aismann** [comment]
Its no longer on the focus.
