### ISSUE TITLE
Android and IOS behave differently when rotating the screen.

### ISSUE THREAD

**Issue by wzhengsen** [adxeproject/adxe#230]
- cocos2d-x version:
engine-x

- devices test on:
android 10.0
ios 14.0

Steps to Reproduce:
#### Now, we have a simple initial scenario that goes like this:
![photo_2020-10-07_17-28-03](https://user-images.githubusercontent.com/30433761/95313257-8603b680-08c2-11eb-9c8b-4cdbb919eed7.jpg)

- Let's start with the performance of android：
1. Using screensetRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT) to rotate the screen,It looks like this:
![photo_2020-10-07_17-43-44](https://user-images.githubusercontent.com/30433761/95315130-b0567380-08c4-11eb-8189-21b73080097f.jpg)

2. It doesn't look too good, but I can swap the width and height with setFrameSize and setDesignResolutionSize, and rearrange the scene to make the interface work properly：
![photo_2020-10-07_17-45-25](https://user-images.githubusercontent.com/30433761/95315303-e693f300-08c4-11eb-880d-3afeb6052ff9.jpg)

3. On android, the screen rotation feature works almost perfectly.

---
- Let's start with the performance of ios:
1. On IOS, the initial orientation is kept landscape as in android,then,I use the code to rotate the IOS screen to portrait:
<img width="391" alt="截屏2020-10-07 下午6 08 28" src="https://user-images.githubusercontent.com/30433761/95317903-62dc0580-08c8-11eb-99e3-228397297f7c.png">

2. I use setFrameSize and setDesignResolutionSize to swap width and height,then layout the scene,as same as android.But the scene looks like this:
<img width="393" alt="截屏2020-10-07 下午6 15 02" src="https://user-images.githubusercontent.com/30433761/95318378-0d542880-08c9-11eb-972b-93ccbe32f578.png">

3. It seems that IOS is not behaving properly.

**Comment by aismann** [comment]
@wzhengsen: Works correct on windows?

**Comment by wzhengsen** [comment]
@aismann There's no real screen rotation on windows, I just use setFrameSize to rotate the screen and swap the width and height of the design dimensions, then rearrange the UI interface to achieve a similar screen rotation effect.
This proved to be effective.

**Comment by aismann** [comment]
Sorry I tried it on Windows 10.
Result:
There is no methods like you told, look:
D:\_____GitHub___\engine-x>findstr /s setRequestedOrientation *.h
D:\_____GitHub___\engine-x>findstr /s setRequestedOrientation *.cpp
D:\_____GitHub___\engine-x>findstr /s ActivityInfo *.h
D:\_____GitHub___\engine-x>findstr /s ActivityInfo *.cpp

**Comment by aismann** [comment]
**Can we close it too?**
Reason I never found part of this sentence on adxe:
 _Using screensetRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT) to rotate the screen,It looks like this:_

Tried to find words like:
ActivityInfo
SCREEN_ORIENTATION_PORTRAIT
setRequestedOrientation

Maybe someone can check it too?
