### ISSUE TITLE
Built-in live2d 

### ISSUE THREAD

**Issue by WuJiayiSH** [adxeproject/adxe#254]
This branch should differentiate itself from the official one. I don't think it should go very further on 3d as well as a decent editor at this stage as they will be huge amount of work, but why not live2d, we already have built-in dragonbone, though it is not very popular, and spine.  I know many Chinese developers looking forward a live2d solution and it should not take very long to integrate the it.

https://docs.live2d.com/cubism-sdk-tutorials/sample-build/?locale=en_us

built-in wwise is also appealing but live2d probably high priority

**Comment by halx99** [comment]
Good news, and do you have interesting integrate it as a extension of engine-x?

**Comment by WuJiayiSH** [comment]
possible, we can add it to backlog, or roadmap . I personally not working on any serious cocos2d-x project at the moment and running short of peronal time these days. but we can come back in the future

**Comment by Xrysnow** [comment]
Well, I have a project on this: https://github.com/Xrysnow/cocos2d-x-live2d

**Comment by aismann** [comment]
@Xrysnow I see there be some updates on your project https://github.com/Xrysnow/cocos2d-x-live2d
Can we add your project on the adxe readme or some more better can you add it as an extension?

**Comment by Xrysnow** [comment]
It's ok to put it on readme. But I don't have time to make it an extension now.

**Comment by aismann** [comment]
@halx99  should I update the readme?

**Comment by halx99** [comment]
Yes, you can update it

**Comment by aismann** [comment]
closed #496

**Comment by halx99** [comment]
Will be done by PR: https://github.com/adxeproject/adxe/pull/668
