### ISSUE TITLE
Is there a way/method to set/get the sprite transparent color?  *EOM*

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#297]

**Comment by halx99** [comment]
setOpacity?

**Comment by aismann** [comment]
Set change all collors on the sprite (left is the normal sprite, right the same sprite with setOpacity(100);)
I mean the alpha color ( I know it as the transparent color which is not drawing on the sprite) 

![grafik](https://user-images.githubusercontent.com/8652787/100967803-6d192980-3530-11eb-9382-dc87f396df4e.png)

**Comment by stevetranby** [comment]
Are you talking about discarding the black pixels?

If so, you can write a simple discard shader. 
```
// pseudo-code
if (texel.r + texel.g + texel.b == 0) { discard; }

// or could try making this fragment zero alpha (need to profile to compare perf) 
if (texel.r + texel.g + texel.b == 0) { frag.a = 0; }
```
(** probably need to use .xyzw instead of .rgba)
