### ISSUE TITLE
Some updates be there for external sw parts

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#312]
Bullet 3.08
Curl   7.74
libjpeg 2.1 beta1 (2.0.90)

Maybe it is usefull to add a "last check of external sw updates before the engine-x 1.0 will be released" on the "To do"?

**Comment by halx99** [comment]
maybe wait libjpeg 2.1 final release is better

**Comment by aismann** [comment]
Yes. Its only a hint to check external sw versions before you starts to release engine-x 1.0

**Comment by halx99** [comment]
done
