### ISSUE TITLE
68:Zwoptex  => get an Exeption only running the AutoTest 

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#319]
engine-x: Latest (windows build)

![grafik](https://user-images.githubusercontent.com/8652787/105956099-93ae9900-6077-11eb-99af-8f0a6e6a4738.png)

**Comment by halx99** [comment]
It's seems getSpriteFrameByName fails

**Comment by aismann** [comment]
After some smal changes (changinging the order of the test) the "exepction is no longer thrown.
Seems a error on the Autotest to be. 
Maybe some other windows user/developer can check it also?
