### ISSUE TITLE
engine-x is a "bad" name to find 'engine-x" stuff on Github and anywhere (youtube, etc.) too

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#327]
On Github:   1,380 repository results has "engine-x" anywhere 

Maybe a more unique name is a better choose?

**Comment by halx99** [comment]
Do you have any idea about engine name?

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aismann** [comment]
CocosXD
CocosXX
CocosAL
Only few examples

**Comment by halx99** [comment]
Well, the cocos offical phone to tell me, we can't use any cocos to name this engine.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aismann** [comment]
Ok.
Why not easy and short like (not checked copyright law for the names):
ENG2X  (Why using 2 longer? Maybe 3D is coming anytime)
ENGXX    
TGEXX   (The Game Engine XX)
nocoX      (not cocos X) 
GamEngX

**Comment by halx99** [comment]
why not remove x just call noco or noc

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by halx99** [comment]
or Stare (Star Engine)
________________________________

**Comment by aismann** [comment]
Everyone is better as engine-x.
but a too short name is also bad for every search engine.

The X is important:
The "X" is a placeholder for everthing and for magic and fantasy ...and of course for all whatever a developer was dreaming.
Without the "X" it is only a name ... not more.

**Comment by halx99** [comment]
well, but the nocox is a github user: https://github.com/nocox

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by aismann** [comment]
nocoX was only a probosal

**Comment by aismann** [comment]
You should not wait to long with a new name.

'StarXngine' maybe is a better name as all before?

**Comment by halx99** [comment]
sounds good
