### ISSUE TITLE
Migrate lua from 5.3.x to 5.4.x

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#332]
- [x] `unpack`, `pack` moved from global to package `table`
- [x] `math.pow` was removed, use operator `^` instead

**Comment by halx99** [comment]
I have run the lua-tests  project with lua5.4.2, the performance is very slow when scroll the main menu panel, so it may needs a long time to determine whether upgrade to lua5.4.x

**Comment by halx99** [comment]
Note: By profile with visualstudio, it may caused by incorrect gc mode set

**Comment by halx99** [comment]
Actually, axmol support simply switch plain lua version with follow steps:
1. unzip lua-5.4.3.tar.gz and copy folder lua-5.4.3 to thirdparty/lua/plainlua/
2. Add  "-DLUA_VERSION=5.4.3" when use cmake to generate project files
