### ISSUE TITLE
How can I use OpenCV with engine-x? Any ideas/examples?

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#337]

**Comment by halx99** [comment]
sorry, I'm not use OpenCV yet, so I have no idea.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: aismann ***@***.***>
Sent: Wednesday, April 7, 2021 7:32:06 PM
To: c4games/engine-x ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [c4games/engine-x] How can I use OpenCV with engine-x? Any ideas/examples? (#337)

**Comment by aismann** [comment]
Its no longer on the focus.
