### ISSUE TITLE
cocos command clashes with Cocos2d

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#349]
If both Cocos2d-x and Engine-x are installed on the same PC, then whichever one happens to be the first in the paths list will be the one to execute the CLI `cocos` command, and as you can imagine this would cause a number of issues.

For example, this command to create a new project, but you won't know if it's making one from Engine-x or Cocos2d-x:
`cocos new gamename -p com.example.gamename -l cpp -d .`

![image](https://user-images.githubusercontent.com/8603230/116864531-58f66700-ac4b-11eb-8ed4-103d61778dce.png)

Is there any reason to not rename the `cocos` CLI command to something else?

**Comment by halx99** [comment]
Because the `engine-x` is a undetermined name, so not rename the CLI file name

**Comment by rh101** [comment]
Fair enough, then as a temporary work-around I'll rename the files on my local system for the time being.
