### ISSUE TITLE
Not compiling in linux for android

### ISSUE THREAD

**Issue by Joilnen** [adxeproject/adxe#351]
- engine-x version: 2c7830246ab38cb1fa65f07150fbf172b692de79
- devices test on: linux cross compiling for android
- developing environments
   - NDK version: r21e

[log.txt](https://github.com/c4games/engine-x/files/6431878/log.txt)

**Comment by halx99** [comment]
I just run on my ubuntu vm, it's seems works well

**Comment by Joilnen** [comment]
could you to try in a archlinux image ?

**Comment by halx99** [comment]
Well, I think the engine only support ubuntu linux with tests

**Comment by halx99** [comment]
close without news.
