### ISSUE TITLE
iOS arm64 OpenSSL linking issue on M1 Mac

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#359]
- engine-x version: 1.0
- devices test on: N/A
- developing environments
   - Xcode version: 12.5

This is on macOS Big Sur 11.3.1 running on Apple M1 ARM hardware.

When compiling I've getting the following errors when the project is trying to link libraries, and this issue is related to the OpenSSL library.  Would anyone have any idea on how to fix this?

```
Undefined symbols for architecture arm64:
  "_ENGINE_get_first", referenced from:
      _ossl_engines_list in libcurl.a(openssl.o)
  "_ENGINE_get_next", referenced from:
      _ossl_engines_list in libcurl.a(openssl.o)
  "_ENGINE_load_private_key", referenced from:
      _cert_stuff in libcurl.a(openssl.o)
  "_ENGINE_set_default", referenced from:
      _ossl_set_engine_default in libcurl.a(openssl.o)
  "_ENGINE_get_id", referenced from:
      _ossl_set_engine_default in libcurl.a(openssl.o)
      _ossl_engines_list in libcurl.a(openssl.o)
  "_ENGINE_by_id", referenced from:
      _ossl_set_engine in libcurl.a(openssl.o)
  "_ENGINE_finish", referenced from:
      _ossl_close_all in libcurl.a(openssl.o)
      _ossl_set_engine in libcurl.a(openssl.o)
  "_ENGINE_init", referenced from:
      _ossl_set_engine in libcurl.a(openssl.o)
  "_ENGINE_ctrl", referenced from:
      _cert_stuff in libcurl.a(openssl.o)
  "_ENGINE_ctrl_cmd", referenced from:
      _cert_stuff in libcurl.a(openssl.o)
  "_ENGINE_free", referenced from:
      _ossl_close_all in libcurl.a(openssl.o)
      _ossl_set_engine in libcurl.a(openssl.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by halx99** [comment]
The prebuilt libs doesn't contains M1 ARM arch, adxe plan to replace prebuilt libs with sources, please see relative issue: 
https://github.com/adxeproject/adxe/issues/115

**Comment by rh101** [comment]
Oh sorry I should specified that I'm building for iOS 11.0 (iPad/iPhone), not for the M1 Mac.

**Comment by halx99** [comment]
Sorry, I don't have M1 mac devices, so it's hard to test and solve this issue for me

**Comment by rh101** [comment]
That's quite alright. I'll spend some time on it to see if I can figure out why it's happening, and I'll let you know if I find a fix for this issue.

**Comment by rh101** [comment]
I managed to get it working by compiling OpenSSL with DSO disabled, and replacing the `ssl.a` and `crypto.a`.  I used these instructions for iOS 64 bit:
`https://wiki.openssl.org/index.php/Compilation_and_Installation#64-bit`

There may be a newer way to compile them as described here: `https://github.com/openssl/openssl/blob/master/Configurations/15-ios.conf#L12`

**Comment by rh101** [comment]
I'm not familiar with github actions, so I'm unsure if it would work or not.

**Comment by halx99** [comment]
I will try if I have time.

**Comment by halx99** [comment]
I create a simple repo https://github.com/adxeproject/openssl-build to build [openssl](https://github.com/openssl/openssl) with github actions, you can download the build artifacts at page https://github.com/adxeproject/openssl-build/actions/runs/903347269

Note: currently not build win32

**Comment by rh101** [comment]
That is excellent! I'm really glad you got it working via the github actions, and thank you for doing this, because it's extremely helpful.

**Comment by halx99** [comment]
Needs wait cmake & opensslconf.h for differrent target arch to adapte

**Comment by rh101** [comment]
Fair enough.  Sorry that I can't be of much help with this.  Github actions are all new to me, so I need to find some time to learn about it.

**Comment by halx99** [comment]
Done, now you can download the prebuilt pacakge from https://github.com/adxeproject/openssl-build/releases, and the release page contains how to use it in adxe

**Comment by rh101** [comment]
Excellent, thank you!

**Comment by rh101** [comment]
@halx99 Just ran into a minor issue.  The file `opensslconf.h.in` (and the opensslconf.h version of it) has a typo, where `define` should be `defined`:

```
#elif define(__APPLE__)
#  include <TargetConditionals.h>
```
should be
```
#elif defined(__APPLE__)
#  include <TargetConditionals.h>
```

**Comment by halx99** [comment]
Thanks foer your report, the latest release fix it and contains win32 build now: https://github.com/adxeproject/openssl-build/releases

If you have any other question about openssl build, you can report on the repo issues directly

**Comment by rh101** [comment]
Closing this issue since it's all sorted now.
