### ISSUE TITLE
Memory leak in ShaderModuleGL::getErrorLog()

### ISSUE THREAD

**Issue by Xrysnow** [adxeproject/adxe#360]
- adxe version: master

https://github.com/adxeproject/adxe/blob/2571bccf41c87372c76bbf0851c575bb2ced5020/cocos/renderer/backend/opengl/ShaderModuleGL.cpp#L65-L72

`log` is never freed. Same as [this issue](https://github.com/cocos2d/cocos2d-x/issues/20670).

**Comment by halx99** [comment]
Good report

**Comment by halx99** [comment]
Thanks, it was fixed by adxe.
