### ISSUE TITLE
cannot open file 'lib\Debug\OpenAL32.lib' in visual studio community 2019

### ISSUE THREAD

**Issue by johnspeny** [adxeproject/adxe#362]
- adxe version:1.0.0
- devices test on: windows
- When ever I am building a solution for windows, this occurs.

**Comment by halx99** [comment]
please try build a specific target such as cpp-tests

**Comment by johnspeny** [comment]
The error is still the same even after using the cpp-tests

**Comment by halx99** [comment]
Please track the https://github.com/adxeproject/adxe/runs/2692161152

**Comment by johnspeny** [comment]
I am using Microsoft Visual Studio Community 2019.
I just cloned this repository yesterday and I have tried to build it for windows and the error I get is 
Error LNK1104	cannot open file 'lib\Debug\OpenAL32.lib'.
Does this have to do with the recent Github changes in the openal folder?

**Comment by halx99** [comment]
Please check whether openal compiled succeed?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by halx99** [comment]
No changes of openal folder recently

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by johnspeny** [comment]
Done building project "OpenAL.vcxproj" -- FAILED.

**Comment by johnspeny** [comment]
Build started...
1>------ Build started: Project: common, Configuration: Debug Win32 ------
1>alcomplex.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\complex(1,1): warning C4821: Unable to determine Unicode encoding type, please save the file with signature (BOM)
1>C:\Dev\adxe\external\openal\common\alcomplex.h(13,38): error C2039: 'complex': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\iterator(21): message : see declaration of 'std'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(13,45): error C2065: 'complex': undeclared identifier
1>C:\Dev\adxe\external\openal\common\alcomplex.h(13,46): error C2062: type 'double' unexpected
1>C:\Dev\adxe\external\openal\common\alcomplex.h(13,52): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Dev\adxe\external\openal\common\alcomplex.h(13): error C2144: syntax error: 'unknown-type' should be preceded by ')'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(13): error C2144: syntax error: 'unknown-type' should be preceded by ';'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(13,52): error C2059: syntax error: '>'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(13,80): error C2059: syntax error: ')'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(19,45): error C2039: 'complex': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\iterator(21): message : see declaration of 'std'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(19,52): error C2065: 'complex': undeclared identifier
1>C:\Dev\adxe\external\openal\common\alcomplex.h(19,53): error C2062: type 'double' unexpected
1>C:\Dev\adxe\external\openal\common\alcomplex.h(19,59): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Dev\adxe\external\openal\common\alcomplex.h(19): error C2144: syntax error: 'unknown-type' should be preceded by ')'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(19): error C2144: syntax error: 'unknown-type' should be preceded by ';'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(19,59): error C2059: syntax error: '>'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(19,68): error C2059: syntax error: ')'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(20,1): error C2143: syntax error: missing ';' before '{'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(20,1): error C2447: '{': missing function header (old-style formal list?)
1>C:\Dev\adxe\external\openal\common\alcomplex.h(26,45): error C2039: 'complex': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\iterator(21): message : see declaration of 'std'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(26,52): error C2065: 'complex': undeclared identifier
1>C:\Dev\adxe\external\openal\common\alcomplex.h(26,53): error C2062: type 'double' unexpected
1>C:\Dev\adxe\external\openal\common\alcomplex.h(26,59): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Dev\adxe\external\openal\common\alcomplex.h(26): error C2144: syntax error: 'unknown-type' should be preceded by ')'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(26): error C2144: syntax error: 'unknown-type' should be preceded by ';'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(26,59): error C2059: syntax error: '>'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(26,68): error C2059: syntax error: ')'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(27,1): error C2143: syntax error: missing ';' before '{'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(27,1): error C2447: '{': missing function header (old-style formal list?)
1>C:\Dev\adxe\external\openal\common\alcomplex.h(36,42): error C2039: 'complex': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\iterator(21): message : see declaration of 'std'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(36,49): error C2065: 'complex': undeclared identifier
1>C:\Dev\adxe\external\openal\common\alcomplex.h(36,50): error C2062: type 'double' unexpected
1>C:\Dev\adxe\external\openal\common\alcomplex.h(36,56): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Dev\adxe\external\openal\common\alcomplex.h(36): error C2144: syntax error: 'unknown-type' should be preceded by ')'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(36): error C2144: syntax error: 'unknown-type' should be preceded by ';'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(36,56): error C2059: syntax error: '>'
1>C:\Dev\adxe\external\openal\common\alcomplex.h(36,65): error C2059: syntax error: ')'
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(16,38): error C2039: 'complex': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\cmath(743): message : see declaration of 'std'
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(16,45): error C2065: 'complex': undeclared identifier
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(16,46): error C2062: type 'double' unexpected
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(16,52): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(16): error C2144: syntax error: 'unknown-type' should be preceded by ')'
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(16): error C2144: syntax error: 'unknown-type' should be preceded by ';'
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(16,52): error C2059: syntax error: '>'
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(16,80): error C2059: syntax error: ')'
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(17,1): error C2143: syntax error: missing ';' before '{'
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(17,1): error C2447: '{': missing function header (old-style formal list?)
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(63,42): error C2039: 'complex': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\cmath(743): message : see declaration of 'std'
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(63,49): error C2065: 'complex': undeclared identifier
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(63,50): error C2062: type 'double' unexpected
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(63,56): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(63): error C2144: syntax error: 'unknown-type' should be preceded by ')'
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(63): error C2144: syntax error: 'unknown-type' should be preceded by ';'
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(63,56): error C2059: syntax error: '>'
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(63,65): error C2059: syntax error: ')'
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(64,1): error C2143: syntax error: missing ';' before '{'
1>C:\Dev\adxe\external\openal\common\alcomplex.cpp(64,1): error C2447: '{': missing function header (old-style formal list?)
1>Done building project "common.vcxproj" -- FAILED.
2>------ Build started: Project: OpenAL, Configuration: Debug Win32 ------
2>uhjfilter.cpp
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\complex(1,1): warning C4821: Unable to determine Unicode encoding type, please save the file with signature (BOM)
2>C:\Dev\adxe\external\openal\common\alcomplex.h(13,38): error C2039: 'complex': is not a member of 'std'
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\memory(28): message : see declaration of 'std'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(13,45): error C2065: 'complex': undeclared identifier
2>C:\Dev\adxe\external\openal\common\alcomplex.h(13,46): error C2062: type 'double' unexpected
2>C:\Dev\adxe\external\openal\common\alcomplex.h(13,52): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>C:\Dev\adxe\external\openal\common\alcomplex.h(13): error C2144: syntax error: 'unknown-type' should be preceded by ')'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(13): error C2144: syntax error: 'unknown-type' should be preceded by ';'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(13,52): error C2059: syntax error: '>'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(13,80): error C2059: syntax error: ')'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(19,45): error C2039: 'complex': is not a member of 'std'
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\memory(28): message : see declaration of 'std'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(19,52): error C2065: 'complex': undeclared identifier
2>C:\Dev\adxe\external\openal\common\alcomplex.h(19,53): error C2062: type 'double' unexpected
2>C:\Dev\adxe\external\openal\common\alcomplex.h(19,59): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>C:\Dev\adxe\external\openal\common\alcomplex.h(19): error C2144: syntax error: 'unknown-type' should be preceded by ')'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(19): error C2144: syntax error: 'unknown-type' should be preceded by ';'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(19,59): error C2059: syntax error: '>'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(19,68): error C2059: syntax error: ')'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(20,1): error C2143: syntax error: missing ';' before '{'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(20,1): error C2447: '{': missing function header (old-style formal list?)
2>C:\Dev\adxe\external\openal\common\alcomplex.h(26,45): error C2039: 'complex': is not a member of 'std'
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\memory(28): message : see declaration of 'std'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(26,52): error C2065: 'complex': undeclared identifier
2>C:\Dev\adxe\external\openal\common\alcomplex.h(26,53): error C2062: type 'double' unexpected
2>C:\Dev\adxe\external\openal\common\alcomplex.h(26,59): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>C:\Dev\adxe\external\openal\common\alcomplex.h(26): error C2144: syntax error: 'unknown-type' should be preceded by ')'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(26): error C2144: syntax error: 'unknown-type' should be preceded by ';'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(26,59): error C2059: syntax error: '>'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(26,68): error C2059: syntax error: ')'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(27,1): error C2143: syntax error: missing ';' before '{'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(27,1): error C2447: '{': missing function header (old-style formal list?)
2>C:\Dev\adxe\external\openal\common\alcomplex.h(36,42): error C2039: 'complex': is not a member of 'std'
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\memory(28): message : see declaration of 'std'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(36,49): error C2065: 'complex': undeclared identifier
2>C:\Dev\adxe\external\openal\common\alcomplex.h(36,50): error C2062: type 'double' unexpected
2>C:\Dev\adxe\external\openal\common\alcomplex.h(36,56): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>C:\Dev\adxe\external\openal\common\alcomplex.h(36): error C2144: syntax error: 'unknown-type' should be preceded by ')'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(36): error C2144: syntax error: 'unknown-type' should be preceded by ';'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(36,56): error C2059: syntax error: '>'
2>C:\Dev\adxe\external\openal\common\alcomplex.h(36,65): error C2059: syntax error: ')'
2>C:\Dev\adxe\external\openal\common\phase_shifter.h(48,27): error C2760: syntax error: unexpected token 'identifier', expected 'type specifier'
2>C:\Dev\adxe\external\openal\common\phase_shifter.h(73): message : see reference to class template instantiation 'PhaseShifterT<FilterSize>' being compiled
2>C:\Dev\adxe\external\openal\core\uhjfilter.cpp(19,24): error C2039: 'complex': is not a member of 'std'
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\memory(28): message : see declaration of 'std'
2>C:\Dev\adxe\external\openal\core\uhjfilter.cpp(19,31): error C2061: syntax error: identifier 'complex'
2>mixer_sse41.cpp
2>Generating Code...
2>Done building project "OpenAL.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 1 up-to-date, 0 skipped ==========

**Comment by halx99** [comment]
It seems caused by some sdk env setup, please check does the openal-soft: https://github.com/kcat/openal-soft could compiled on your computer?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by johnspeny** [comment]
OpenAL Soft compiled well, now how do I get rid of openal32.lib that was causing error in my visual studio. Or even how do I integrate OpenAL Soft into my cocos project

**Comment by halx99** [comment]
It's strange, I just tests on my devices with the same msvctools 14.28.29910, and works well:
```text
d:\dev\adxe>cmake --build build --target OpenAL
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.9.0+5e4b48a27
版权所有(C) Microsoft Corporation。保留所有权利。

  Checking Build System
  Building Custom Rule D:/dev/adxe/external/openal/CMakeLists.txt
  alcomplex.cpp
D:\dev\adxe\external\openal\common\albit.h(135,1): warning C4127: 条件表达式是常量 [D:\dev\adxe\build\engine\external\openal\co
mmon.vcxproj]
D:\dev\adxe\external\openal\common\alcomplex.cpp(22): message : 查看对正在编译的函数 模板 实例化“int al::countr_zero<size_t>(T)”的引用 [D
:\dev\adxe\build\engine\external\openal\common.vcxproj]
          with
          [
              T=size_t
          ]
D:\dev\adxe\external\openal\common\albit.h(139,1): warning C4293: “>>”: Shift 计数为负或过大，其行为未定义 [D:\dev\adxe\build\engine\
external\openal\common.vcxproj]
  alfstream.cpp
  almalloc.cpp
  alstring.cpp
  dynload.cpp
  polyphase_resampler.cpp
  ringbuffer.cpp
  strutils.cpp
  threads.cpp
  正在生成代码...
  common.vcxproj -> D:\dev\adxe\build\lib\Debug\common.lib
  Generating hrtf_default.h
  Building Custom Rule D:/dev/adxe/external/openal/CMakeLists.txt
  auxeffectslot.cpp
D:\dev\adxe\external\openal\common\albit.h(135,1): warning C4127: 条件表达式是常量 [D:\dev\adxe\build\engine\external\openal\Op
enAL.vcxproj]
D:\dev\adxe\external\openal\al\auxeffectslot.cpp(279): message : 查看对正在编译的函数 模板 实例化“int al::countr_zero<uint64_t>(T)”的引用
 [D:\dev\adxe\build\engine\external\openal\OpenAL.vcxproj]
          with
          [
              T=uint64_t
          ]
  buffer.cpp
D:\dev\adxe\external\openal\common\albit.h(135,1): warning C4127: 条件表达式是常量 [D:\dev\adxe\build\engine\external\openal\Op
enAL.vcxproj]
D:\dev\adxe\external\openal\al\buffer.cpp(365): message : 查看对正在编译的函数 模板 实例化“int al::countr_zero<uint64_t>(T)”的引用 [D:\de
v\adxe\build\engine\external\openal\OpenAL.vcxproj]
          with
          [
              T=uint64_t
          ]
  effect.cpp
D:\dev\adxe\external\openal\common\albit.h(135,1): warning C4127: 条件表达式是常量 [D:\dev\adxe\build\engine\external\openal\Op
enAL.vcxproj]
D:\dev\adxe\external\openal\al\effect.cpp(188): message : 查看对正在编译的函数 模板 实例化“int al::countr_zero<uint64_t>(T)”的引用 [D:\de
v\adxe\build\engine\external\openal\OpenAL.vcxproj]
          with
          [
              T=uint64_t
          ]
  error.cpp
  event.cpp
D:\dev\adxe\external\openal\al\event.cpp(204,36): warning C4834: 放弃具有 "nodiscard" 属性的函数的返回值 [D:\dev\adxe\build\engine\e
xternal\openal\OpenAL.vcxproj]
  extension.cpp
  filter.cpp
D:\dev\adxe\external\openal\common\albit.h(135,1): warning C4127: 条件表达式是常量 [D:\dev\adxe\build\engine\external\openal\Op
enAL.vcxproj]
D:\dev\adxe\external\openal\al\filter.cpp(361): message : 查看对正在编译的函数 模板 实例化“int al::countr_zero<uint64_t>(T)”的引用 [D:\de
v\adxe\build\engine\external\openal\OpenAL.vcxproj]
          with
          [
              T=uint64_t
          ]
  listener.cpp
  source.cpp
D:\dev\adxe\external\openal\common\albit.h(135,1): warning C4127: 条件表达式是常量 [D:\dev\adxe\build\engine\external\openal\Op
enAL.vcxproj]
D:\dev\adxe\external\openal\al\source.cpp(732): message : 查看对正在编译的函数 模板 实例化“int al::countr_zero<uint64_t>(T)”的引用 [D:\de
v\adxe\build\engine\external\openal\OpenAL.vcxproj]
          with
          [
              T=uint64_t
          ]
  state.cpp
  alc.cpp
D:\dev\adxe\external\openal\common\albit.h(135,1): warning C4127: 条件表达式是常量 [D:\dev\adxe\build\engine\external\openal\Op
enAL.vcxproj]
D:\dev\adxe\external\openal\alc\alc.cpp(1992): message : 查看对正在编译的函数 模板 实例化“int al::countr_zero<uint64_t>(T)”的引用 [D:\dev
\adxe\build\engine\external\openal\OpenAL.vcxproj]
          with
          [
              T=uint64_t
          ]
  alu.cpp
  alconfig.cpp
  effectslot.cpp
  panning.cpp
  base.cpp
D:\dev\adxe\external\openal\common\albit.h(135,1): warning C4127: 条件表达式是常量 [D:\dev\adxe\build\engine\external\openal\Op
enAL.vcxproj]
D:\dev\adxe\external\openal\alc\backends\base.cpp(185): message : 查看对正在编译的函数 模板 实例化“int al::countr_zero<uint>(T)”的引用 [D
:\dev\adxe\build\engine\external\openal\OpenAL.vcxproj]
          with
          [
              T=uint
          ]
D:\dev\adxe\external\openal\common\albit.h(139,1): warning C4293: “>>”: Shift 计数为负或过大，其行为未定义 [D:\dev\adxe\build\engine\
external\openal\OpenAL.vcxproj]
  loopback.cpp
  winmm.cpp
  dsound.cpp
  wasapi.cpp
  正在生成代码...
  正在编译...
  wave.cpp
D:\dev\adxe\external\openal\alc\backends\wave.cpp(152,66): warning C4127: 条件表达式是常量 [D:\dev\adxe\build\engine\external\o
penal\OpenAL.vcxproj]
  ambdec.cpp
  ambidefs.cpp
  bformatdec.cpp
  bs2b.cpp
  bsinc_tables.cpp
  buffer_storage.cpp
  converter.cpp
  cpu_caps.cpp
  devformat.cpp
  except.cpp
  biquad.cpp
  nfc.cpp
  splitter.cpp
  fmt_traits.cpp
  fpu_ctrl.cpp
  helpers.cpp
  hrtf.cpp
D:\dev\adxe\external\openal\core\hrtf.cpp(458,1): warning C4127: 条件表达式是常量 [D:\dev\adxe\build\engine\external\openal\Ope
nAL.vcxproj]
D:\dev\adxe\external\openal\core\hrtf.cpp(486): message : 查看对正在编译的函数 模板 实例化“T `anonymous-namespace'::readle<uint32_t,32
>(std::istream &)”的引用 [D:\dev\adxe\build\engine\external\openal\OpenAL.vcxproj]
          with
          [
              T=uint32_t
          ]
D:\dev\adxe\external\openal\core\hrtf.cpp(471,1): warning C4127: 条件表达式是常量 [D:\dev\adxe\build\engine\external\openal\Ope
nAL.vcxproj]
  logging.cpp
  mastering.cpp
  正在生成代码...
  正在编译...
  mixer.cpp
  uhjfilter.cpp
  uiddefs.cpp
  voice.cpp
  mixer_c.cpp
  mixer_sse.cpp
  mixer_sse2.cpp
  mixer_sse3.cpp
  mixer_sse41.cpp
  正在生成代码...
  autowah.cpp
  chorus.cpp
  compressor.cpp
  convolution.cpp
  dedicated.cpp
  distortion.cpp
  echo.cpp
  equalizer.cpp
  fshifter.cpp
  modulator.cpp
  null.cpp
  pshifter.cpp
  reverb.cpp
  vmorpher.cpp
  context.cpp
  device.cpp
  autowah.cpp
  chorus.cpp
  compressor.cpp
  convolution.cpp
  dedicated.cpp
  distortion.cpp
  echo.cpp
  equalizer.cpp
  fshifter.cpp
  modulator.cpp
  null.cpp
  pshifter.cpp
  reverb.cpp
  vmorpher.cpp
  null.cpp
  context.cpp
  device.cpp
    正在创建库 D:/dev/adxe/build/lib/Debug/OpenAL32.lib 和对象 D:/dev/adxe/build/lib/Debug/OpenAL32.exp
  OpenAL.vcxproj -> D:\dev\adxe\build\bin\Debug\OpenAL32.dll
```

**Comment by johnspeny** [comment]
It has refused on my pc, okay at least how do I disable or remove it from my project.

**Comment by halx99** [comment]
The message maybe the reason:
```txt
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\complex(1,1): warning C4821: Unable to determine Unicode encoding type, please save the file with signature (BOM)
1>C:\Dev\adxe\external\openal\common\alcomplex.h(13,38): error C2039: 'complex': is not a member of 'std'
```

**Comment by johnspeny** [comment]
1>C:\Dev\adxe\external\openal\common\alcomplex.h(13,38): error C2039: 'complex': is not a member of 'std'

I opened alcomplex.h and I see std::complex underlined in red.

Which version of c++ are u using.
Is urs also underlined?.

**Comment by halx99** [comment]
c++14 is required

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by johnspeny** [comment]
I use c++14 by default. Still same problem.

**Comment by aismann** [comment]
Please add: "Visual Studio Community 2019" on the title.
With the professional its works.

**Comment by johnspeny** [comment]
it now works well.
