### ISSUE TITLE
Add on all 3rd party libs a version or at least a github ID

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#366]
At this moment I dont know the correct version on some 3rd party libs'
Better to make an update and add the github id on the readme 

astc  2.5   (26 Mar)
https://github.com/ARM-software/astc-encoder/releases/tag/2.5

LLVM (ConvertUTF)   LLVM 12.0.0  (15 April)
https://github.com/llvm/llvm-project

poly2tri git 7f0487a  (13 days ago)
https://github.com/jhasse/poly2tri

Only md5 seems to be without any link.

**Comment by halx99** [comment]
Since openssl or mbedtls contains md5 digest implementation, the md5.h/md5.c maybe remove in the future

**Comment by aismann** [comment]
@halx99 No problem, so maybe the other three libs above have to be update?

**Comment by halx99** [comment]
Updated: https://github.com/adxeproject/adxe/commit/e0beb6cf27082f3eecf55ce2e212828c66cc9601

**Comment by aismann** [comment]
astc 2.5 (26 Mar)
https://github.com/ARM-software/astc-encoder/releases/tag/2.5

or later version is missing

**Comment by halx99** [comment]
Now, everythings of this issues updated: https://github.com/adxeproject/adxe/commit/9321a65e8c3fe3538fffa200e1defa40239d8302
