### ISSUE TITLE
win32 debug verion has build errors  (release version works)

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#368]
- adxe version: latest
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS/msvctools version: Visual Studio 2019/14.28.29910
   - cmake version: 
Steps to Reproduce:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file '..\..\..\lib\Debug\box2d.lib'	cpp-tests	D:\_____GitHub___\adxe\build\engine\tests\cpp-tests\LINK	1	
Error	C1090	PDB API call failed, error code '3': D:\_____GitHub___\adxe\build\lib\Debug\box2d.pdb	box2d	D:\_____GitHub___\adxe\external\box2d\src\dynamics\b2_weld_joint.cpp	1	
Error	C1090	PDB API call failed, error code '3': D:\_____GitHub___\adxe\build\lib\Debug\webp.pdb	webp	D:\_____GitHub___\adxe\external\webp\src\dsp\lossless_enc_sse41.c	1

**Comment by halx99** [comment]
but the github win32 debug build action works fine: https://github.com/adxeproject/adxe/runs/2723045313?check_suite_focus=true

**Comment by aismann** [comment]
I tried it again. With the latest adxe from now:
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file '..\..\..\lib\Debug\adxe.lib'	cpp-tests	D:\_____GitHub___\adxe\build\engine\tests\cpp-tests\LINK	1	
Error	LNK1104	cannot open file '..\..\..\lib\Debug\common.lib'	OpenAL	D:\_____GitHub___\adxe\build\engine\external\openal\LINK	1	
Error	C1041	cannot open program database 'D:\_____GitHub___\adxe\build\lib\Debug\adxe.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS	adxe	D:\_____GitHub___\adxe\cocos\audio\src\AudioEngineImpl.mm	1	
Error	C1090	PDB API call failed, error code '3': D:\_____GitHub___\adxe\build\engine\external\curl\lib\libcurl.dir\Debug\vc142.pdb	libcurl	D:\_____GitHub___\adxe\external\curl\lib\ftp.c	1	
Error	C1090	PDB API call failed, error code '3': D:\_____GitHub___\adxe\build\lib\Debug\common.pdb	common	D:\_____GitHub___\adxe\external\openal\common\threads.cpp	1	
Error	C1090	PDB API call failed, error code '3': D:\_____GitHub___\adxe\build\lib\Debug\jpeg.pdb	jpeg	D:\_____GitHub___\adxe\external\jpeg\jdatadst.c	1	
Error	C1090	PDB API call failed, error code '3': D:\_____GitHub___\adxe\build\lib\Debug\ogg.pdb	ogg	D:\_____GitHub___\adxe\external\ogg\src\vorbis\vorbisfile.c	1	
Error	C1090	PDB API call failed, error code '3': D:\_____GitHub___\adxe\build\lib\Debug\recast.pdb	recast	D:\_____GitHub___\adxe\external\recast\DetourTileCacheBuilder.cpp	1	
Error	C1090	PDB API call failed, error code '3': D:\_____GitHub___\adxe\build\lib\Debug\webp.pdb	webp	D:\_____GitHub___\adxe\external\webp\src\enc\config_enc.c	1	
Error	C1090	PDB API call failed, error code '5': D:\_____GitHub___\adxe\build\lib\Debug\box2d.pdb	box2d	D:\_____GitHub___\adxe\external\box2d\src\dynamics\b2_weld_joint.cpp	1

**Comment by halx99** [comment]
Your error output is so strange, I have no idea yet.

**Comment by aismann** [comment]
very crazy:
I build it again and again, after each build the errors be gone more and more.
After ca 5 builds the cpp-test.exe is build and works as far as I can see.

On one of the error is this (/FS): seems errors comes with multiple CL.EXE on the same .PDB file
Error C1041 cannot open program database 'D:__GitHub\adxe\build\lib\Debug\adxe.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS adxe D:__GitHub\adxe\cocos\audio\src\AudioEngineImpl.mm 1

**Comment by halx99** [comment]
> very crazy:
> I build it again and again, after each build the errors be gone more and more.
> After ca 5 builds the cpp-test.exe is build and works as far as I can see.
> 
> On one of the error is this (/FS): seems errors comes with multiple CL.EXE on the same .PDB file
> Error C1041 cannot open program database 'D:__GitHub\adxe\build\lib\Debug\adxe.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS adxe D:__GitHub\adxe\cocos\audio\src\AudioEngineImpl.mm 1

Is it convenient for you to remotely assist through teamviewer, let me check what happend on your PC?

**Comment by aismann** [comment]
It works  on another machine.

**Comment by halx99** [comment]
ok, I close this issue
