### ISSUE TITLE
ASTC Test has artefakte (is this correct or some settings on my machine)?

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#370]
- adxe version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS/msvctools version: Visual Studio 2019/14.28.29910
   - cmake version: 
Steps to Reproduce:

1. open  2: Texture2D
2. the red letter has also artefakte
![image](https://user-images.githubusercontent.com/8652787/120894691-17762480-c61a-11eb-844f-2cac0ada710a.png)

**Comment by halx99** [comment]
What's your device card, Nvidia or AMD, my computer with NV works well

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: aismann ***@***.***>
Sent: Saturday, June 5, 2021 10:32:35 PM
To: adxeproject/adxe ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [adxeproject/adxe] ASTC Test has artefakte (is this correct or some settings on my machine)? (#370)


  *   adxe version:
  *   devices test on:
  *   developing environments
     *   NDK version:
     *   Xcode version:
     *   VS/msvctools version: Visual Studio 2019/14.28.29910
     *   cmake version:
Steps to Reproduce:

  1.  open 2: Texture2D
  2.  the red letter has also artefakte
[image]<https://user-images.githubusercontent.com/8652787/120894691-17762480-c61a-11eb-844f-2cac0ada710a.png>

**Comment by halx99** [comment]
And check output, does's your display card support hardware to decode astc

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by halx99** [comment]
And software decoder also works well: 
![image](https://user-images.githubusercontent.com/6977319/120898467-96408100-c65d-11eb-9024-e9341cee44a8.png)

![image](https://user-images.githubusercontent.com/6977319/120898482-a0627f80-c65d-11eb-8f8c-b147372d686a.png)

**Comment by aismann** [comment]
I checked it on some windows machines: ASTC test works correct!
If I have more time I will check the graphic settings on the "bad" machine again.
At the moment I have to work.

**Comment by aismann** [comment]
I have checked it again:
Left is the release  and right the debug windows app (same machine)
![image](https://user-images.githubusercontent.com/8652787/121234010-8c07c800-c893-11eb-8768-c3ccb1b21cd0.png)

**Comment by halx99** [comment]
So does your computer support astc hardware decode?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by halx99** [comment]
I can comfirm, it's bug of arm astcenc when build with sse2

**Comment by halx99** [comment]
I open a issue on astc-encoder: https://github.com/ARM-software/astc-encoder/issues/259

**Comment by halx99** [comment]
It's a msvc compiler codegen bug, see also: https://github.com/ARM-software/astc-encoder/commit/b43d3a2736d9b4eb67b388743faa8f3282088ac5

**Comment by halx99** [comment]
And vs2019 16.10.1/MSVC 19.29.30037.0 seems fixed

**Comment by aismann** [comment]
Nice to found it ;)

**Comment by aismann** [comment]
Works now!
