### ISSUE TITLE
iOS arm64 armv7 build issue

### ISSUE THREAD

**Issue by efreyu** [adxeproject/adxe#371]
Hello. First of all, I would like to thank you for the development of this important and complex project. You inspire me to explore a new technologies in game development and create my own small projects.
At first it seemed to me that it had something to do with the `libstdc++` library from `iphone.sdk`, and then i found the undefined variable `SIZEOF_SIZE_T` in `build/engine/external/jpeg/inc/jconfigint.h`
`/* The size of 'size_t', as computed by sizeof. */`
`#define SIZEOF_SIZE_T  0`
I suppose that this is due to the architecture of the processor, because in the desktop version this problem does not exist and the variable is correctly initialized.
I will be glad for any help and recommendations on how to fix it. Thank you and have a nice day!
- developing environments
   - Macos: 11.3.1, 11.4
   - Xcode version: 12.3, 12.4, 12.5
   - cmake version: 3.20.3
1.  Build command used: `cmake -S . -B build -GXcode -DCMAKE_TOOLCHAIN_FILE=cmake/ios.mini.cmake && cmake --build build --config Release --target adxe -- -quiet -jobs 12`
2. Output in the attached file
[macos 11.3.1 result_cmake.txt](https://github.com/adxeproject/adxe/files/6602803/result_cmake.txt)
[macos 11.3.1 result_build.txt](https://github.com/adxeproject/adxe/files/6602805/result_build.txt)
1.  Build command used: `cmake -S . -B build -GXcode -DCMAKE_TOOLCHAIN_FILE=cmake/ios.mini.cmake -DCMAKE_OSX_SYSROOT=iphoneos -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO -DBUILD_EXT_ALSOFT=ON && cmake --build build --config Release --target adxe -- -quiet -jobs 12`
2. Output in the attached file
[result_cmake_11.4.txt](https://github.com/adxeproject/adxe/files/6602962/result_cmake_11.4.txt)
[result_build_11.4.txt](https://github.com/adxeproject/adxe/files/6602963/result_build_11.4.txt)

**Comment by halx99** [comment]
Thanks for your report, I will check it later

**Comment by halx99** [comment]
Please try:
cmake -S . -B build -GXcode -DCMAKE_TOOLCHAIN_FILE=cmake/ios.mini.cmake -DCMAKE_OSX_ARCHITECTURES=arm64

**Comment by efreyu** [comment]
@halx99 Thank you for your reply.
Console build with `-DCMAKE_OSX_ARCHITECTURES=arm64` was successful, but this is not enough to send app to testflight. I tried to do the same for armv7 but got errors like in the last post.
As far as I understand, for sending it is necessary that the xcode has build both architectures. But I could be wrong.
Previously undefined variable `SIZEOF_SIZE_T` has now changed.
`/* The size of 'size_t', as computed by sizeof. */`
`#define SIZEOF_SIZE_T  8`

**Comment by halx99** [comment]
Well, maybe some thirdparty libs not sutiable xcode multi-arch build, the config file cmake script maybe needs adpate `"-DCMAKE_OSX_ARCHITECTURES=arm64;armv7"` to generate common config file

**Comment by halx99** [comment]
And I have test multi arch for ios, the jpeg-turbo official cmake will report: doesn't support it.

**Comment by halx99** [comment]
so jpeg-turbo needs build as prebuilt lib like openssl: https://github.com/adxeproject/buildware

**Comment by efreyu** [comment]
Thank you, i will try do it later.

**Comment by halx99** [comment]
The latest master finished to use prebuilt jpeg-turbo from  https://github.com/adxeproject/buildware, now the `buildware repo` can produce openssl, jpeg-turbo prebuit libs with github actions automatically.

**Comment by efreyu** [comment]
I tested these changes on Mac and iOS, everything works. Thank you.
