### ISSUE TITLE
[iOS] Error when building for arm64 simulator

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#376]
- adxe version: latest
- devices test on: N/A
- developing environments
   - Xcode version: 12.5
   - cmake version: 3.20.2

Cmake is run with this command:
`cmake .. -GXcode -DCMAKE_TOOLCHAIN_FILE=../cocos2d/cmake/ios.mini.cmake -DCMAKE_OSX_SYSROOT=iphonesimulator -DCMAKE_OSX_ARCHITECTURES=arm64`

This is the error appearing when it tries to link certain libraries:
```
In /app/cocos2d/thirdparty/openssl/prebuilt/ios/libcrypto.a(aes_cfb.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
```

If I use this cmake command:
`cmake .. -GXcode -DCMAKE_TOOLCHAIN_FILE=../cocos2d/cmake/ios.mini.cmake -DCMAKE_OSX_ARCHITECTURES=arm64`

and I try to build for a arm64 simulator, then I get this error:
```
Building for iOS Simulator, but linking in .tbd built for iOS, file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/lib/libbz2.tbd' for architecture arm64
```

Is there anything I should be doing differently?

**Comment by halx99** [comment]
Currently, the iphone simulator arm64 target doesn't support yet,, should use `x86_64`

**Comment by rh101** [comment]
No worries

**Comment by rh101** [comment]
Since the `x86_64` version of the simulator is supported and working great on the Apple M1 hardware, should we close this issue?

**Comment by halx99** [comment]
Can be close if we don't plan support arm simulator, and if x86_64 simulator works well on Apple M1 hardware, arm simulator support is pointless

**Comment by rh101** [comment]
That is the case, so all good, I'll just close this.
