### ISSUE TITLE
[iOS] ASTC x86_64 iOS simulator build fails

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#377]
- adxe version: latest
- devices test on:
- developing environments
   - Xcode version: 12.5
   - cmake version: 3.20.2
Steps to Reproduce:

Using cmake command:
`cmake .. -GXcode -DCMAKE_TOOLCHAIN_FILE=cmake/ios.mini.cmake -DCMAKE_OSX_ARCHITECTURES=x86_64`

Getting this error when building in Xcode:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.5/include/arm_neon.h:28:2: "NEON intrinsics not available with the soft-float ABI. Please use -mfloat-abi=softfp or -mfloat-abi=hard"

```

The issue is in `arm_neon.h`:
```
...
#ifndef __ARM_NEON_H
#define __ARM_NEON_H

#ifndef __ARM_FP
#error "NEON intrinsics not available with the soft-float ABI. Please use -mfloat-abi=softfp or -mfloat-abi=hard"
#else
...
```

For some reason it's picking up ARM NEON is being active in the cmake project creation, when it shouldn't be.  

Does the x86_64 build actually work on an Intel Mac?  if it does, then it may just be an issue with the Apple ARM M1 Mac machines.

I'll disable ASTC support in this build for now to see if the rest of the code compiles.

**Comment by halx99** [comment]
The github action build ios simulator x86_64

**Comment by halx99** [comment]
Please ensure clear CMakeCache.txt before you generate x86_64 xcodeproj, and upload the file CMakeOutput.txt and CMakeError.txt

**Comment by rh101** [comment]
The build succeeded when I disabled ASTC in CMake and commented out the code related to ASTC in `astc.cpp`, and the x86_64 app ran successfully in the simulator on the ARM Mac M1.  

> Please ensure clear CMakeCache.txt before you generate x86_64 xcodeproj, and upload the file CMakeOutput.txt and CMakeError.txt

I'll delete the build folder completely and recreate it again with cmake, that way I'll know for sure if it's an issue with the ASTC or my setup, and if the issue persists I'll upload the CMake logs. :)

**Comment by rh101** [comment]
@halx99 Doing a clean build worked, so it was a silly mistake by me. I'll close this PR.  I'm sorry for any time you wasted on this!
