### ISSUE TITLE
Chimunk2D - TestBed:  Changing the DesignResolutionSize set not the menu labels (position)

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#392]
(for a better screen view I changed with the latest Chipmunkk2D - Testbed version (Branch: Chipmunk2D):
```
   auto director = Director::getInstance();
    auto glview   = director->getOpenGLView();
    Size designSize(960 * 0.8, 640 * 0.8);
    glview->setDesignResolutionSize(designSize.width, designSize.height, ResolutionPolicy::NO_BORDER);
```

   - VS/msvctools version: Visual Studio 2019/14.28.29910
   - cmake version: 
Steps to Reproduce:

1. Start Chipmunk2D - Testbed
2. Go back tho the root menue (back button)

The menue will be shown correct AFTER  you select another Menu (not the Chipmunk2D - Testbed)

**Comment by halx99** [comment]
## Note: 
We should restore window and design size before create a new scene, otherwise, the layout will incorrect.
