### ISSUE TITLE
dev branch has unresolved ....

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#396]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	3 unresolved externals	cpp-tests	D:\_____GitHub___\adxe\build\bin\cpp-tests\Release\cpp-tests.exe	1	
Error	LNK2019	unresolved external symbol _llhttp_init referenced in function "private: void __thiscall cocos2d::network::HttpClient::processResponse(class cocos2d::network::HttpResponse *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?processResponse@HttpClient@network@cocos2d@@AAEXPAVHttpResponse@23@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	cpp-tests	D:\_____GitHub___\adxe\build\engine\tests\cpp-tests\adxe.lib(HttpClient.obj)	1	
Error	LNK2019	unresolved external symbol _llhttp_settings_init referenced in function "private: void __thiscall cocos2d::network::HttpClient::processResponse(class cocos2d::network::HttpResponse *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?processResponse@HttpClient@network@cocos2d@@AAEXPAVHttpResponse@23@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	cpp-tests	D:\_____GitHub___\adxe\build\engine\tests\cpp-tests\adxe.lib(HttpClient.obj)	1	
Error	LNK2019	unresolved external symbol _llhttp_execute referenced in function "private: void __thiscall cocos2d::network::HttpClient::handleNetworkEvent(class yasio::inet::io_event *)" (?handleNetworkEvent@HttpClient@network@cocos2d@@AAEXPAVio_event@inet@yasio@@@Z)	cpp-tests	D:\_____GitHub___\adxe\build\engine\tests\cpp-tests\adxe.lib(HttpClient.obj)	1

**Comment by halx99** [comment]
You needs to delete CMakeCache.txt on your build dir and regenerate adxe.sln again

**Comment by aismann** [comment]
Maybe deleting during the build (if exist) is a better way?

**Comment by halx99** [comment]
Delete CMakeCache.txt is ok

**Comment by aismann** [comment]
Works (after delete CMakeCache.txtdelete CMakeCache.txt)
