### ISSUE TITLE
Wish we have some more draw primitives....(at least a drawSolidSegment  and a drawSegment (with a borderwith and different color)

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#397]
I miss:

Please change 
cocos2d::DrawNode::drawSegment=> rename it to drawSolidSegment  (like drawSolidCircle)
cocos2d::DrawNode::drawSegment=> add outlineColor, fillColor and borderWidth

The new one should call like:
void DrawNode::drawSegment(const Vec2 &from, const Vec2 &to, float radius, const Color4F &fillColor, float borderWidth, const Color4F &borderColor)

for backwards compatibility borderWidth, &borderColor should have default value?

Some more ideas:
DrawRoundRect
DrawSolidRoundRect

Not so important: (only ideas)
DrawStar   (with parameter how much spikes, deep, etc))
DrawSolidStar

Maybe you have also some ideas which be supported by adxe?

**Comment by halx99** [comment]
Agree, could you post a pull-request for this?

**Comment by aismann** [comment]
Im not realy a good OpenGL programmers 
A pull request needs source code (as far a know)?

**Comment by aismann** [comment]
[ADD]     void drawSolidCircle(const Vec2& center, float radius, float angle, unsigned int segments, float scaleX, float scaleY, const Color4F& fillColor, float borderWidth, const Color4F& borderColor);

**Comment by aismann** [comment]
Closed it. Maybe I will add some more any time.
