### ISSUE TITLE
Working on the Box2D - TestBed compiling is ok, Testcpp.exe start, Box2D -Testbad can selected but I getting this error...

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#415]
![grafik](https://user-images.githubusercontent.com/8652787/124393063-e95b3180-dcf8-11eb-8fc6-36ee4765fafa.png)

Any ideas or a Bug on the CCDrawNode.cpp?
What can I check before I upload?

**Comment by halx99** [comment]
it seems the drawnode is nullptr

**Comment by halx99** [comment]
Please check do you really create DrawNode instance before you use any drawNode API

**Comment by aismann** [comment]
Thanks! Works now!
I can start to create the "Box2D -TestBed" for adxe now (lot of work !)

**Comment by aismann** [comment]
Can be closed now!
