### ISSUE TITLE
[Question] What is the purpose of FileStream::Mode::OVERLAPPED

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#416]
From #413 there is a change to the DownloadTaskCurl:

`_fsMd5 = FileUtils::getInstance()->openFileStream(_checksumFileName, FileStream::Mode::OVERLAPPED);`

I did notice the `O_TRUNC` flag is missing from `FileStream::Mode::OVERLAPPED`, but what is the difference in behavior between the `FileStream::Mode::WRITE` and `FileStream::Mode::OVERLAPPED`?

The reason for asking this is that I need to ensure that the VFS implementation of FileStream that I'm using replicates the behavior of the `FileStream::Mode::OVERLAPPED` option.

**Comment by halx99** [comment]
The mode WRITE will always trucate file size to zero when open.
The OVERLAP behavior same with 'APPEND'+'SEEK TO SET', it's useful to seralize and update md5 state realtime and resume file download at breakpoint

**Comment by rh101** [comment]
Thank you for the explanation!
