### ISSUE TITLE
Plesase add also https://github.com/mtsamis/box2d-optimized to the third party libs like Box2D

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#451]
Should be easily add to adxe like Box2d

https://github.com/mtsamis/box2d-optimized

Box2D-optimized is a Box2D fork that aims to offer improved perfromance and scalability, while maintaining a similar API and feature set. This library merges commits from upstream Box2D regularly in order to be up to date.

**Comment by halx99** [comment]
If the fork cmake script works well, could be simply replace current box2d folder

**Comment by aismann** [comment]
Great!
But can you add it to adxe without replacing the orginal Box2D?

**Comment by halx99** [comment]
But the box2d-optimized seems in alpha, working in progress
do you test the performance with original edition in adxe?

**Comment by aismann** [comment]
There is a folder which has some benchmark grafiphics on box2d-optimized.
No I test it not, but I belive is it working well.
alpha -> Thats is the reason to ADD it and not remove original Box2D.

**Comment by halx99** [comment]
Added https://github.com/adxeproject/adxe/commit/de925136c93d99edb070025d02b1e1dd5b3dadfe

**Comment by halx99** [comment]
use cmake option: OPT_BOX2D_OPTIMIZED=ON to enable it
