### ISSUE TITLE
cpp test: Node - Sprite: Is crashing on windows

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#457]
![image](https://user-images.githubusercontent.com/8652787/129590660-6a047b98-b904-4e1b-b454-e16c06957f63.png)

**Comment by rh101** [comment]
I'll take a look at it now in case it has something to do with the sprite sheet changes.

**Comment by rh101** [comment]
Fixed in #459 

This addresses other crashes in the sprite test as well. Sorry about that!
