### ISSUE TITLE
adxelua is not building on windows

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#460]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'cocos2d::ISpriteSheetLoader *cocos2d::SpriteFrameCache::getSpriteSheetLoader(uint32_t)': cannot convert argument 1 from 'std::string' to 'uint32_t'	adxelua	D:\______\GitHub\adxe\extensions\scripting\lua-bindings\auto\lua_cocos2dx_auto.cpp	98103	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'void cocos2d::SpriteFrameCache::addSpriteFramesWithFile(const std::string &,const std::string &,uint32_t)': cannot convert argument 2 from 'cocos2d::Texture2D *' to 'const std::string &'	adxelua	D:\______\GitHub\adxe\extensions\scripting\lua-bindings\auto\lua_cocos2dx_auto.cpp	98271	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'void cocos2d::SpriteFrameCache::deregisterSpriteSheetLoader(uint32_t)': cannot convert argument 1 from 'std::string' to 'uint32_t'	adxelua	D:\______\GitHub\adxe\extensions\scripting\lua-bindings\auto\lua_cocos2dx_auto.cpp	98601

**Comment by rh101** [comment]
The LUA bindings may need to be updated

**Comment by aismann** [comment]
I downloaded the whole adxe stuff before I build it.

**Comment by rh101** [comment]
The bindings were last updated 3 days ago, so the function signatures won't be correct for the changes made over the past day or so.  

Try to generate them using the instructions here: [](https://github.com/adxeproject/adxe/tree/dev/tools/tolua)

**Comment by rh101** [comment]
I'll try to generate them now and upload them in a new PR.

**Comment by rh101** [comment]
@aismann Check #461
