### ISSUE TITLE
Maybe needs int64_t for vfs when large than 4GB?

### ISSUE THREAD

**Issue by halx99** [adxeproject/adxe#467]
https://github.com/adxeproject/adxe/blob/11434287cd37bbcde503c923f916d3858bc2cf1c/cocos/platform/CCFileStream.h#L43

@rh101 Please take a look, the list API require int64:
- `virtual int64_t seek(int64_t offset, int origin) = 0;`
- `virtual int64_t tell() = 0;`
- `virtual int64_t size() = 0;`

**Comment by rh101** [comment]
I'd love to implement them for int64, but do you want both 32 and 64 versions, or just 64 bit?

**Comment by halx99** [comment]
I think just int64 for position or size of virutal file system is enough.

**Comment by rh101** [comment]
Excellent, that's what I was hoping for.  I'll get it all sorted over the next day.

**Comment by rh101** [comment]
I just realised `virtual int64_t seek(int64_t offset, int origin) = 0;` doesn't need i64_t as the return type, since it's just -1 for error, and 0 for no error.  I'll make it "long" return type to just keep it consistent with return types in posix etc.

**Comment by halx99** [comment]
> I just realised `virtual int64_t seek(int64_t offset, int origin) = 0;` doesn't need i64_t as the return type, since it's just -1 for error, and 0 for no error. I'll make it "long" return type to just keep it consistent with return types in posix etc.

ok, got it

**Comment by rh101** [comment]
Do you require the read and write methods to also have 64 bit values?  Realistically, would a game ever need to read or write more than 2^31 bytes at any given time?

**Comment by halx99** [comment]
No, I think game never needs to read or write 2GB+ buffer at on time

**Comment by halx99** [comment]
So, I think we don't needs to implement 64bit read write
