### ISSUE TITLE
Dear ImGui: Releases v1.84.1 (Latest 2 days ago)

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#472]

**Comment by halx99** [comment]
done: https://github.com/adxeproject/adxe/commit/d0d77730a946dbfbda8851230a0237f8313230a3

**Comment by aismann** [comment]
Weshould an an informationen about this Patch in the third party version upload page tooAm 23.08.2021 11:51 schrieb halx99 ***@***.***>:
Closed #472.
