### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by crazyhappygame** [adxeproject/adxe#473]
Hey, 
Great job!

Do you have benchmark comparing adxe with cocos2dx 4.0? (There are some performance issues in cocos2dx 4.0 and android).

How much APK size increased comparing to cocos2dx 4.0?

**Comment by aismann** [comment]
APK sitze can find in the Wiki page.

**Comment by halx99** [comment]
A little better: Left is `cocos2d-x-4.0`, right is `adxe`
![image](https://user-images.githubusercontent.com/6977319/131435144-112d41df-60c8-4e7f-adb6-004f8f8d0b74.png)
![image](https://user-images.githubusercontent.com/6977319/131435283-3a9e239b-6feb-409a-b87d-165bbf1a45dd.png)

**Comment by aismann** [comment]
adxe can be faster: look on the windows title (its debug modus) ;)
