### ISSUE TITLE
Crash with some .ttf caused by #384

### ISSUE THREAD

**Issue by halx99** [adxeproject/adxe#480]
- adxe version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS/msvctools version: Visual Studio 2019/14.28.29910
   - cmake version: 
Steps to Reproduce:

1. 
2.
[Freeride.zip](https://github.com/adxeproject/adxe/files/7068295/Freeride.zip)
![image](https://user-images.githubusercontent.com/6977319/131157840-be431ad5-7a7d-4ac9-b1f3-2ba01554aeb1.png)

@rh101 Do you have time take a look about this issue?

**Comment by rh101** [comment]
Yes, I'll look into it today.  Was the TTF library updated?

**Comment by halx99** [comment]
Yes, update to 2.11.0, I will test does 2.10.4 has this issue

**Comment by halx99** [comment]
The 2.10.4 also has this problem

**Comment by rh101** [comment]
Thanks for looking into it, and the fix.

**Comment by halx99** [comment]
You can review the PR, and check does it have other affects.

**Comment by rh101** [comment]
I'm in the process of testing it with the primary project I'm working on, which uses a fair number of TTF files, and hopefully it all goes well.

**Comment by halx99** [comment]
Good, if everything looks well, please tell me to merge the PR, thanks
