### ISSUE TITLE
Updated shader uniforms not rendered properly on Spine nodes

### ISSUE THREAD

**Issue by etsek** [adxeproject/adxe#482]
- adxe version: adxe-1.0.0b2
- devices test on: iPhone XR
- developing environments
   - NDK version:
   - Xcode version:
   - VS/msvctools version: Visual Studio 2019/14.28.29910
   - cmake version: 
Steps to Reproduce:

1. Apply a custom shader to a Spine node (ex. example_Blur.fsh)
2. Set a uniform value (ex. blurRadius), check if node is updated

The following macro as defined in cpp-tests used to work for Spine nodes as well but not anymore.

#define SET_UNIFORM(ps, name, value)  do {   \
decltype(value) __v = value;                           \
auto __loc = (ps)->getUniformLocation(name);  \
(ps)->setUniform(__loc, &__v, sizeof(__v));  \
} while(false) 
 
For comparison you can apply the same uniform update to a Sprite node and check results.

**Comment by halx99** [comment]
Does it works on windows?

**Comment by etsek** [comment]
Same problem on Windows, iOS, Android etc

**Comment by halx99** [comment]
does cocos2d-x-4.0 works?

**Comment by halx99** [comment]
What's your example code, I have test, it works:
```
#define SET_UNIFORM(ps, name, value)                          \
    do                                                        \
    {                                                         \
        decltype(value) __v = value;                          \
        auto __loc          = (ps)->getUniformLocation(name); \
        (ps)->setUniform(__loc, &__v, sizeof(__v));           \
    } while (false) 

auto programCache = backend::ProgramCache::getInstance();
programCache->registerCustomProgramFactory(
    101, positionTextureColor_vert, FileUtils::getInstance()->getStringFromFile("Shaders/example_Blur.fsh"));
auto program = programCache->getCustomProgram(101);

skeletonNode->setProgramState(new backend::ProgramState(program), false);
auto skeleton1PS = skeletonNode->getProgramState();

Vec2 resolution{100.f, 100.f};
float blurRadius = 50.0f;
float sampleNum  = 7.0f;
SET_UNIFORM(skeleton1PS, "resolution", resolution);
SET_UNIFORM(skeleton1PS, "blurRadius", blurRadius);
SET_UNIFORM(skeleton1PS, "sampleNum", sampleNum);
```

**Comment by etsek** [comment]
What I'm noticing is this: when SET_UNIFORM is called immediately after the shader is applied to the Spine node (as in your example) it indeed does work. However when SET_UNIFORM is called from another location, i.e. a different method of the same layer class then the change is not reflected on the Spine node. I've been calling SET_UNIFORM for both Sprite and Spine nodes this way and noticed sprite nodes are updated properly while Spine nodes are not. 

I will try to integrate this use case into an existing test class in cpp-tests for you to be able to reproduce this behavior.

**Comment by rh101** [comment]
@halx99 If I recall correctly, this was a concern that was brought up a while back with the Spine team, and it was the reason for this PR: [https://github.com/EsotericSoftware/spine-runtimes/pull/1763](https://github.com/EsotericSoftware/spine-runtimes/pull/1763), but it was closed and never merged in.  The code in your PR #485 is a lot cleaner, and the end result should be the same, as it should fix the problem.

**Comment by etsek** [comment]
[SpineTest.zip](https://github.com/adxeproject/adxe/files/7077899/SpineTest.zip)

To reproduce this issue replace file SpineTest.cpp in cpp-tests, build/run and select test no. 44 (Node: Spine).
Navigate to 8:Spineboy and click twice on screen (spine node will go into slow motion). At this time SET_UNIFORM will have been called on the spine node program state and the sprite node will be appearing blurred.

**Comment by halx99** [comment]
Do you mean set uniform at next draw frame?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by halx99** [comment]
> [SpineTest.zip](https://github.com/adxeproject/adxe/files/7077899/SpineTest.zip)
> 
> To reproduce this issue replace file SpineTest.cpp in cpp-tests, build/run and select test no. 44 (Node: Spine).
> Navigate to 8:Spineboy and click twice on screen (spine node will go into slow motion). At this time SET_UNIFORM will have been called on the spine node program state and ONLY the sprite node will be appearing blurred.

I think I know what happen, in the `SkeletonBatch.cpp`, always use programState clone, and only when programType changed will update to command pipeline, that why you must apply uniform immidiately

**Comment by halx99** [comment]
There is a solution for `adxe` but not for cocos2d-x, adxe introduced a `UniformID` for `ProgramState`, we can check it at SkeletonBatch like follow:
```cpp
backend::ProgramState* SkeletonBatch::updateCommandPipelinePS(SkeletonCommand* command, backend::ProgramState* programState)
{
	auto& currentState = command->getPipelineDescriptor().programState;
	if(currentState == nullptr || currentState->getProgram() != programState->getProgram() || currentState->getUniformID() != programState->getUniformID()) {
		CC_SAFE_RELEASE(currentState);
		currentState = programState->clone();
		
		auto vertexLayout = currentState->getVertexLayout();
		auto locPosition = currentState->getAttributeLocation("a_position");
		auto locTexcoord = currentState->getAttributeLocation("a_texCoord");
		auto locColor = currentState->getAttributeLocation("a_color");
		vertexLayout->setAttribute("a_position", locPosition, backend::VertexFormat::FLOAT3, offsetof(V3F_C4B_T2F, vertices), false);
		vertexLayout->setAttribute("a_color", locColor, backend::VertexFormat::UBYTE4, offsetof(V3F_C4B_T2F, colors), true);
		vertexLayout->setAttribute("a_texCoord", locTexcoord, backend::VertexFormat::FLOAT2, offsetof(V3F_C4B_T2F, texCoords), false);
		vertexLayout->setLayout(sizeof(_vertices[0]));


		command->_locMVP = currentState->getUniformLocation("u_MVPMatrix");
		command->_locTexture = currentState->getUniformLocation("u_texture");
	}
	return currentState;
}
```

And also needs update uniformID at:
```cpp
bool SpineTestLayer::init()
{   
    if (!TestCase::init()) return false;

    EventListenerTouchOneByOne* listener = EventListenerTouchOneByOne::create();
    listener->onTouchBegan = [this](Touch* touch, cocos2d::Event* event) -> bool {
        if (!skeletonNode) return true;
        _touchIndex = (_touchIndex + 1) % 3;
        if (_touchIndex == 0)
        {
            skeletonNode->setDebugBonesEnabled(false);
            skeletonNode->setTimeScale(1.0f);
        }
        else if (_touchIndex == 1)
        {
            skeletonNode->setDebugBonesEnabled(true);
            skeletonNode->setTimeScale(1.0f);
        }
        else if (_touchIndex == 2)
        {
            skeletonNode->setDebugBonesEnabled(true);
            skeletonNode->setTimeScale(0.3f);

            // Get Spine node PS and update uniforms 
            auto skeleton1PS = skeletonNode->getProgramState();
    
            Vec2 resolution{100.f, 100.f};
            float blurRadius = 50.0f;
            float sampleNum  = 7.0f;

            // This doesn't work on Spine node, works on sprite node
            SET_UNIFORM(skeleton1PS, "resolution", resolution);
            SET_UNIFORM(skeleton1PS, "blurRadius", blurRadius);
            SET_UNIFORM(skeleton1PS, "sampleNum", sampleNum);
            skeleton1PS->updateUniformID();
        }
        return true;
    };
    _eventDispatcher->addEventListenerWithSceneGraphPriority(listener, this);

    SCALE_SKELETON_NODE(skeletonNode);

    return true;
}
```

**Comment by etsek** [comment]
I can confirm this fix solves the problem, what is peculiar is SET_UNIFORM was rendering properly right after issue  https://github.com/adxeproject/adxe/issues/234 was fixed back in Oct 2020 **without the need for updateUniformID()**.

**Comment by halx99** [comment]
Because, the old spine runtime clone ProgramState per frame without programType check

**Comment by etsek** [comment]
Hello , this fix has worked fine so far. Will you be making a push request for the change in updateCommandPipelinePS() ?
Thanks once again!

**Comment by halx99** [comment]
> Hello , this fix has worked fine so far. Will you be making a push request for the change in updateCommandPipelinePS() ?
> Thanks once again!

Done with https://github.com/adxeproject/adxe/commit/15be00be207b528da02d652189359a47490df460, and also post to spine team

**Comment by halx99** [comment]
Close with issue solved
