### ISSUE TITLE
In some cases, calling os.exit() will raise an error.

### ISSUE THREAD

**Issue by wzhengsen** [adxeproject/adxe#484]
- adxe version: lastest
- devices test on: 华为 HONOR
- developing environments
   - NDK version: 22.1.7171670
   - Android Studio: 4.2
   - cmake version: 
Steps to Reproduce:

1. Play any sound effect once;
2. Call lua function: os.exit();
3. Raise an error.

![image](https://user-images.githubusercontent.com/30433761/131310506-93bc0fb1-ec91-4edd-b585-70c9b8ecdf0f.png)

**Comment by halx99** [comment]
https://github.com/adxeproject/adxe/issues/550

**Comment by halx99** [comment]
This issue was fixed by the upstream commit: https://github.com/adxeproject/adxe/commit/8ab6ad0139c5a943801fdf917780b294db7c7b6e
