### ISSUE TITLE
Never use 'unsigned long' and 'long' for cross platform development

### ISSUE THREAD

**Issue by halx99** [adxeproject/adxe#487]
- [x] Remove dangerous lua  number conversion functions which beahvior incorrect on windows x64
- [ ] Remove any API with `unsigned long` and `long`, use `unsigned int` and `int` instead
- Let's some where `long` as-is which require external library
- [ ] Use `uintptr_t` or `intptr_t` instead `long` for converting pointer to integer type

**Comment by halx99** [comment]
> I'm a little confused by this. The use of `long` and `unsigned long` guarantee 32 bits of data, whereas `int` may change based on the architecture being compiled for to either 32 or 64 bits. Code that is specifically expecting 32 bits of data will start having issues if changed to `int` type, since the compiler may change it to 64bits.
> 
> Isn't usage of `long` (for 32bits) and `long long` (for 64bits) for methods that need the exact size of data the preferred way to handle things?
> 
> I can understand that there are methods which use `int`, and that the size of it doesn't matter to those methods, so `int` should be used there.

The size of long on differenct paltform differrent arch is:

- x64:
  - windows: 4bytes
  - linux/unix: 8bytes
- x86
  - windows: 4bytes
  - linux/unix: 4bytes

**Comment by rh101** [comment]
> x64:
> 
>     * windows: 4bytes
> 
>     * linux/unix: 8bytes

That I was not expecting, and yes, that would cause a problem.  Would it be better to use `int32_t` and `int64_t` explicitly instead if `long` and `long long`?

**Comment by halx99** [comment]
Yes, int32_t, int64_t is the best

**Comment by rh101** [comment]
> 
> 
> Yes, `int32_t`, `int64_t` is the best

It would be great if this is what the code uses.  Do you need help with these changes?

**Comment by halx99** [comment]
> > Yes, `int32_t`, `int64_t` is the best
> 
> It would be great if this is what the code uses. Do you need help with these changes?

That would be fine if you can help check this

**Comment by rh101** [comment]
I'm assuming usage of types like `int` and `long long` can stay as-is. and the only concern here is `long` and `unsigned long` which should be changed to `int32_t` and `uint32_t`.

Some methods can be changed to `int` instead of `int32_t` since the return size is irrelevant, like this method:
`virtual long FileStream::seek(int64_t offset, int origin) = 0;`
can become
`virtual int FileStream::seek(int64_t offset, int origin) = 0;`

or would you want to change that to this instead:
`virtual int32_t FileStream::seek(int64_t offset, int origin) = 0;`

**Comment by halx99** [comment]
`I'm assuming usage of types like int and long long can stay as-is. and the only concern here is long and unsigned long which should be changed to int32_t and uint32_t. ` correct

**Comment by rh101** [comment]
There are some tricky spots in the code like for the vorbis decoder (in AudioDecoderOgg), where the library does expect a `long` type:
```
typedef struct {
  size_t (*read_func)  (void *ptr, size_t size, size_t nmemb, void *datasource);
  int    (*seek_func)  (void *datasource, ogg_int64_t offset, int whence);
  int    (*close_func) (void *datasource);
  long   (*tell_func)  (void *datasource);
} ov_callbacks;
```

They seem to have explicit usage of `ogg_int64_t` where required, so I can only assume that they purposely used `long` there, knowing that it would be 64 bit on some platforms.  Is that a fair assumption?

**Comment by rh101** [comment]
There is also this:
```
struct PXIoF {
    int(*read)(PXFileHandle& handle, void*, unsigned int);
    long(*seek)(PXFileHandle& handle, long, int);
    int(*close)(PXFileHandle& handle);
    long long(*size)(PXFileHandle& handle);
};
```

The posix seek method uses `off_t`, which can become 64 bit if `__USE_FILE_OFFSET64` is defined. 

Perhaps we should just use `off_t` instead of int32_t for that.
```
struct PXIoF {
    int(*read)(PXFileHandle& handle, void*, unsigned int);
    off_t(*seek)(PXFileHandle& handle, off_t, int);
    int(*close)(PXFileHandle& handle);
    long long(*size)(PXFileHandle& handle);
};

static off_t pfs_posix_seek(PXFileHandle& handle, off_t offst, int origin) { return posix_lseek(handle._fd, offst, origin); }

static off_t pfs_obb_seek(PXFileHandle& handle, off_t offset, int origin) { return FileUtilsAndroid::getObbFile()->zfseek(&handle._zfs, offset, origin); }
```

etc..

**Comment by rh101** [comment]
See if #488 helps. Some places had to change to int64_t, like OBB related Android methods, and I've left some as-is (such as the `ov_callbacks`).

**Comment by halx99** [comment]
> See if #488 helps. Some places had to change to int64_t, like OBB related Android methods, and I've left some as-is (such as the `ov_callbacks`).

It's ok
