### ISSUE TITLE
A problem I'm not sure if it's a bug, or, is it designed that way?

### ISSUE THREAD

**Issue by wzhengsen** [adxeproject/adxe#489]
- adxe version: latest
- devices test on: any
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 

1. Use cocos2d::Label::createWithTTF(...) to create a label;
2. setMaxLineWidth(...) and setLineBreakWithoutSpace(true) and setOverflow(Label::Overflow::RESIZE_HEIGHT)
3. setString(...)
4. Yes, now the label is able to wrap lines.
5. However, when I use cocos2d::Label::create() to create a label, the label line wrap doesn't seem to work?

Is this expected behavior?

**Comment by halx99** [comment]
That's strange, can you dig to check what happen?

**Comment by wzhengsen** [comment]
This is because the _maxLineWidth length is not used correctly in the _getFontDefinition function. For a label with no Dimensions set, width is set to 0, but sometimes _maxLineWidth is available.

And I commited a PR to simply fix it.
