### ISSUE TITLE
cpptest: 41: Node: Physics is crashing (x64) latest adxe on windows

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#492]
- adxe version: latest (today)

![grafik](https://user-images.githubusercontent.com/8652787/131980644-018a0dea-026d-4252-8e8f-bdd90c2ae9db.png)

**Comment by halx99** [comment]
Does first win64 support revision works?

**Comment by halx99** [comment]
I have checked, win32 works, maybe only win64 issue

**Comment by halx99** [comment]
It's not bug, I have test change stack size to 10MB will works

**Comment by aismann** [comment]
How can I change the stack size?
