### ISSUE TITLE
About scrollTo* functions of listview and scrollview

### ISSUE THREAD

**Issue by wzhengsen** [adxeproject/adxe#494]
When I push a widget into a list view or scroll view, I have to wait until the next frame to call a function of type scrollTo* to scroll the view. 
If I choose to call such a function immediately, it usually doesn't take effect.

Is it necessary to wait until the next frame? Is there a more elegant way? 
For example, it could be called at any moment and take effect immediately.

**Comment by rh101** [comment]
For ListView, try calling `ListView::doLayout()` after using `pushBackCustomItem` etc., since it calls `requestDoLayout()` internally. If you want to force the layout update without actually adding anything to the container, then call `requestDoLayout()` and then `doLayout()`.  

After you do that, call one of the `scrollTo` methods to see if it works as you expect.

**Comment by wzhengsen** [comment]
@rh101 
Thank you,it works.
However, there is a small side effect after calling doLayout(),it will take me to the front of the listview.

This can cause some trouble in some cases, for example if I want to scroll to a new chat when there is one in the chat listview, this will cause to go back to the front of the listview first before scrolling.

**Comment by wzhengsen** [comment]
How can I do it so that after pushing in an item, I can scroll directly from the current position to the new item.

**Comment by rh101** [comment]
> However, there is a small side effect after calling doLayout(),it will take me to the front of the listview.

> How can I do it so that after pushing in an item, I can scroll directly from the current position to the new item.

Is there something preventing you from stepping through the code to figure out why it's happening? 

Off the top of my head, if there is an issue, you can probably work around it by calling `jumpToItem`, and passing the index of the position you're currently at, after calling `doLayout`.  You can then call `scrollTo` from that point.  That may work, but I strongly suggest you trace through the code to figure out why the `doLayout` is resetting the position.

**Comment by wzhengsen** [comment]
Thank you very much, I have found the root of the problem.

**Comment by rh101** [comment]
> Thank you very much, I have found the root of the problem.

Do you want to mention what the root of the problem is so you can help others who experience this issue?

**Comment by halx99** [comment]
Do we need fix something?

**Comment by wzhengsen** [comment]
I will submit a PR.
