### ISSUE TITLE
When using ImGui, there is a problem that the click event may penetrate the ImGui layer.

### ISSUE THREAD

**Issue by wzhengsen** [adxeproject/adxe#505]
- adxe version:latest
- devices test on:Windows 10
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 

Steps to Reproduce:

Forgive me for using custom ImGui lua bindings (these may not exist in adxe), but even with c++, they should be reproduced.

1. See lua code:
```lua
local click = false;
if imgui.BeginCombo("Hello","World") then
    click,self.comboInt = imgui.Combo("My Combo",self.comboInt,{"1","2","3"});
    if click then
        print("Click!");
    end
    imgui.EndCombo();
end
```
2.It looks like this:
![image](https://user-images.githubusercontent.com/30433761/134375433-977b6fac-1134-44a4-9471-78527930e530.png)

3.At this point, we click on the blank space and this click will penetrate  the ImGui layer.

**Comment by halx99** [comment]
Should be fixed by the commit https://github.com/adxeproject/adxe/commit/f9e766086c50977d0941defb80a5964ed4dffb71
