### ISSUE TITLE
When in some cases, ImGui will make the memory will grow infinitely.

### ISSUE THREAD

**Issue by wzhengsen** [adxeproject/adxe#506]
- adxe version:latest
- devices test on:Windows 10
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 
Steps to Reproduce:

1. See code:
```c++
if (ImGui::Begin("Window")) {
    if (ImGui::BeginChild("Child")) {
        ImGui::Text("Hello");
    }
    ImGui::EndChild();
}
ImGui::End();
```
2.The memory now looks fine:
![image](https://user-images.githubusercontent.com/30433761/134545904-ebb906e2-ab8e-41e7-b9f2-c65e9773e61c.png)

3.Now I move the ImGui window out of the main window:
![image](https://user-images.githubusercontent.com/30433761/134546165-40644be7-d99a-43cc-a0f7-16f4a30892f8.png)

**Comment by halx99** [comment]
There are some issues about memory leak:
- https://github.com/ocornut/imgui/issues/4468
- https://github.com/ocornut/imgui/issues/4504

**Comment by wzhengsen** [comment]
When I use a discrete graphics card, the memory leak disappears.
