### ISSUE TITLE
Another issue that may make it possible for clicks to penetrate the ImGui layer.

### ISSUE THREAD

**Issue by wzhengsen** [adxeproject/adxe#507]
- adxe version:latest
- devices test on:Windows 10
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 
Steps to Reproduce:

1. Make the cocos window lose focus.
2. With the cocos window out of focus, click on the ImGui layer and this click will penetrate the ImGui layer.

**Comment by halx99** [comment]
On mac, works well, I have no windows device currently on my hand

**Comment by aismann** [comment]
I will try it later.

**Comment by aismann** [comment]
adxe 64bit debug:
I can not see any issues.
Maybe Im doing wrong? 
@wzhengsen:  Can you explain it a little bit more what should happens, what Im have to do?

**Comment by wzhengsen** [comment]
![Record](https://user-images.githubusercontent.com/30433761/134685105-8f751e4b-0dd0-481f-b348-04c1f89bd1e2.gif)

**Comment by wzhengsen** [comment]
@aismann I submitted a screen recording.

**Comment by aismann** [comment]
Thanks.
I got it also. Same behavior as on the screen recording (using the "Back" Button)

**Comment by halx99** [comment]
This issue should be fixed by latest commit

**Comment by aismann** [comment]
Tried it again.
Seems to be fixed. THANKS.
