### ISSUE TITLE
OpenSSL3.0.0 issue

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#509]
- adxe version: dev/latest
- devices test on: Windows 10 x64
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 3.21
Steps to Reproduce:

I'm suddenly getting connection errors because of OpenSSL 3.0.0, so out of curiosity, has anyone tested ADXE with OpenSSL 3.0.0 yet? 

A null value is being returned from `SSL_get1_peer_certificate` after a successful connection:

```
ERR_clear_error();
int connect_result = SSL_connect(_ssl_connection);
if (connect_result != 1) return;
X509* server_cert = SSL_get1_peer_certificate(_ssl_connection);
if (server_cert == nullptr)
{
    // error, no X509 certificate
}
```

I'm not quite sure what is going on, since that piece of code is in a 3rd party library that I'm using, and I've traced it as far as that.  I may have to compile OpenSSL 3.0.0 from source and dive into it if no-one has any ideas why this may be happening.

**Comment by halx99** [comment]
The code come from curl?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: RH ***@***.***>
Sent: Monday, September 27, 2021 10:36:52 PM
To: adxeproject/adxe ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [adxeproject/adxe] OpenSSL3.0.0 issue (#509)


  *   adxe version: dev/latest
  *   devices test on: Windows 10 x64
  *   developing environments
     *   NDK version: r19c
     *   Xcode version: 12.4
     *   VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
     *   cmake version: 3.21
Steps to Reproduce:

I'm suddenly getting connection errors because of OpenSSL 3.0.0, so out of curiosity, has anyone tested ADXE with OpenSSL 3.0.0 yet?

A null value is being returned from SSL_get1_peer_certificate after a successful connection:

ERR_clear_error();
int connect_result = SSL_connect(_ssl_connection);
if (connect_result != 1) return;
X509* server_cert = SSL_get1_peer_certificate(_ssl_connection);
if (server_cert == nullptr)
{
    // error, no X509 certificate
}


I'm not quite sure what is going on, since that piece of code is in a 3rd party library that I'm using, and I've traced it as far as that. I may have to compile OpenSSL 3.0.0 from source and dive into it if no-one has any ideas why this may be happening.

**Comment by aismann** [comment]
32bit or 64bit  app?

**Comment by rh101** [comment]
> The code come from curl?

No, it's a WebSocket library that I'm using, [IXWebSocket](https://github.com/machinezone/IXWebSocket).  No matter, I'll switch over to the source distrubtion of OpenSSL to dig into this issue.  Would you happen to have a link to the build scripts used to create the OpenSSL binaries for ADXE?

> 32bit or 64bit app?

Windows x64 is what I've tested, but I'll test x86 as well soon.

**Comment by rh101** [comment]
The x86 versions works correctly, but the x64 does not.

**Comment by halx99** [comment]
It's auto build by https://github.com/adxeproject/buildware

**Comment by halx99** [comment]
You can comment other libs except openssl on https://github.com/adxeproject/buildware/blob/main/1k/build.ps1#L25, then run follow command at `buildware` root dir:
```psh
1k\build.ps1 windows x64
```

**Comment by halx99** [comment]
And I have test on `yasio`, get peer cert when handshake succeed, seems works well:
https://github.com/yasio/yasio/blob/main/yasio/yasio.cpp#L1429
![image](https://user-images.githubusercontent.com/6977319/135018267-54d3b780-06a3-4fff-8b7d-a0371fce41c8.png)

**Comment by rh101** [comment]
> And I have test on `yasio`, get peer cert when handshake succeed, seems works well:

Thank you for checking.

It must be something related to the WebSocket library, so at the moment I'm trying to figure out how to compile OpenSSL from source so I can trace into it.  I'll check the buildware info you posted.

**Comment by rh101** [comment]
@halx99 I'm having issues building it, with this error popping up:

```
apps\lib\libapps-lib-fmt.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\lib.EXE"' : return code '0x458'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
```

Would you happen to know what causes this error?

**Comment by rh101** [comment]
I'm getting some strange things happening.

Firstly, the issue is that `SSL->session` is null (only for Windows x64 build), so it's failing on this:

```
X509 *SSL_get0_peer_certificate(const SSL *s)
{
    if ((s == NULL) || (s->session == NULL))
        return NULL;
    else
        return s->session->peer;
}
```

Here's the weird part: I can step into `SSL_get0_peer_certificate()` while debugging the IXWebSocket library. but I cannot step into `SSL_connect()`.  What's even stranger is that I can actually put a breakpoint inside `SSL_connect()`, but it only triggers if it's called from libCURL, but the breakpoint will not trigger if it is called from the IXWebSocket library.  Has anyone ever experienced something like this before?

**Comment by halx99** [comment]
That's strange, does the IXWebSocket link with a different openssl library?

**Comment by rh101** [comment]
> That's strange, does the IXWebSocket link with a different openssl library?

That must be it, and it what I'm checking right now. I've never seen this happen before, so I think there is something in the CMakeLists.txt of the IXWebSocket that is forcing the usage of system libraries instead of the ones passed to it from ADXE.

**Comment by rh101** [comment]
All sorted, thank you @halx99 and @aismann 

The issue was with the CMake configuration of that IXWebSocket library, as it kept using `find_package(OpenSSL REQUIRED)` and was adding the system OpenSSL libraries to the `${OPENSSL_LIBRARIES}` list, which already had the ADXE OpenSSL libraries.
