### ISSUE TITLE
ProgramState::setTextureArray does not work properly

### ISSUE THREAD

**Issue by solan-solan** [adxeproject/adxe#510]
- adxe version:
- devices test on:
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 
Steps to Reproduce:
![ushort_to_int_bag](https://user-images.githubusercontent.com/73186496/135344544-d4c15bab-0bfe-49fa-9345-2c83296533da.jpg)

Take a look please. TextureInfo::slots vector has uint16_t base type> which is 'unsigned short'. At the attached screenshort there is type conversion of the unsigned short* to the int* pointer.

I have an issue with the ProgramState::setTextureArray by the reason (Only first texture in the array is rendered). All works fine if set uint32_t instead of uint16_t for the TextureInfo::slots.

**Comment by halx99** [comment]
Could you create a pull-request of your fix?

**Comment by solan-solan** [comment]
Sorry. I read it too late. I try to suggest some decision via pull request
next time, if any issue appears. But you have done good fix, thanks.

чт, 30 сент. 2021 г. в 03:19, halx99 ***@***.***>:
