### ISSUE TITLE
[Request] WebView implementation for Windows platform

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#511]
**Is your feature request related to a problem? Please describe.**
At the moment there is no implementation of WebView for the Windows platform builds. The only implementations that exist are for iOS and Android.  

The WebView is useful in many ways, but for this particular case, for use in Facebook Login/Sign in with Apple, where they offer no native Windows SDKs for this purpose.  The WebView would be loaded, the user signs in, and the WebView would be used to extract the response from the server response.

**Describe the solution you'd like**
A WebView implementation that works for Windows x86/x64.

**Describe alternatives you've considered**
At the moment looking into implementations for WebView that can serve the purpose.  I'm just wondering if anyone here has any suggestions.

**Additional context**
There was a Cocos2d-x Win32 WebView implementation that was removed from the code-base because of a [dependency on Microsoft ATL](https://github.com/cocos2d/cocos2d-x/issues/8561). You can see it here: https://github.com/cocos2d/cocos2d-x/pull/8743/files#diff-578e2caf44a8dbea13c56a75517b9e5d45d7157f37776c6357d62ae8fde07e05

**Comment by rh101** [comment]
I'm going to test out re-adding the code that was removed, but would you the dependency on ATL be an issue for ADXE?

**Comment by halx99** [comment]
I wan't to know, does the implemtation webview browser kernel is `Internet Explorer`, since `Microsoft` mark `Internet Explorer` as deprecated, and removed in windows 11, we shouldn't use it anymore.

**Comment by rh101** [comment]
I'm not sure, but I'll find out.  Hopefully it's using chromium or Microsoft Edge WebView2.

**Comment by halx99** [comment]
Here is the edge webview2 guide: https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/win32

**Comment by rh101** [comment]
By the look of things, the old cocos2d-x Win32 WebView implementation in UIWebViewImpl-win32.cpp is based on Internet Explorer (using the `DWebBrowserEvents2` interface), so we definitely cannot use that.

I'll see what I can do with updating it to Edge webview2, but this isn't high up on my priority list at the moment, so it may be a while before I get to it.

**Comment by rh101** [comment]
I've got a reasonable implementation working, and it no longer requires Microsoft ATL.  It does require the Microsoft.Web.WebView2 NuGet package to be installed during the CMake process, and all paths set up to the headers and libraries.  The issue with that is Microsoft hasn't added certain features for NuGet in C++ vcxproj files, so the work around is to add this:

```
    find_program(NUGET_EXE NAMES nuget)
    if(NOT NUGET_EXE)
        message("NUGET.EXE not found.")
        message(FATAL_ERROR "Please install this executable, and run CMake again.")
    endif()

    exec_program(${NUGET_EXE}
        ARGS install "Microsoft.Web.WebView2" -Version 1.0.992.28 -ExcludeVersion -OutputDirectory ${CMAKE_BINARY_DIR}/packages)
    target_link_libraries(${ADXE_CORE_LIB} ${CMAKE_BINARY_DIR}/packages/Microsoft.Web.WebView2/build/native/Microsoft.Web.WebView2.targets)  
```

The `nuget.exe` file has to be downloaded from [https://www.nuget.org/downloads](https://www.nuget.org/downloads), put in a folder, and add that folder to the environment path.  I'm not sure if there's a way to automate this via CMake, or if the licensing allows for the NuGet.exe to be added to ADXE, so it may have to be a manual step that the developer needs to do.  Microsoft doesn't provide that nuget.exe CLI as part of any other distribution, so this is the only way to get it.

If you know of a better way to automate the download of NuGet.exe, specifically from this path, `https://dist.nuget.org/win-x86-commandline/latest/nuget.exe`, and it go into the generated build folder, then we won't need to add it to the environment path, since we can just pass the correct path to the cmake `exec_program`.

I'll create a PR sometime in the next week with the WebView2 changes.

**Comment by halx99** [comment]
What about use setup.py download it to tools/nuget/?

**Comment by rh101** [comment]
That should work, as long as the downloaded nuget.exe isn't directly in the environment path, just in case the developer uses a different version that machine. 

So, for example, if we download it to `tools/nuget/nuget.exe` , then we can refer to it by that full path. Is that ok? It would mean we always use the one we downloaded, and not any other version that may exist on the PC.

**Comment by rh101** [comment]
It turns out NuGet is under the MIT license, as detailed [here](https://docs.microsoft.com/en-us/nuget/resources/nuget-faq#what-is-the-license-for-nuget-exe-), and redistribution is allowed, so can be included in the ADXE repo if that's a better option.  The only issue with that is keeping it up-to-date.

**Comment by wzhengsen** [comment]
I have implemented webview on windows and linux in my own branch with cef implementation.
I implemented videoplayer using vlc.
But they both have significant drawbacks.
1. they are both too heavyweight.
2. My code is not very well written.

If you are interested, you can go to: https://github.com/wzhengsen/StarryX/tree/Develop/cocos/ui

**Comment by rh101** [comment]
>     1. they are both too heavyweight.

What do you mean by that? Is there something wrong with CEF?

**Comment by wzhengsen** [comment]
The dynamic library of cef is too big, about 100M

**Comment by rh101** [comment]
I didn't know that, and you're right, it is excessive.

**Comment by rh101** [comment]
@halx99 Would there be any issue in adding [WinRT/C++](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt) headers? The WinRT/C++ require C++17 support, which ADXE already has, and it simplifies access to the Windows COM interfaces.

**Comment by rh101** [comment]
Added initial support for Windows WebView using WebView2 Edge chromium in #514 

It works fine, but cookies support isn't implemented yet.  The class structure is based on the original implementation that was removed from Cocos2d-x due to ATL, but the actual implementation now is based on the [https://github.com/webview/webview](https://github.com/webview/webview) project.

**Comment by halx99** [comment]
> @halx99 Would there be any issue in using [WinRT/C++](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt) headers? WinRT/C++ requires C++17 support, which ADXE already has, and it simplifies access to the Windows COM interfaces.
> 
> If not, the fallback is to just use `QueryInterface`, which isn't too bad.

No issue.

**Comment by halx99** [comment]
But, QueryInterface is better

**Comment by rh101** [comment]
QueryInterface worked out just fine, so unless there is complex COM code to write, we won't need WinRT/C++ at the moment.

**Comment by rh101** [comment]
@wzhengsen 
Unfortunately, there are a few issues with that.  Firstly, I don't use Linux, so I can't do much for that platform, and for Mac, I don't build for that platform (only for iOS), so allocating resources to work on an implementation may take quite a while.

Perhaps using the CEF implementation that you've already created for the time being on Linux is better than nothing.  Does it work on Mac too?

**Comment by rh101** [comment]
Yes the [https://github.com/webview/webview](https://github.com/webview/webview) implementation would work fine, just needs someone to port the code over and adapt it to the ADXE UIWebView.  If and when I have some time, I'll attempt the Mac version first, and if that works, I'll see what I can do about installing Linux and sorting that one out too, but again, I can't promise when I'll get around to it.
