### ISSUE TITLE
createWithSpriteFrameName release mode crash issue

### ISSUE THREAD

**Issue by DelinWorks** [adxeproject/adxe#512]
- adxe version: adxe-1.0.0b2
- devices test on: Windows 10 x64 Machine
- developing environments
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133

calling `Sprite::createWithSpriteFrameName("image.png")` will return nullptr only when project is set to Release mode

I have traced this error and tried to solve it but to no avail, it works fine in debug mode but release mode it does not

Steps to repreduce:

1. create a new adxe cpp project
2. just go to helloworld.cpp and addSpriteFrames from a texture atlas made by texturePacker And try to load a spriteFrame by name into a sprite object
3. put project in release mode
4. run!... crash will happen cuz you tried to modify a nullptr object

**Comment by DelinWorks** [comment]
I have followed this article to enable debugging in release mode: https://social.msdn.microsoft.com/Forums/en-US/749ff016-ea1b-45fc-b911-b0613d391d1b/vs-c-2008-release-mode-debug-?forum=vsdebug

I have set up some breakpoints on the function and it doesn't seem to be called
I click step in and that's what I get

![image](https://user-images.githubusercontent.com/45469625/135732375-a9777e6f-ce2c-4c2d-b3bc-30a1ab3859b9.png)
![image](https://user-images.githubusercontent.com/45469625/135732383-ec2b939f-425c-4782-9929-2c6fa31a730f.png)
![image](https://user-images.githubusercontent.com/45469625/135732392-1af3bfc7-297e-437c-aa12-4eb95d874348.png)
![image](https://user-images.githubusercontent.com/45469625/135732457-3a2eca86-bf27-4460-93b1-6f95b97feebc.png)

**Comment by halx99** [comment]
Thanks, will take a look later

**Comment by rh101** [comment]
> Steps to repreduce:
> 
>     1. create a new adxe cpp project
> 
>     2. just go to helloworld.cpp and try to load a spriteFrame by name into a sprite object
> 
>     3. put project in release mode
> 
>     4. run!... crash will happen cuz you tried to modify a nullptr object

Those list of steps aren't complete.  `Sprite::getSpriteFrame*` methods are for sprites that exist in sprite sheets, so should there be another step in there to add a sprite sheet with the sprite frames on it?

What I mean is, did you load the sprite sheet first using one of the available methods, such as  `SpriteFrameCache::getInstance()->addSpriteFramesWithFile()`?

I tested it myself now, both debug and release, and the only way it crashes is if the sprite sheet is not loaded prior to trying to create sprite frames from it.

**Comment by DelinWorks** [comment]
yes i did load it, i loaded it on init and it works fine in debug but not on release

**Comment by DelinWorks** [comment]
Sorry it turns out the plist file that texturePacker created was corrupted! I looked into the plist and there were missing stuff but when I put them back it works, not sure why it works in debug mode anyways
