### ISSUE TITLE
Strange issue with GLViewImpl::createWithRect

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#513]
- adxe version: current branch
- devices test on: Windows 10 x64 build
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 
Steps to Reproduce:

1. Build cpp-tests project (x64)
2. Run it, window will open up at 960x640 resolution. Close window.
3. Change `static Size resourceSize(960, 640);` in AppDelegate.cpp to `static Size resourceSize(1920, 1080);`
4. Build and run.  Window is still at 960x640, when it should be 1920x1080.

I cannot change the window size at all, and I'm not sure why this is happening.  Is this an issue anyone else is experiencing? If not, then something in my Windows environment is causing this problem.

Note: This issue does not exist in Cocos2d-x v4. It's something specific to ADXE.

**Comment by rh101** [comment]
Nevermind, I just found this in BaseTest.cpp:

```
void TestList::runThisTest()
{
    _cellTouchEnabled = true;

    /* Restore default window and design size
    * Note: We should change frame and design size before your new scene create
    * otherwise, the layout will incorrect
    */
    
    GLViewImpl* glview = (GLViewImpl*) Director::getInstance()->getOpenGLView();
 #if defined(CC_PLATFORM_PC)
    Size resourceSize(960, 640);
    glview->setWindowed(resourceSize.width, resourceSize.height);
 #endif

```

**Comment by halx99** [comment]
Correct
