### ISSUE TITLE
An assertion error that can be caused when using ImGui::InputTextWithHint.

### ISSUE THREAD

**Issue by wzhengsen** [adxeproject/adxe#515]
- adxe version:latest
- devices test on:Windows 10
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 
Steps to Reproduce:
![Record](https://user-images.githubusercontent.com/30433761/136075044-f9ee182f-05c6-40b5-a8cd-c319ab76f99c.gif)

**Comment by halx99** [comment]
I have test the official imgui docking demo `example_win32_directx9`, also have this issue, so should be imgui issue.
Can you post it to imgui project: https://github.com/ocornut/imgui

**Comment by halx99** [comment]
So, from author said, you can't use empty id for label, please use `#xxx` instead
