### ISSUE TITLE
Error to build for android with adxe script

### ISSUE THREAD

**Issue by Joilnen** [adxeproject/adxe#529]
- adxe version: commit af19d52d0ef811c2ed3aaf5877610cbc59b9335d

 - NDK version: r21e
 - see the log.txt file
[log.txt](https://github.com/adxeproject/adxe/files/7430286/log.txt)

**Comment by Joilnen** [comment]
Worked, do you know how could I compile in a verbose mode, the ndk part ? Is there some way using adxe script ?

**Comment by halx99** [comment]
I don't know yet.
