### ISSUE TITLE
Use std::string_view instead const std::string& since we update codebase to c++17

### ISSUE THREAD

**Issue by halx99** [adxeproject/adxe#543]

**Comment by wzhengsen** [comment]
Now that the c++ standard has been upgraded to c++17 is there any consideration of using the <filesystem> standard library to implement FileUtils?
This would greatly reduce code variability across platforms.

**Comment by aismann** [comment]
Some more hints where you can replace pre-C++17 string parameter with std::string_view:
https://riptutorial.com/cplusplus/example/6571/using-the-std--string-view-class
![grafik](https://user-images.githubusercontent.com/8652787/144009556-bab7f1c5-9f91-4b42-b74b-4ed3551c9edc.png)

**Comment by halx99** [comment]
> Now that the c++ standard has been upgraded to c++17 is there any consideration of using the standard library to implement FileUtils? This would greatly reduce code variability across platforms.

I'm not sure does it worth to replace exists FileUtils implementation with c++17 filesystem APIs

**Comment by halx99** [comment]
> Some more hints where you can replace pre-C++17 string parameter with std::string_view: https://riptutorial.com/cplusplus/example/6571/using-the-std--string-view-class ![grafik](https://user-images.githubusercontent.com/8652787/144009556-bab7f1c5-9f91-4b42-b74b-4ed3551c9edc.png)

Good point

**Comment by aismann** [comment]
A search construct can find all this "parameter constructs" to help to to replace it with 'string_view'

**Comment by halx99** [comment]
That's a little crazzy, but may be workable with regex search

**Comment by halx99** [comment]
@aismann  Do you have interesting to post a PR work for this?

**Comment by halx99** [comment]
Some hints:
- Should skip all thirdparty
- Should skip some extensions: fairygui, DragonBones, spine
- Does the return type `const std::string&` also need replace with `std::string_view`?

**Comment by aismann** [comment]
> @aismann Do you have interesting to post a PR work for this?

At the moment I have to work on real world stuff.
Maybe 2022.

**Comment by aismann** [comment]
Are there more examples how you update codebase to std::string_view?
- const std::string&  
- see examples above

**Comment by aismann** [comment]
Info:  
Changed:
virtual void setString(std::string_view label) = 0;

Cannot change:
virtual const std::string& getString() const = 0;

**Comment by halx99** [comment]
Maybe `virtual const std::string& getString() const = 0;` can change to `virtual std::string_view getString() const = 0;`

**Comment by aismann** [comment]
> Maybe `virtual const std::string& getString() const = 0;` can change to `virtual std::string_view getString() const = 0;`

It will also change some inherited method on extensions: fairygui, DragonBones, spine.

**Comment by aismann** [comment]
> > Maybe `virtual const std::string& getString() const = 0;` can change to `virtual std::string_view getString() const = 0;`
> 
> It will also change some inherited method on extensions: fairygui, DragonBones, spine.

But it is a peformance improvement.
@halx99  want you try a PR?

**Comment by halx99** [comment]
> > > Maybe `virtual const std::string& getString() const = 0;` can change to `virtual std::string_view getString() const = 0;`
> > 
> > 
> > It will also change some inherited method on extensions: fairygui, DragonBones, spine.
> 
> But it is a peformance improvement. @halx99 want you try a PR?

Should be done by this PR: https://github.com/adxeproject/adxe/pull/560, Huge changes, if somebody interested in it, please help us  review & test it

**Comment by rh101** [comment]
@halx99 I'm running into many issues converting a relatively large project to use the string_view changes.  Besides the large number of compilation issues (which is expected), and the fact that doing this means completely breaking any form of Cocos2d-x compatibility, there is the possibility of more serious, and hidden, problems.

Any parts of the code that use `std::string::c_str()` cannot be simply changed over to use `std::string_view::data()`, since it does not guarantee that the data returned is null terminated.  The safe way would involve a cast the `std::string_view` to to `std::string` first, then calling `c_str()` on the result.

Took me quite a while to get the compilation issues fixed, and now I'm facing a memory leak somewhere that is just chewing up large amounts of memory and freezing Visual Studio. so I'm trying to dig into the cause of that.

**Comment by halx99** [comment]
- Guarantee data with null-terminated c styled string:
  - Construct with literal strings
  - Construct with `std::string`

- Not Guarantee with null-terminated
  - Construct with default constructor `std::string_view{}`
  - Construct with other blob buffer without null-terminated character, such as `std::vector<char>`

**Comment by rh101** [comment]
Would something like this cause a problem:
```
std::string_view UserDefault::getStringForKey(const char* pKey)
{
    return getStringForKey(pKey, "");
}

std::string_view UserDefault::getStringForKey(const char* pKey, std::string_view defaultValue)
{
    auto pValue = getValueForKey(pKey);
    if (pValue)
        return *pValue;

    return defaultValue;
}
```

The `return getStringForKey(pKey, "");` creates a temporary value for defaultValue on the stack.  If a value does not exist in the store, then it will return the std::string_view defaultValue, which is a memory address pointing to a temporary value.  Would the return value still be valid given that it's pointing to a stack that already been unwound (if my assumption on how it works is correct)?

**Comment by halx99** [comment]
It's no problem when the string_view construct with `""`, it's a permanent memory, that why I define a safe `empty_sv` at https://github.com/adxeproject/adxe/blob/ahead/cocos/base/hlookup.h#L62

**Comment by rh101** [comment]
All good, I understand.

I've managed to fix all remaining issues in my project, so now it's working with the string_view changes, and it all seems fine at the moment.

**Comment by aismann** [comment]
When will this big PR available?

**Comment by halx99** [comment]
Currently, It's available to build & test, you can simply fetch & checkout to branch `ahead` to test it

**Comment by aismann** [comment]
> Currently, It's available to build & test, you can simply fetch & checkout to branch `ahead` to test it

My fork has only the dev branch (default) after fetch, no ahead there.
How can I fork ?

**Comment by rh101** [comment]
> My fork has only the dev branch (default) after fetch, no ahead there. How can I fork ?

Follow the instructions here:
[https://stackoverflow.com/questions/4410091/github-import-upstream-branch-into-fork](https://stackoverflow.com/questions/4410091/github-import-upstream-branch-into-fork)

**Comment by halx99** [comment]
The big PR will merge to dev first, and the default branch `release` instead `dev` for stable and compatible reason

**Comment by aismann** [comment]
with the latest adxe (dev from today)
Works on VS IDE!
Get error if it run directly:
![image](https://user-images.githubusercontent.com/8652787/147809230-ae39af73-a5f2-428e-8a97-671b8f3a45c4.png)

**Comment by halx99** [comment]
will check it later

**Comment by halx99** [comment]
> with the latest adxe (dev from today) Works on VS IDE! Resources on IDE from: adxe\tests\cpp-tests\Resources !!! Get error if it run directly: ![image](https://user-images.githubusercontent.com/8652787/147809230-ae39af73-a5f2-428e-8a97-671b8f3a45c4.png)

Aha, you needs use run.bat

**Comment by halx99** [comment]
The working directory needs set to Resources

**Comment by aismann** [comment]
> Here a first check and counting: ![grafik](https://user-images.githubusercontent.com/8652787/144017615-93545002-e2c0-4a15-8c52-dec2138a1077.png)
> 
> Starting with "templates' and 'tests' is a good first step.

I belive it is done (Issue can be closed):
![grafik](https://user-images.githubusercontent.com/8652787/152940098-c56a8213-786e-417a-abd4-77462ff1bff5.png)
