### ISSUE TITLE
yasio crashing on cpptest (autotest) on Windows 

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#546]
- adxe version: latest
- devices test on: windows

   - VS/msvctools version: Visual Studio 2022
   - cmake version: 
Steps to Reproduce:
Run the autotest on cpptest (windows 

[TestController]  Begin traverse TestList:18:Network Test
[TestController]    Begin traverse TestSuite:1:HttpClientTest
[TestController]      Run test:HttpClientTest.
[yasio][1638417778515][global] the yasio-3.39.0 is initialized, the size of per transport is 65816 when object_pool enabled.

[yasio][1638417778515][global] sizeof(io_event)=48

[TestController]      Run test:HttpClientClearRequestsTest.
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\NapiNSP.dll'. 
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\pnrpnsp.dll'. 
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wshbth.dll'. 
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\nlaapi.dll'. 
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winrnr.dll'. 
[yasio]xxsocket::getipsv: flags=3
The thread 0x2e5c has exited with code 0 (0x0).
[TestController]    Begin traverse TestSuite:2:DownloaderTest
[TestController]      Run test:DownloaderTest.
[TestController]      Run test:DownloaderMultiTask.
The thread 0x22e0 has exited with code 0 (0x0).
The thread 0x3398 has exited with code 0 (0x0).
The thread 0x53ac has exited with code 0 (0x0).
The thread 0x3854 has exited with code 0 (0x0).
The thread 0x2e64 has exited with code 0 (0x0).
The thread 0x4ae4 has exited with code 0 (0x0).
Exception thrown at 0x7A72513E (atioglxx.dll) in cpp-tests.exe: 0xC0000005: Access violation reading location 0x00000700.

**Comment by aismann** [comment]
Got the same error in debug mode also:
[TestController]      Run test:HttpClientClearRequestsTest.
HttpClient::destroyInstance begin
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\NapiNSP.dll'. 
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\pnrpnsp.dll'. 
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wshbth.dll'. 
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\nlaapi.dll'. 
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\IPHLPAPI.DLL'. 
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dnsapi.dll'. 
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\nsi.dll'. 
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winrnr.dll'. 
[yasio]xxsocket::traverse_local_address: localhost=DESKTOP-2L1C6CH
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rasadhlp.dll'. 
'cpp-tests.exe' (Win32): Loaded 'C:\Windows\SysWOW64\FWPUCLNT.DLL'. 
[yasio]xxsocket::getipsv: flags=3
The thread 0x1238 has exited with code 0 (0x0).
HttpClient destructor
HttpClient::destroyInstance() finished!
HttpClient singleton is nullptr
[TestController]    Begin traverse TestSuite:2:DownloaderTest
[TestController]      Run test:DownloaderTest.
Construct Downloader 14C64DE8
Construct DownloaderCURL::Impl 11F917BC
Construct DownloaderCURL 14C04BB8
[TestController]      Run test:DownloaderMultiTask.
Construct Downloader 14C65148
Construct DownloaderCURL::Impl 0AE02ABC
Construct DownloaderCURL 14C057F8
Destruct Downloader 14C64DE8
Destruct DownloaderCURL 14C04BB8
Destruct DownloaderCURL::Impl 11F917BC
downloader task create: 0_cocos2dx_landscape.png
Construct DownloadTaskCURL 1471DA18
DownloaderCURL: createTask: Id(0)
++++DownloaderCURL::Impl::_threadProc begin 0AE02ABC
downloader task create: 1_cocos2dx_landscape.png
Construct DownloadTaskCURL 1471ED00
DownloaderCURL: createTask: Id(1)
downloader task create: 2_cocos2dx_landscape.png
Construct DownloadTaskCURL 1471E2B0
DownloaderCURL: createTask: Id(2)
downloader task create: 3_cocos2dx_landscape.png
Construct DownloadTaskCURL 1471DBD0
    _threadProc task create curl handle:14B7F030
    _threadProc task create curl handle:14ACF628
    _threadProc task create curl handle:14B03018
DownloaderCURL: createTask: Id(3)
downloader task create: 4_cocos2dx_landscape.png
Construct DownloadTaskCURL 1471DD88
DownloaderCURL: createTask: Id(4)
downloader task create: 5_cocos2dx_landscape.png
Construct DownloadTaskCURL 1471DF40
DownloaderCURL: createTask: Id(5)
downloader task create: 6_cocos2dx_landscape.png
Construct DownloadTaskCURL 1471E0F8
DownloaderCURL: createTask: Id(6)
    _threadProc task create curl handle:14B0E068
    _threadProc task create curl handle:14A90BE8
downloader task create: 7_cocos2dx_landscape.png
    _threadProc task create curl handle:14A91A18
Construct DownloadTaskCURL 1471E468
    _threadProc task create curl handle:14C1E040
DownloaderCURL: createTask: Id(7)
downloader task create: 8_cocos2dx_landscape.png
Construct DownloadTaskCURL 1471E620
DownloaderCURL: createTask: Id(8)
downloader task create: 9_cocos2dx_landscape.png
Construct DownloadTaskCURL 1471E7D8
DownloaderCURL: createTask: Id(9)
downloader task create: 10_cocos2dx_landscape.png
Construct DownloadTaskCURL 11BB2AC0
DownloaderCURL: createTask: Id(10)
downloader task create: 11_cocos2dx_landscape.png
    _threadProc task create curl handle:14B72028
Construct DownloadTaskCURL 11BB12B0
    _threadProc task create curl handle:14B72E58
    _threadProc task create curl handle:14B73C88
    _threadProc task create curl handle:14B74AB8
DownloaderCURL: createTask: Id(11)
downloader task create: 12_cocos2dx_landscape.png
Construct DownloadTaskCURL 11BB1D00
DownloaderCURL: createTask: Id(12)
downloader task create: 13_cocos2dx_landscape.png
Construct DownloadTaskCURL 11BB2070
DownloaderCURL: createTask: Id(13)
downloader task create: 14_cocos2dx_landscape.png
Construct DownloadTaskCURL 11BB2228
DownloaderCURL: createTask: Id(14)
downloader task create: 15_cocos2dx_landscape.png
Construct DownloadTaskCURL 11BB23E0
    _threadProc task create curl handle:14B000A0
    _threadProc task create curl handle:14C13070
    _threadProc task create curl handle:14B06D58
    _threadProc task create curl handle:14B05ED0
DownloaderCURL: createTask: Id(15)
downloader task create: 16_cocos2dx_landscape.png
Construct DownloadTaskCURL 11BB2598
DownloaderCURL: createTask: Id(16)
downloader task create: 17_cocos2dx_landscape.png
Construct DownloadTaskCURL 0B8C2068
DownloaderCURL: createTask: Id(17)
downloader task create: 18_cocos2dx_landscape.png
Construct DownloadTaskCURL 0B8C2748
DownloaderCURL: createTask: Id(18)
downloader task create: 19_cocos2dx_landscape.png
Construct DownloadTaskCURL 0BCFB248
DownloaderCURL: createTask: Id(19)
    _threadProc task create curl handle:14B0A778
downloader task create: 20_cocos2dx_landscape.png
    _threadProc task create curl handle:14B07BE0
    _threadProc task create curl handle:14B098F0
Construct DownloadTaskCURL 0AD5D468
    _threadProc task create curl handle:14B05048
    _threadProc task create curl handle:14B08A68
DownloaderCURL: createTask: Id(20)
downloader task create: 21_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD1BA0
DownloaderCURL: createTask: Id(21)
downloader task create: 22_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD1150
DownloaderCURL: createTask: Id(22)
downloader task create: 23_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD1D58
DownloaderCURL: createTask: Id(23)
downloader task create: 24_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD0F98
DownloaderCURL: createTask: Id(24)
    _threadProc task create curl handle:14CEF028
    _threadProc task create curl handle:14CF38D0
    _threadProc task create curl handle:14CF0D38
    _threadProc task create curl handle:14CF55E0
downloader task create: 25_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD1308
    _threadProc task create curl handle:14CF1BC0
DownloaderCURL: createTask: Id(25)
downloader task create: 26_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD1678
DownloaderCURL: createTask: Id(26)
downloader task create: 27_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD1F10
DownloaderCURL: createTask: Id(27)
downloader task create: 28_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD0DE0
DownloaderCURL: createTask: Id(28)
downloader task create: 29_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD14C0
DownloaderCURL: createTask: Id(29)
downloader task create: 30_cocos2dx_landscape.png
    _threadProc task create curl handle:14CF6468
Construct DownloadTaskCURL 14CD19E8
    _threadProc task create curl handle:14CF4758
    _threadProc task create curl handle:14CF2A48
    _threadProc task create curl handle:14CEFEB0
    _threadProc task create curl handle:14CFBB98
DownloaderCURL: createTask: Id(30)
downloader task create: 31_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD20C8
DownloaderCURL: createTask: Id(31)
downloader task create: 32_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD2280
DownloaderCURL: createTask: Id(32)
downloader task create: 33_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD2438
DownloaderCURL: createTask: Id(33)
downloader task create: 34_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD25F0
DownloaderCURL: createTask: Id(34)
downloader task create: 35_cocos2dx_landscape.png
    _threadProc task create curl handle:14CFAD10
Construct DownloadTaskCURL 14CD1830
    _threadProc task create curl handle:14CFD8A8
    _threadProc task create curl handle:14CFCA20
    _threadProc task create curl handle:14CF9000
    _threadProc task create curl handle:14CF8178
DownloaderCURL: createTask: Id(35)
downloader task create: 36_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD27A8
DownloaderCURL: createTask: Id(36)
downloader task create: 37_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD2960
DownloaderCURL: createTask: Id(37)
downloader task create: 38_cocos2dx_landscape.png
Construct DownloadTaskCURL 14CD2B18
DownloaderCURL: createTask: Id(38)
downloader task create: 39_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCD610
DownloaderCURL: createTask: Id(39)
downloader task create: 40_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCD0E8
The thread 0x3748 has exited with code 0 (0x0).
The thread 0x818 has exited with code 0 (0x0).
DownloaderCURL: createTask: Id(40)
downloader task create: 41_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCDB38
The thread 0xa1c has exited with code 0 (0x0).
The thread 0x38a0 has exited with code 0 (0x0).
The thread 0x3814 has exited with code 0 (0x0).
The thread 0x4ed8 has exited with code 0 (0x0).
The thread 0x2cf4 has exited with code 0 (0x0).
DownloaderCURL: createTask: Id(41)
The thread 0x4e98 has exited with code 0 (0x0).
downloader task create: 42_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCD2A0
The thread 0x4b1c has exited with code 0 (0x0).
The thread 0x68c has exited with code 0 (0x0).
The thread 0x2660 has exited with code 0 (0x0).
The thread 0x2d8c has exited with code 0 (0x0).
The thread 0x21f4 has exited with code 0 (0x0).
DownloaderCURL: createTask: Id(42)
The thread 0x3e88 has exited with code 0 (0x0).
The thread 0x4720 has exited with code 0 (0x0).
downloader task create: 43_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCD7C8
The thread 0xaac has exited with code 0 (0x0).
The thread 0x385c has exited with code 0 (0x0).
The thread 0x34f0 has exited with code 0 (0x0).
The thread 0x354c has exited with code 0 (0x0).
The thread 0x4ff8 has exited with code 0 (0x0).
DownloaderCURL: createTask: Id(43)
The thread 0x2cb8 has exited with code 0 (0x0).
The thread 0x678 has exited with code 0 (0x0).
The thread 0x3024 has exited with code 0 (0x0).
The thread 0x225c has exited with code 0 (0x0).
The thread 0x3e28 has exited with code 0 (0x0).
The thread 0x4770 has exited with code 0 (0x0).
The thread 0x400c has exited with code 0 (0x0).
The thread 0x26fc has exited with code 0 (0x0).
The thread 0x2a70 has exited with code 0 (0x0).
The thread 0x403c has exited with code 0 (0x0).
The thread 0x35b4 has exited with code 0 (0x0).
The thread 0xc24 has exited with code 0 (0x0).
The thread 0x1b24 has exited with code 0 (0x0).
The thread 0x5060 has exited with code 0 (0x0).
The thread 0x505c has exited with code 0 (0x0).
downloader task create: 44_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCDCF0
DownloaderCURL: createTask: Id(44)
downloader task create: 45_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCEAB0
DownloaderCURL: createTask: Id(45)
downloader task create: 46_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCE588
DownloaderCURL: createTask: Id(46)
downloader task create: 47_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCD458
DownloaderCURL: createTask: Id(47)
downloader task create: 48_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCEE20
DownloaderCURL: createTask: Id(48)
downloader task create: 49_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCD980
DownloaderCURL: createTask: Id(49)
downloader task create: 50_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCDEA8
DownloaderCURL: createTask: Id(50)
downloader task create: 51_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCE060
DownloaderCURL: createTask: Id(51)
downloader task create: 52_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCE218
DownloaderCURL: createTask: Id(52)
downloader task create: 53_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCE3D0
DownloaderCURL: createTask: Id(53)
downloader task create: 54_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCE740
DownloaderCURL: createTask: Id(54)
downloader task create: 55_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCEC68
DownloaderCURL: createTask: Id(55)
downloader task create: 56_cocos2dx_landscape.png
Construct DownloadTaskCURL 14DCE8F8
DownloaderCURL: createTask: Id(56)
downloader task create: 57_cocos2dx_landscape.png
Construct DownloadTaskCURL 14B1B560
DownloaderCURL: createTask: Id(57)
downloader task create: 58_cocos2dx_landscape.png
Construct DownloadTaskCURL 14B1B1F0
DownloaderCURL: createTask: Id(58)
downloader task create: 59_cocos2dx_landscape.png
Construct DownloadTaskCURL 14B1BC40
DownloaderCURL: createTask: Id(59)
downloader task create: 60_cocos2dx_landscape.png
Construct DownloadTaskCURL 14B1B3A8
DownloaderCURL: createTask: Id(60)
downloader task create: 61_cocos2dx_landscape.png
Construct DownloadTaskCURL 14B1B718
DownloaderCURL: createTask: Id(61)
downloader task create: 62_cocos2dx_landscape.png
Construct DownloadTaskCURL 14B1BDF8
DownloaderCURL: createTask: Id(62)
downloader task create: 63_cocos2dx_landscape.png
Construct DownloadTaskCURL 14B1B038
DownloaderCURL: createTask: Id(63)
Destruct Downloader 14C65148
Destruct DownloadTask 14C44CA0
Destruct DownloadTaskCURL 14B1B038
Destruct DownloadTask 14C442A8
Destruct DownloadTaskCURL 14B1BDF8
Destruct DownloadTask 14C435F8
Destruct DownloadTaskCURL 14B1B718
Destruct DownloadTask 14C43FF0
Destruct DownloadTaskCURL 14B1B3A8
Destruct DownloadTask 14C43170
Destruct DownloadTaskCURL 14B1BC40
Destruct DownloadTask 14C43F08
Destruct DownloadTaskCURL 14B1B1F0
Destruct DownloadTask 14C441C0
Destruct DownloadTaskCURL 14B1B560
Destruct DownloadTask 14C43088
Destruct DownloadTaskCURL 14DCE8F8
Destruct DownloadTask 14C43E20
Destruct DownloadTaskCURL 14DCEC68
Destruct DownloadTask 14C449E8
Destruct DownloadTaskCURL 14DCE740
Destruct DownloadTask 14C44818
Destruct DownloadTaskCURL 14DCE3D0
Destruct DownloadTask 14C43510
Destruct DownloadTaskCURL 14DCE218
Destruct DownloadTask 14C44478
Destruct DownloadTaskCURL 14DCE060
Destruct DownloadTask 14C44560
Destruct DownloadTaskCURL 14DCDEA8
Destruct DownloadTask 14C43C50
Destruct DownloadTaskCURL 14DCD980
Destruct DownloadTask 14C42FA0
Destruct DownloadTaskCURL 14DCEE20
Destruct DownloadTask 14C43B68
Destruct DownloadTaskCURL 14DCD458
Destruct DownloadTask 14C44900
Destruct DownloadTaskCURL 14DCE588
Destruct DownloadTask 14C42EB8
Destruct DownloadTaskCURL 14DCEAB0
Destruct DownloadTask 14C43A80
Destruct DownloadTaskCURL 14DCDCF0
Destruct DownloadTask 14C43D38
Destruct DownloadTaskCURL 14DCD7C8
Destruct DownloadTask 14C43998
Destruct DownloadTaskCURL 14DCD2A0
Destruct DownloadTask 14C44648
Destruct DownloadTaskCURL 14DCDB38
Destruct DownloadTask 14C43428
Destruct DownloadTaskCURL 14DCD0E8
Destruct DownloadTask 14C43340
Destruct DownloadTaskCURL 14DCD610
Destruct DownloadTask 14C42DD0
Destruct DownloadTaskCURL 14CD2B18
Destruct DownloadTask 14C44390
Destruct DownloadTaskCURL 14CD2960
Destruct DownloadTask 14C438B0
Destruct DownloadTaskCURL 14CD27A8
Destruct DownloadTask 14C437C8
Destruct DownloadTaskCURL 14CD1830
    _threadProc task clean cur handle :14CF6468 with errCode:35
    _threadProc task clean cur handle :14CF4758 with errCode:35
    _threadProc task clean cur handle :14CF2A48 with errCode:35
    _threadProc task clean cur handle :14CEFEB0 with errCode:35
    _threadProc task clean cur handle :14CFBB98 with errCode:35
    _threadProc task clean cur handle :14CFAD10 with errCode:35
    _threadProc task clean cur handle :14CFD8A8 with errCode:35
    _threadProc task clean cur handle :14CFCA20 with errCode:35
    _threadProc task clean cur handle :14CF9000 with errCode:35
    _threadProc task clean cur handle :14CF8178 with errCode:35
    _threadProc task clean cur handle :14B03018 with errCode:35
    _threadProc task clean cur handle :14A90BE8 with errCode:35
    _threadProc task clean cur handle :14ACF628 with errCode:35
    _threadProc task clean cur handle :14B7F030 with errCode:35
    _threadProc task clean cur handle :14B0E068 with errCode:35
    _threadProc task clean cur handle :14A91A18 with errCode:35
    _threadProc task clean cur handle :14C1E040 with errCode:35
    _threadProc task clean cur handle :14B72028 with errCode:35
    _threadProc task clean cur handle :14B72E58 with errCode:35
    _threadProc task clean cur handle :14B74AB8 with errCode:35
    _threadProc task clean cur handle :14B73C88 with errCode:35
    _threadProc task clean cur handle :14B07BE0 with errCode:35
    _threadProc task clean cur handle :14B05048 with errCode:35
    _threadProc task clean cur handle :14B098F0 with errCode:35
    _threadProc task clean cur handle :14CF38D0 with errCode:35
    _threadProc task clean cur handle :14B08A68 with errCode:35
    _threadProc task clean cur handle :14CF55E0 with errCode:35
    _threadProc task clean cur handle :14CEF028 with errCode:35
    _threadProc task clean cur handle :14B06D58 with errCode:35
    _threadProc task clean cur handle :14B05ED0 with errCode:35
    _threadProc task clean cur handle :14B000A0 with errCode:35
    _threadProc task clean cur handle :14C13070 with errCode:35
    _threadProc task clean cur handle :14B0A778 with errCode:35
    _threadProc task clean cur handle :14CF0D38 with errCode:35
    _threadProc task clean cur handle :14CF1BC0 with errCode:35
----DownloaderCURL::Impl::_threadProc end
The thread 0x4bb8 has exited with code 0 (0x0).
Destruct DownloaderCURL 14C057F8
Destruct DownloaderCURL::Impl 0AE02ABC
Destruct DownloadTask 1471C290
Destruct DownloadTaskCURL 14CD0F98
Destruct DownloadTask 1471B410
Destruct DownloadTaskCURL 14CD1150
Destruct DownloadTask 1471AEA0
Destruct DownloadTaskCURL 11BB23E0
Destruct DownloadTask 1471A930
Destruct DownloadTaskCURL 11BB1D00
Destruct DownloadTask 1471ADB8
Destruct DownloadTaskCURL 11BB12B0
Destruct DownloadTask 1471BD20
Destruct DownloadTaskCURL 11BB2228
Destruct DownloadTask 1471B5E0
Destruct DownloadTaskCURL 11BB2070
Destruct DownloadTask 1471BE08
Destruct DownloadTaskCURL 0AD5D468
Destruct DownloadTask 1471B4F8
Destruct DownloadTaskCURL 14CD1D58
Destruct DownloadTask 1471B328
Destruct DownloadTaskCURL 0BCFB248
Destruct DownloadTask 1471B158
Destruct DownloadTaskCURL 14CD1BA0
Destruct DownloadTask 1471B240
Destruct DownloadTaskCURL 0B8C2068
Destruct DownloadTask 1471B980
Destruct DownloadTaskCURL 0B8C2748
Destruct DownloadTask 1471B070
Destruct DownloadTaskCURL 11BB2598
Destruct DownloadTask 1471ABE8
Destruct DownloadTaskCURL 1471E7D8
Destruct DownloadTask 1471ACD0
Destruct DownloadTaskCURL 11BB2AC0
Destruct DownloadTask 1471AF88
Destruct DownloadTaskCURL 1471E620
Destruct DownloadTask 1471BC38
Destruct DownloadTaskCURL 1471E468
Destruct DownloadTask 1471AA18
Destruct DownloadTaskCURL 1471E0F8
Destruct DownloadTask 1471B6C8
Destruct DownloadTaskCURL 1471DF40
Destruct DownloadTask 1471C1A8
Destruct DownloadTaskCURL 1471DBD0
Destruct DownloadTask 1471BB50
Destruct DownloadTaskCURL 1471DA18
Destruct DownloadTask 1471BFD8
Destruct DownloadTaskCURL 1471ED00
Destruct DownloadTask 1471AB00
Destruct DownloadTaskCURL 1471DD88
Destruct DownloadTask 1471B7B0
Destruct DownloadTaskCURL 1471E2B0
Destruct DownloadTask 14C440D8
Destruct DownloadTaskCURL 14CD25F0
Destruct DownloadTask 1471C800
Destruct DownloadTaskCURL 14CD2438
Destruct DownloadTask 1471C718
Destruct DownloadTaskCURL 14CD2280
Destruct DownloadTask 1471C630
Destruct DownloadTaskCURL 14CD20C8
Destruct DownloadTask 1471BA68
Destruct DownloadTaskCURL 14CD19E8
Destruct DownloadTask 1471C548
Destruct DownloadTaskCURL 14CD14C0
Destruct DownloadTask 1471C460
Destruct DownloadTaskCURL 14CD0DE0
Destruct DownloadTask 1471B898
Destruct DownloadTaskCURL 14CD1F10
Destruct DownloadTask 1471C378
Destruct DownloadTaskCURL 14CD1678
Destruct DownloadTask 1471C0C0
Destruct DownloadTaskCURL 14CD1308
Exception thrown at 0x7A72513E (atioglxx.dll) in cpp-tests.exe: 0xC0000005: Access violation reading location 0x00000700.

**Comment by halx99** [comment]
It seems the exception throw from display driver atioglxx.dll

**Comment by aismann** [comment]
Yes I got it on another test to (sporadic):
I will close this issue (maybe an autotest issue)

[TestController]      Run test:AssetsManager Test3.
Storage path for this test : C:/Users/dreif/AppData/Local/cpp-tests/CppTests/AssetsManagerExTest/scene3
Construct Downloader 13D430F0
Construct DownloaderCURL::Impl 130EE28C
Construct DownloaderCURL 11618DD0
Destruct Downloader 13D41D88
Destruct DownloaderCURL 11618C10
Destruct DownloaderCURL::Impl 130F017C
Destruct Downloader 13D430F0
Destruct DownloaderCURL 11618DD0
Destruct DownloaderCURL::Impl 130EE28C
[TestController]    Begin traverse TestSuite:2:TableViewTest
[TestController]      Run test:TableViewTest.
cocos2d: TextureCache: removing unused texture: D:/______/GitHub/adxe/tests/cpp-tests/Resources/hd/Images/Icon.png
Exception thrown at 0x7A72513E (atioglxx.dll) in cpp-tests.exe: 0xC0000005: Access violation reading location 0x00000700.
