### ISSUE TITLE
https://github.com/slembcke/Chipmunk2D has some fixes (get the latest is a good idea) 

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#551]
https://github.com/slembcke/Chipmunk2D has some fixes (get the latest is a good idea)

**Comment by halx99** [comment]
Can you help update it with post a PR?

**Comment by aismann** [comment]
> Can you help update it with post a PR?

I need only copy the 'latest' chipmunk into the https://github.com/adxeproject/adxe/tree/dev/thirdparty/chipmunk.
And build them.
Right?

**Comment by halx99** [comment]
You just needs copy `include` and `src` from `chipmunk` repo to `thirdparty/chipmunk` and build them
