### ISSUE TITLE
Issue with _searchPathArray

### ISSUE THREAD

**Issue by solan-solan** [adxeproject/adxe#553]
- adxe version:
- devices test on:
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 
Steps to Reproduce:

Could you please explain if it is issue or new project structure. Today I updated adxe to the latest commit, and now it is impossible to load some *c3b object by the following reason:
This is cocos _searchPathArray
![seach_path_cocos](https://user-images.githubusercontent.com/73186496/146691972-d2d85af4-5918-4069-9e1f-8c187fe4698e.png)

And this is adxe _searchPathArray
![seach_path](https://user-images.githubusercontent.com/73186496/146691985-2b0cd320-f6ad-4a8a-977e-7efac50fbcb4.png)

There is no more _Resources_ folder

Thanks

**Comment by aismann** [comment]
maybe it is a 64bit issue?
Can you build the 32bit version and this works?

**Comment by halx99** [comment]
@solan-solan Please specific correct working directory to run MyGame.exe

**Comment by halx99** [comment]
adxe optimize workflow on winodws, use `working directory` and `exe directory` as search path instead add programming `Rsources` folder as search path

**Comment by halx99** [comment]
You can refer to full changelog: https://github.com/adxeproject/adxe/blob/dev/CHANGELOG

**Comment by solan-solan** [comment]
> maybe it is a 64bit issue? Can you build the 32bit version and this works?

Yes, there is no more Resources folder for the 32bit also


> `adxe` optimize workflow on winodws, use `working directory` and `exe directory` as search path instead add programming `Rsources` folder as search path

My 'working directory' has value $(ProjectDir) which is 'F:\g\proj\p\adxe\win64_build19\'. Is it supposed that I need to change it manually? Or I need to add Resources folder to the seach path in the code?
May be it is better to place 'res' folder on the level up? Give me a tip please when you have time.

**Comment by aismann** [comment]
Rename folder  'res' to 'Resources'.  Helps?

**Comment by solan-solan** [comment]
> Rename folder 'res' to 'Resources'. Helps? Compare cpp_tests : Classes, Resources on the same folder

Renaming does not help since, there will be two Resources folder instead of Debug/Resources/res/...
It is good idea to compare with the cpp_tests, I will check it

**Comment by aismann** [comment]
Put all files from Res into Resources. Helps?

**Comment by solan-solan** [comment]
> Put all files from Res into Resources. Helps?

Yes it helps, but this is a little missmatch with cocos resources structure
Thanks a lot in any case

**Comment by aismann** [comment]
Only for my own interest:
Have you a link to the official cocos resources structure

**Comment by solan-solan** [comment]
I just mean generated cocos project templates where 'Resource' folder includes 'res' folder where user resources can be placed. It was convinient to link files in the manner of 'res/...' for me. But of cause it is a deal of habit.

**Comment by halx99** [comment]
please refer to https://github.com/adxeproject/adxe/blob/dev/templates/cpp-template-default/CMakeLists.txt#L166

**Comment by halx99** [comment]
The cmake script will auto set `VS_DEBUGGER_WORKING_DIRECTORY` to correct, if not please clear CMakeCache.txt or regenerate visual studio solution project solustion file again.

**Comment by solan-solan** [comment]
> The cmake script will auto set `VS_DEBUGGER_WORKING_DIRECTORY` to correct, if not please clear CMakeCache.txt or regenerate visual studio solution project solustion file again.

I lost sight of what is needed to update CMakeLists.txt in my projects, it is my issue, sorry for disturbing
