### ISSUE TITLE
[Android] Stack corruption when using CCDownloader

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#559]
- adxe version: https://github.com/adxeproject/adxe/tree/658fa24cb06898fa518018492a3a695297b78174
- devices test on: Devices with Android 8.1 and 11 (all arm64-v8a)
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133 and VS2022
   - cmake version: 3.21
Steps to Reproduce:

1. Create a new project 
2. Unzip the contents of the attached archive to replace HelloWorld.cpp/.h in the created project folder.

When you run it on Windows and iOS, it works fine, and the test file is downloaded correctly.

When it's run on Android, the application crashes:
```
2021-12-27 21:59:43.298 24821-24939/test.example A/libc: stack corruption detected (-fstack-protector)
2021-12-27 21:59:44.683 24821-24939/test.example A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 24939 (GLThread 3939), pid 24821 (test.example)
2021-12-27 21:59:45.301 24821-24939/test.example A/libc: crash_dump helper failed to exec
2021-12-27 21:59:45.302 24821-24939/test.example A/libc: failed to wait for crash_dump helper: No child processes
```

It crashes after `_getHeaderInfoProc()` is called (on the return statement in that method):

```
if (!_getHeaderInfoProc(curlHandle, coTask)) // crashes on the return of this method
{
    // the error info has been set in _getHeaderInfoProc
    break;
}
```

I can't quite figure this issue out, and since I haven't worked on the Android build for over a month, I also can't pin-point when the issue started, because the same code was working correctly the last time I tried the Android build (with an older version of ADXE).  I would appreciate any ideas on why this would be happening.

[HelloWorldScene.zip](https://github.com/adxeproject/adxe/files/7779924/HelloWorldScene.zip)

**Comment by halx99** [comment]
I have tests on my android phone, seems works fine:
![image](https://user-images.githubusercontent.com/6977319/147555720-5cfe9e06-f30b-4edd-8b20-982ea78aa502.png)

**Comment by rh101** [comment]
I don't understand why it's happening at all.  I'll wipe the game engine and the sample project folders and start from scratch by re-cloning from git, and see if that does anything.

**Comment by rh101** [comment]
Ok, so I did the following steps:

1. Clone the latest ADXE from github.
2. Ran setup.py
3. Created project with `adxe new demogame -p com.example.demogame -l cpp -d .`
4. Replaced the HelloWorldScene.cpp/h with the files I attached in the initial post of this issue.  
5. An Android 8.1 device is connected to my PC (Nexus 6P)/
6. When I run it as standalone or debug, it crashes.  In the debug run it displays this in the Android Studio debug window:
![image](https://user-images.githubusercontent.com/8603230/147560384-cb75aaf3-25df-49ac-a623-34000591a29d.png)

This is the development environment:
Windows 10 Pro x64 21H1 19043.1415
Android Studio 2020.3.1 patch 4
JDK 11
Gradle 7.0.4
NDK 19.2.5345600

Is there anything you can see with the above that is different to your setup?

**Comment by halx99** [comment]
I use the branch `ahead` and `HelloCpp` project was created several month ago, I will follow your step to check later

**Comment by halx99** [comment]
By the way ,do you test on Android simulator?

**Comment by rh101** [comment]
> By the way ,do you test on Android simulator?

I just did, and it worked fine. The simulator has the following specs:
![image](https://user-images.githubusercontent.com/8603230/147561782-ecb134fa-758b-415d-8abd-99be941c3290.png)



```
2021-12-28 22:25:35.509 8090-8190/com.example.demogame D/cocos2d-x debug info: Download progress 10000000 out of 10000000
2021-12-28 22:25:35.509 8090-8190/com.example.demogame D/cocos2d-x debug info: DownloadGame task complete!
```

**Comment by halx99** [comment]
so, only crash on your handphone device?

**Comment by rh101** [comment]
> I use the branch `ahead` and `HelloCpp` project was created several month ago, I will follow your step to check later

I appreciate that, thank you.

**Comment by rh101** [comment]
> so, only crash on your handphone device?

Yes, on both Nexus 6P with Android 8.1, and a Google Pixel 4a with Android 12. The same crash on both.

**Comment by halx99** [comment]
I haven't found gradle 7.0.4 on https://services.gradle.org/distributions/, so I will use 6.9 to test

**Comment by halx99** [comment]
My test env is:
Windows 11 Pro x64 21H2 22000.376
Android Studio 2020.3.1 patch 4
JDK 8 Update 281
Gradle 6.9
NDK 19.2.5345600

**Comment by rh101** [comment]
I initially tested with Gradle plugin 4.2.0 and Gradle 6.9, and then upgraded Gradle when Android Studio popped up the notification, but still the same crash.

**Comment by halx99** [comment]
Should be fixed by the latest commit

**Comment by rh101** [comment]
Excellent! Thank you
