### ISSUE TITLE
Only one solution-file (adxe.sln) for Windows 32/64 (debug/release) 

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#562]
Only one solution-file (adxe.sln) for Windows 32/64 (debug/release)  

On the VS (2019/2022) you can select 64/32 Debug/Release 

Reason: 
Easier testing/build of 32bit/64bit executables on  only one adxe source "at the same time".
VS2019/2022 has its own adxe.sln
Maybe some files can be used on all but will be copy only once into the build dir.

**Comment by halx99** [comment]
According to https://gitlab.kitware.com/cmake/cmake/-/issues/18450, Support multiple Architectures in Visual Studio seems impossible

**Comment by aismann** [comment]
What I mean is this one:
![image](https://user-images.githubusercontent.com/8652787/147802679-4cb016fc-774c-411f-954c-b8ce74bf842f.png)

Not build all at the same time but I can select which build will be performed via selection.

**Comment by halx99** [comment]
Yes, The cmake doesn't support multiple architectures visual studio solution file

**Comment by aismann** [comment]
Ok.
