### ISSUE TITLE
[Windows dev workflow] Compile engine once, link prebuilt for project

### ISSUE THREAD

**Issue by halx99** [adxeproject/adxe#564]
## Use steps:

1. Build engine firstly

```bat
cd adxe
cmake -B build_x86 -A Win32
cmake --build build_x86 --config Debug
cmake --build build_x86 --config Release
```

2. create new project and build with engine prebuilt libs

```bat
adxe new -p org.adxe.hellocpp -d D:\dev\projects\ -l cpp --portrait HelloCpp
cd /d D:\dev\projects\HelloCpp
cmake -B build_x86 -A Win32
cmake --build build_x86 --config Debug --target HelloCpp
REM run the HelloCpp.exe
run.bat
```

**Comment by DelinWorks** [comment]
It would be nice if this feature isn't forced, like when you create a project it asks you wither you want prebuilt linking or just normal building, because people like me want to edit the engine anytime they feel like👍

**Comment by aismann** [comment]
> ## Use steps:
> 1. Build engine firstly
> 
> ```batchfile
> cd adxe
> cmake -B build_x86 -A Win32
> cmake --build build_x86 --config Debug
> cmake --build build_x86 --config Release
> ```
> 
> 2. create new project and build with engine prebuilt libs
> 
> ```batchfile
> adxe new -p org.adxe.hellocpp -d D:\dev\projects\ -l cpp --portrait HelloCpp
> cd /d D:\dev\projects\HelloCpp
> cmake -B build_x86 -A Win32 "-DAX_PREBUILT_DIR=build_x86"
> cmake --build build_x86 --config Debug --target HelloCpp
> REM run the HelloCpp.exe
> run.bat
> ```

Will you add this "info"  to the readme or wiki too?

**Comment by halx99** [comment]
May be add a CMakeOptions.md is better, there a other unified options needs docs, see relative issue:
https://github.com/adxeproject/adxe/issues/578

**Comment by DelinWorks** [comment]
Les goo its getting lit in here

**Comment by aismann** [comment]
> Maybe add a CMakeOptions.md is better, there a other unified options needs docs, see relative issue: #578

Good idea.
Only a link to this CMakeOptions.md on readme or wiki is usefull.
What are you mean?

**Comment by aismann** [comment]
Please remove the history (only first entry is important)
Rename `axde `to `axis`

**Comment by aismann** [comment]
@halx99 
Rename axis to axys
