### ISSUE TITLE
CCLabel overflow shrink bug

### ISSUE THREAD

**Issue by DelinWorks** [adxeproject/adxe#565]
There is a bug in cocos2d::Label that can be fixed easily, when making a Label overflow shrink the size of the label after being shrinked from a big text doesn't go back to it's original font size after setting the text to something smaller

In another wording if shrink shrinks the text the label stays small forever even if you put smaller text in it

- adxe version: 1.0.0b2 (Old version but bug still applies)
- devices test on: windows 10

I'm kind of noob at making GitHub pull requests but ill try, if you can help I'll appreciate it :D

Steps to Reproduce:

1. make a new adxe windows project
2. create a new label this way and add it to the scene
```
loadingText = Label::createWithTTF("Validating Resources...", "fonts/SourceCodePro-Regular.ttf", 22, Size(600, 40), TextHAlignment::CENTER);
loadingText->setAnchorPoint(Vec2(.5f, 1));
loadingText->setOverflow(Label::Overflow::SHRINK);
```

Keep manipulating the text when some keys are pressed and you'll notice the bug right off the bat

I fixed it by going to CCLabel.cpp in the engine's source and modifying setString() function and adding restoreFontSize() built-in function when the text changes so that it becomes normal again and for shrink function to modify it however it wants without "locking" it to a small font size

```
void Label::setString(const std::string& text)
{
    if (text.compare(_utf8Text))
    {
        restoreFontSize();

        _utf8Text = text;
        _contentDirty = true;

        std::u32string utf32String;
        if (StringUtils::UTF8ToUTF32(_utf8Text, utf32String))
        {
            _utf32Text  = utf32String;
        }
    }
}
```

**Comment by rh101** [comment]
Isn't `restoreFontSize` an expensive call to make, especially in `setString()`, which may be called quite a lot in certain scenarios, for instance, where a label displays a counter etc.

When the overflow is set to `Overflow::SHRINK`, `shrinkLabelToContentSize` seems to be the section of code that handles everything to shrink the displayed text (I only had a quick look at it).  Have you looked into any alternatives to solving this issue without having to call `restoreFontSize` on every `setString`?
