### ISSUE TITLE
Should it added to adxe readme:    "https://repobeats.axiom.co"  ?

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#572]
Look add
https://repobeats.axiom.co/

**Comment by aismann** [comment]
I tried it but I get only the info from "my fork" (thats not the right one).
I belive the owner of the "adxe" has to add it.

![grafik](https://user-images.githubusercontent.com/8652787/151334840-77cc9f99-5bec-4d21-8081-ecf12f3762f2.png)

**Comment by halx99** [comment]
I just add it: https://github.com/adxeproject/adxe/commit/d47816ba3e765b8a746885702ff6ccb2330dbfb3
