### ISSUE TITLE
Error compiling in linux

### ISSUE THREAD

**Issue by Joilnen** [adxeproject/adxe#576]
I get this compiling in linux 
adxe version: 7f81b65596fc2e09b0ecb07ea8c16adc526c345a

Consolidate compiler generated dependencies of target ImGuiEXT
[ 75%] Building CXX object engine/extensions/ImGuiEXT/CMakeFiles/ImGuiEXT.dir/imgui_impl_adxe.cpp.o
/home/joilnen/adxe_devel/adxe-1.0/extensions/ImGuiEXT/imgui_impl_adxe.cpp: In function ‘bool ImGui_ImplAdxe_Init(bool)’:
/home/joilnen/adxe_devel/adxe-1.0/extensions/ImGuiEXT/imgui_impl_adxe.cpp:682:5: error: ‘g_MouseCursors’ was not declared in this scope; did you mean ‘ImGuiMouseCursor_’?
  682 |     g_MouseCursors[ImGuiMouseCursor_ResizeAll]  = glfwCreateStandardCursor(GLFW_ARROW_CURSOR);
      |     ^~~~~~~~~~~~~~
      |     ImGuiMouseCursor_
make[2]: *** [engine/extensions/ImGuiEXT/CMakeFiles/ImGuiEXT.dir/build.make:90: engine/extensions/ImGuiEXT/CMakeFiles/ImGuiEXT.dir/imgui_impl_adxe.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1974: engine/extensions/ImGuiEXT/CMakeFiles/ImGuiEXT.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by halx99** [comment]
Fixed by the latest commit
