### ISSUE TITLE
Is it safe to convert std::wstring to std::string?

### ISSUE THREAD

**Issue by wzhengsen** [adxeproject/adxe#586]
1. In file UIWebViewImpl-win32.cpp，about line 349 and 356
2.The code:
```c++
std::wstring ws(uri);
const auto result = std::string(ws.begin(), ws.end());
```
3.The warning:
```
xstring(2588,23): warning C4244: “参数”: 从“wchar_t”转换到“const _Elem”，可能丢失数据
```

**Comment by halx99** [comment]
If all chars is ansi, it should be safe

**Comment by wzhengsen** [comment]
In general, does uri have to be ansi encoded?

**Comment by DelinWorks** [comment]
Yes a uri is ansi encoded as far as im aware

![image](https://user-images.githubusercontent.com/45469625/153862513-d212a6cc-3f75-4100-917d-a81e5286bf3c.png)

![image](https://user-images.githubusercontent.com/45469625/153862796-02c621da-dea9-4a11-b90c-25e807c345c6.png)

if you issue chcp 437 (which is ANSI) or 1254 on windows, and echo a string containing a uri formatted data then you will not see any "?" marks

**Comment by wzhengsen** [comment]
@DelinWorks 
Yes, you are right.
I originally thought the Chinese domain name would be used directly, but later I verified that its converted to punycode.
For example: ```新华网.cn -> xn--xkrr14bows.cn```

**Comment by halx99** [comment]
The `punycode` indicate to same website, so this actually is not a issue? correct?

**Comment by wzhengsen** [comment]
Yes, I can use https://新华网.cn to open and jump to the website correctly.
