### ISSUE TITLE
Use Solution Dir for easier project migration from one pc to another

### ISSUE THREAD

**Issue by DelinWorks** [adxeproject/adxe#596]
Use $(SolutionDir) including rather than absolute path to make project migration easier

![image](https://user-images.githubusercontent.com/45469625/155585622-18f98cae-52de-4505-bed2-9a9f1bd06aef.png)

This is the default way of including files and dependencies which uses absolute path to disk, what If I were to develop in another pc?
I'd have to check if I have the same path to that disk or change paths manually or recreate the project and link everything up

Example of wanted solution
![image](https://user-images.githubusercontent.com/45469625/155586142-b0ff28f9-c980-4239-87b2-51129d0bf7fc.png)

**Comment by rh101** [comment]
That only applies to the generated project build files, or am I misunderstanding what you mean here?  

The problem isn't just the Visual Studio generated project files, but also everything related to cmake inside your build folder.  The cmake-generated files will have absolute path references, and the only way to fix it is to re-run cmake.  You would have to delete the `[build dir]\CMakeCache.txt` file first, or perhaps even the entire build folder if you copied it across. 

The source code and related files should have hard-coded references to paths, and when you check-out or copy the source code across, you should not be copying the generated build files with it (which would have hard-coded paths).  Running cmake on your project in the new environment will regenerate all the required build files with the correct paths.
