### ISSUE TITLE
{fmt} changes caused some issues

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#597]
- adxe version: latest release branch, https://github.com/adxeproject/adxe/tree/357c570538d44e7b293039b0c61ca749f15707f4
- devices test on: Windows 10
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 
Steps to Reproduce:

After upgrading to the latest version of ADXE, errors just popped up everywhere related to the {fmt} library.  I noticed this change in the `thirdparty/CMakeList.txt`:

Original:
```
# fmt-lib
add_subdirectory(fmt)
target_link_libraries(thirdparty fmt-header-only)
configure_target_outdir(fmt)
```

The above was deleted and replaced by:
```
# header only libs
target_include_directories(thirdparty
    INTERFACE "fmt/include"
    ...
)
```

This caused several issues.  The first is that `fmt-header-only` can no longer be linked with libraries other than the primary app.  For instance, another third party library that also requires fmt would either need to include it's own version of fmt, or have some cmake magic to somehow link it to the existing {fmt} that is supplied by adxe.

The other issue is that `FMT_HEADER_ONLY` is no longer defined, since that was being defined in the `fmt/CMakeLists.txt` file when `fmt-header-only` was being used.

If FMT_HEADER_ONLY is not defined, then it causes problems like this when certain fmt code is used:
```
Error	LNK2001	unresolved external symbol "struct fmt::v8::detail::thousands_sep_result<char> __cdecl fmt::v8::detail::thousands_sep_impl<char>(class fmt::v8::detail::locale_ref)" (??$thousands_sep_impl@D@detail@v8@fmt@@YA?AU?$thousands_sep_result@D@012@Vlocale_ref@012@@Z)
```

Now I noticed a new file named `base/format.h`, which contains this:
```
#ifndef ADXE_FORMAT_H
#define ADXE_FORMAT_H

#ifndef FMT_HEADER_ONLY
#  define FMT_HEADER_ONLY
#endif

#include "fmt/format.h"
...
...
#endif
```

This `format.h` file doesn't seem to be part of the source code in the VS project, so it doesn't show up at all, even when searching for the `FMT_HEADER_ONLY` text.  Also, that `format.h` cannot be included from other external third party libraries, since they don't link with adxe directly.

So, firstly, a question. What was the reason for the change from linking with `fmt-header-only`? Was it causing a problem?  

To fix this issue, and to avoid having to define FMT_HEADER_ONLY before including the different `fmt/****.h` files, I had to add this to my project `CMakeLists.txt`:
```
target_compile_definitions(${APP_NAME} PRIVATE FMT_HEADER_ONLY=1)
```

For any external library that also required `{fmt}`, this seems to work:
```
target_compile_definitions(otherlibrary PRIVATE FMT_HEADER_ONLY=1)
target_include_directories(otherlibrary 
    PRIVATE ${ADXE_ROOT_PATH}/thirdparty/fmt/include
)
```

The alternative is that I include my own version of the `{fmt}`, but then I may end up running into header clashes, since there would be multiple versions of `fmt/format.h` etc, and there doesn't seem to be a way to disable the inclusion of the version that comes with the ADXE code (like with `AX_ENABLE_EXT_FMT` or similar).

I'm happy to just leave it as-is since I've got it working again, but I'm curious as to why this was changed from the `fmt-header-only`.

**Comment by halx99** [comment]
Reverted

**Comment by rh101** [comment]
Oh fair enough, I wasn't expecting you to revert it, but either way, it's all good.  Is there any problem when using `fmt-header-only` that you know of, regarding the original reason for the change?

**Comment by rh101** [comment]
Just as an FYI, you can prevent the fmt library from being built, since we're it as header-only, by changing this:

`add_subdirectory(fmt)`

to this

`add_subdirectory(fmt EXCLUDE_FROM_ALL)`

in `thirdparty/CMakeLists.txt`

I just tested it with EXCLUDE_FROM_ALL, and it didn't generate the lib file, which is correct, since there is no need for it to be created.  I noticed this in the fmt docs [here](https://github.com/fmtlib/fmt/blob/master/doc/usage.rst#usage-with-cmake).

**Comment by halx99** [comment]
> Oh fair enough, I wasn't expecting you to revert it, but either way, it's all good. Is there any problem when using `fmt-header-only` that you know of, regarding the original reason for the change?

The extension fairgygui can't be compile on android with fmtlib: 
https://github.com/adxeproject/adxe/runs/4740896470?check_suite_focus=true

**Comment by rh101** [comment]
That is so strange, and it's an error I've never seen before with fmt.

Have you tried just building it as a static library, not header-only, as in:

```
add_subdirectory(fmt)
target_link_libraries(thirdparty fmt)
```

(and make sure not to remove the FMT_HEADER_ONLY define from `base/format.h`)

**Comment by halx99** [comment]
Actualy, add `base/format.h` sovled the issue finally

**Comment by halx99** [comment]
> That is so strange, and it's an error I've never seen before with fmt.
> 
> Have you tried just building it as a static library, not header-only, as in:
> 
> ```
> add_subdirectory(fmt)
> target_link_libraries(thirdparty fmt)
> ```
> 
> (and make sure not to remove the FMT_HEADER_ONLY define from `base/format.h`)

Not try build static yet

**Comment by rh101** [comment]
Oh that's crazy, it was just a missing include! C++ error messages are often overly complex and misleading.

I'm really glad you sorted it out!
