### ISSUE TITLE
A few compilation errors.

### ISSUE THREAD

**Issue by wzhengsen** [adxeproject/adxe#602]
- adxe version:dev latest
- devices test on:Windows11 PC
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2022 / C++20 standard
   - cmake version: 

1.
![image](https://user-images.githubusercontent.com/30433761/158600739-50eba255-7806-4207-9a51-ac01105ff330.png)
2.
![image](https://user-images.githubusercontent.com/30433761/158602172-fb7e2c66-3834-4045-b94f-7cfb410f6906.png)

**Comment by halx99** [comment]
well, the cpp20 not tests yet

**Comment by aismann** [comment]
Fixed 
with axmol #888
