### ISSUE TITLE
Sometimes protected members are accessed.

### ISSUE THREAD

**Issue by wzhengsen** [adxeproject/adxe#603]
In UIVideoPlayer-win.cpp at line 291 and 469:
```c++
pvd->_vrender = new Sprite();
...
pvd->_vrender->initWithTexture(pvd->_vtexture);
```
You can see that Sprite's constructor and initWithTexture method are qualified by CC_CONSTRUCTOR_ACCESS, and the macro definition of CC_CONSTRUCTOR_ACCESS is as follows:
```c++
#ifndef CC_CONSTRUCTOR_ACCESS
#    ifdef CC_ENABLE_SCRIPT_BINDING
#        define CC_CONSTRUCTOR_ACCESS public
#    else
#        define CC_CONSTRUCTOR_ACCESS protected
#    endif
#endif
```
That is, in some cases, the initWithTexture method is not always public.

A similar situation is found in abundance in fairygui.

**Comment by halx99** [comment]
Simply change `CC_CONSTRUCTOR_ACCESS` to `public` without preprocessor check maybe better

**Comment by halx99** [comment]
Done
