### ISSUE TITLE
When the pugixml is updated, the sv literal may no longer be applicable.

### ISSUE THREAD

**Issue by wzhengsen** [adxeproject/adxe#604]
In TranslationHelper.cpp at line 28:
![image](https://user-images.githubusercontent.com/30433761/158749007-ac9b6245-0853-4804-aeef-4dbf7caba491.png)

**Comment by halx99** [comment]
The `pugixml` used by adxe is from this fork: https://github.com/halx99/pugixml with `string_view` support
