### ISSUE TITLE
Sorry: PyBullet 3.2.4  released this 4 days ago

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#624]
PyBullet 3.2.4 Latest
@[erwincoumans](https://github.com/erwincoumans) erwincoumans released this 4 days ago

**Comment by halx99** [comment]
Well, it update too fast

**Comment by aismann** [comment]
Roadrunner behavior at this moment.

**Comment by halx99** [comment]
Nothing changes for adxe, just version code was change to `3.24`

**Comment by aismann** [comment]
Should we not add an  info on the bullet  version info line at least?

**Comment by halx99** [comment]
Yes, should be done by latest commit
