### ISSUE TITLE
VideoPlayer has bad horizontal quality and stale colors

### ISSUE THREAD

**Issue by DelinWorks** [adxeproject/adxe#627]
VideoPlayer node has a problem with quality (or Microsoft Media Foundation to be specific) 
It seems that with every video you get this interlaced effect which makes the video ugly and also looks stale with a gray tone:

![image](https://user-images.githubusercontent.com/45469625/166119435-7976d561-d82a-461c-89ae-c513d11ab22d.png)

But when viewed from an outside source like VLC it's seen normal and with good quality and has a great tone:

![image](https://user-images.githubusercontent.com/45469625/166119443-3beaeb47-7d5c-4439-b96f-dcf9b35f236d.png)

Don't mind the video I just wanted to have text in it so that the problem is clear.

**Comment by halx99** [comment]
Can you provide your video file?

**Comment by DelinWorks** [comment]
https://user-images.githubusercontent.com/45469625/166128535-bded2642-dbb2-471c-b839-c1eebd8dfe63.mp4

This is some video file I experimented on but rest assured that it happens with every video, so yeah texts or small lines or whatever detail is in a video seems to have squiggly annoying lines.

I think it's because of YUY2 format because it uses half the width sacrificing quality to store data or whatever I haven't read about the algorithm really

**Comment by halx99** [comment]
I have tried the `NV12`, it seems still gray than windows system video player:
<img width="968" alt="image" src="https://user-images.githubusercontent.com/6977319/166142422-031e6b98-d129-4caf-a883-e10f588e0fb9.png">

**Comment by DelinWorks** [comment]
Nice! the horizontal lines to disappear which makes it 70% better, but the gray? don't you think it needs to have shader tweaking or color correction?

**Comment by halx99** [comment]
> Nice! the horizontal lines seem to have been gone which makes it 70% better, but the gray? don't you think it needs to have shader tweaking or color correction?
> 
> Could you tell me how did you switch to `NV12` rather than `YUY2`? I tired to but seems like it's mmf that decides that

Just force set VideoOutputFormat to `MFVideoFormat_NV12` at follow lines:

https://github.com/adxeproject/adxe/blob/dev/core/ui/UIVideoPlayer/MFMediaPlayer.cpp#L1571

**Comment by halx99** [comment]
I checked the Unreal Engine 4.27.2, the video render result have same issue:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/6977319/166175578-162e2983-584f-4508-b03a-c8e50c9f3fa2.png">

**Comment by DelinWorks** [comment]
I think it's because of lighting? the plane that projects the video seems to have a light source like a directional light or something

**Comment by halx99** [comment]
I hide the lighting, then result is:
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/6977319/166176765-81dd1ce1-6aa3-4a6d-9b9a-e6adc29d92d3.png">

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/6977319/166176848-215249f3-9775-47cc-b704-cc9c5f47e5f4.png">

**Comment by DelinWorks** [comment]
> I hide the lighting, then result is: <img alt="image" width="1391" src="https://user-images.githubusercontent.com/6977319/166176765-81dd1ce1-6aa3-4a6d-9b9a-e6adc29d92d3.png">
> 
> <img alt="image" width="1038" src="https://user-images.githubusercontent.com/6977319/166176848-215249f3-9775-47cc-b704-cc9c5f47e5f4.png">

this it's better now! the horizontal lines problem is fixed but we still  have the color correction problem

**Comment by DelinWorks** [comment]
```
std::string_view NV12_FRAG = R"(
#ifdef GL_ES
varying highp vec4 v_fragmentColor;
varying highp vec2 v_texCoord;
#else
varying vec4 v_fragmentColor;
varying vec2 v_texCoord;
#endif

uniform sampler2D u_texture; // Y sample
uniform sampler2D u_texture1; // UV sample

void main()
{
    // refer to: 
    // a. https://gist.github.com/crearo/0d50442145b63c6c288d1c1675909990
    // b. https://github.com/tqk2811/TqkLibrary.Media.VideoPlayer/blob/38a2dce908215045cc27cffb741a6e4b8492c9cd/TqkLibrary.Media.VideoPlayer.OpenGl/Renders/NV12Render.cs#L14
    // c. https://www.cnblogs.com/nanqiang/p/10224867.html
    
    float cy = v_texCoord.y + 0.01625; // why needs adjust?
    vec4 uvColor = texture2D(u_texture1, vec2(v_texCoord.x, cy));
    vec3 yuv = vec3(texture2D(u_texture, v_texCoord).r, uvColor.r - 0.5, uvColor.a - 0.5);

    vec3 rgb = mat3( 1.0,       1.0,       1.0,
                     0,        -0.39465,   2.03211,
                     1.13983,  -0.58060,   0 ) * yuv;

    float contrast = 1.42982;
    float brightness = -0.09206;

    rgb.r = rgb.r * contrast + brightness;
    rgb.g = rgb.g * contrast + brightness;
    rgb.b = rgb.b * contrast + brightness;

    gl_FragColor = v_fragmentColor * vec4(rgb, 1.0);
}
)"sv;
```

I think this color correction result is turning out to be great!
![image](https://user-images.githubusercontent.com/45469625/166297779-38fe4474-ed07-4b6e-8202-44f3ebbfc90c.png)

Left is game right is VLC
What do you think @halx99 ?

**Comment by halx99** [comment]
The text in the left corner lighter than VLC, but yes, it's much better than before

**Comment by DelinWorks** [comment]
Yeah you're right, I'll try to improve it even more
it's just about finding the right values

**Comment by halx99** [comment]
This issue should be fixed by latest commit, please check

**Comment by DelinWorks** [comment]
Good job! it looks nice now.
![image](https://user-images.githubusercontent.com/45469625/167306628-7763ab7a-7e82-4420-8324-7c23c00f60b4.png)

**Comment by DelinWorks** [comment]
Just asking is this bit of code intended? `UIVideoPlayer-win.cpp`

![image](https://user-images.githubusercontent.com/45469625/167319332-ba145fdc-c5c6-4bad-a1cc-9e1dc5e7fc4f.png)

If the format is `YUY2` or `NV12` in any case it will go to the second case which is `NV12` did you mean to put a `break` in there?

**Comment by halx99** [comment]
> @halx99 Just asking is this bit of code intended? `UIVideoPlayer-win.cpp`
> 
> ![image](https://user-images.githubusercontent.com/45469625/167319332-ba145fdc-c5c6-4bad-a1cc-9e1dc5e7fc4f.png)
> 
> If the format is `YUY2` or `NV12` in any case it will go to the second case which is `NV12` did you mean to put a `break` after `YUY2` case?

It means `YUY2` and `NV12` needs register custom shader program.

**Comment by DelinWorks** [comment]
oh for both of them they get their shaders registered! I understand now, that's actually smart.
