### ISSUE TITLE
Qt Creator: New Adxe project open failed cmake ?

### ISSUE THREAD

**Issue by lavara123** [adxeproject/adxe#631]
- adxe version: 1.0
Arch Lİnux =>Qt Creator
- developing environments
   - NDK version: r24-1
   - Qt Creator Version: 7.01
   - cmake version: 3.23.1
Steps to Reproduce:

cmake error (qt):
```
CMake Error at CMakeLists.txt:50 (message):
  Please run setup.py add system env var 'ADXE_ROOT' to specific the engine
  root
```

### EDIT:

if i change the following line in CMakeLists.txt in new project it works
Line: 43
`set(ADXE_ROOT "$ENV{ADXE_ROOT}")`
to
`set(ADXE_ROOT "/home/USER/adxe")`

returns value in console:
`echo $ADXE_ROOT`

**Comment by DelinWorks** [comment]
Did you run `setup.py` in the engines root directory?
$ADXE_ROOT env variable needs to be set and is used widely in cmake and changing every occurrence of `$ENV{ADXE_ROOT}` to `/home/USER/adxe` isn't a viable option.

**Comment by DelinWorks** [comment]
It may be that you've run `setup.py` in `sudo` mode because that will setup the environment variables under root and not your user
And when you use the engine in your `USER` path it doesn't recognize the variables because they're not there

**Comment by lavara123** [comment]
@DelinWorks

Yes I ran it with sudo but it was added to the user's `~/.bashrc` file.

on console
`echo $ADXE_ROOT` returns a good value.

Problem
`$ENV{ADXE_ROOT`}

`ENV` function pulls value blank

**Comment by DelinWorks** [comment]
Does replacing `set(ADXE_ROOT "$ENV{ADXE_ROOT}")` with `set(ADXE_ROOT "ENV{ADXE_ROOT}")` or `set(ADXE_ROOT "${ADXE_ROOT}")` fix the problem?

**Comment by lavara123** [comment]
@DelinWorks 
I found the problem. newly added environment are not visible in cmake but I couldn't find how to solve the problem

**Comment by DelinWorks** [comment]
see, I think the application menu is depending on a custom user, and that user lets say `desktop` doesn't know anything about the environment variables `setup.py` has made.
