### ISSUE TITLE
[Android] Black screen after unlocking device while game app is running

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#635]
- adxe version: Current dev branch
- devices test on: Android 12 devices (Pixel 4a etc).
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2022
   - cmake version: 3.21+
Steps to Reproduce:

1. Run ADXE app on Android device.
2. Once the app is loaded, press the power button to turn off the screen/lock the phone.
3. Unlock the phone, and the app flashes then goes black.

The only way to recover the ADXE application screen is to tap the overview button (the square button down the bottom), switch to another app, then switch back to ADXE app. Or, alternatively, press the Android home button, then go back to your ADXE app.

The issue has to do with the method `resumeIfHasFocus` in Cocos2dxActivity.java:

```
    @Override
    protected void onResume() {
    	Log.d(TAG, "onResume()");
        paused = false;
        super.onResume();
        this.hideVirtualButton();
       	resumeIfHasFocus();
    }
    
    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
    	Log.d(TAG, "onWindowFocusChanged() hasFocus=" + hasFocus);
        super.onWindowFocusChanged(hasFocus);
        
        this.hasFocus = hasFocus;
        resumeIfHasFocus();
    }
    
    private void resumeIfHasFocus() {
        //It is possible for the app to receive the onWindowsFocusChanged(true) event
        //even though it is locked or asleep
        boolean readyToPlay = !isDeviceLocked() && !isDeviceAsleep();

        if(hasFocus && readyToPlay) {
            this.hideVirtualButton();
            Cocos2dxHelper.onResume();
            mGLSurfaceView.onResume();
        }
    }
```

If we comment out the "isDeviceLocked()" check, then everything works, but it's strange logic.  From the comment in the code, it seems that `onWindowFocusChanged(true) can be called even though the device is locked or asleep.  

The issue here is timing, because the device locked status hasn't yet been updated by the time `onWindowFocusChanged` is called.  If you add a thread sleep in `resumeIfHasFocus()`, before calling `isDeviceLocked()`, then everything works. For example:

    private void resumeIfHasFocus() {
        try
        {
            Thread.sleep(500);
        }
        catch(InterruptedException ex)
        {
            Thread.currentThread().interrupt();
        }

        //It is possible for the app to receive the onWindowFocusChanged(true) event
        //even though it is locked or asleep
        boolean readyToPlay = !isDeviceLocked() && !isDeviceAsleep();

        if(hasFocus && readyToPlay) {
            this.hideVirtualButton();
            Cocos2dxHelper.onResume();
            mGLSurfaceView.onResume();
        }
    }

While it does work, the ADXE app recovers, then goes black, then comes back again.  I don't think that is the correct solution.  

If the ADXE application is put into the background, such as the user switching to another application, or the device goes into lock or sleep mode etc, then `onPause()` is *always* called, as per the Google android [documentation](https://developer.android.com/guide/components/activities/activity-lifecycle).  `onWindowFocusChanged(false)` is called after `onPause()`.

Once the app is recovered, `onResume()` is called before `onWindowFocusChanged(true)`, so we can't really resume in `onResume()` unless we're sure the application has focus.

So, my suggestion is this:

    @Override
    protected void onResume() {
        Log.d(TAG, "onResume()");
        paused = false;
        super.onResume();
        if (this.hasFocus) {
            resume();
        }
    }
    
    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        Log.d(TAG, "onWindowFocusChanged() hasFocus=" + hasFocus);
        super.onWindowFocusChanged(hasFocus);
        
        this.hasFocus = hasFocus;
        if (this.hasFocus && !paused) {
            resume();
        }
    }
    
    private void resume() {
        this.hideVirtualButton();
        Cocos2dxHelper.onResume();
        mGLSurfaceView.onResume();
    }

What happens here is that if for some reason `onResume()` is called, but we already have focus, then we resume.  

If `onWindowFocusChanged(true)` is called by the system, but the application is paused (meaning we're in locked/sleep mode), then it will not be resumed.  

The only time it will be resumed is if the app is not paused, and we have focus.  

We no longer need to explicitly check `isDeviceLocked()` or `isDeviceAsleep()`, so there no longer a need for the `resumeIfHasFocus()` method.

This has been tested, and it fixed the issue, without any strange side-effects.

What are your opinions on this? If anyone else can reproduce the original issue, then please try the suggested fix, and see if it has any side-effects for you.

Note, this is an issue with Cocos2d-x as well, so not something specific to ADXE.

**Comment by halx99** [comment]
May be, you can try post a pull-request about this issue for somebody can easy to merge your patch and check the suggested fix.

**Comment by rh101** [comment]
Will do!
