### ISSUE TITLE
Remove the "cocos2dx" HelloWorld.png with an official "adxe" logo version  

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#659]
Remove the "cocos2dx" HelloWorld.png with an official "adxe" logo version  

Steps:
1) First a official adxe logo have to be created.
2)  replace the "cocos2dx" HelloWorld.png with this official "adxe" HelloWorld.png on the whole adxe projects

**Comment by aismann** [comment]
I have used image below on SimpleSnake example, but is not really nice, isnt it?
![image](https://user-images.githubusercontent.com/8652787/174121253-a1ac6d9b-66a3-4f19-a747-7e9bc8b0f3d6.png)

**Comment by DelinWorks** [comment]
You'd have to somehow extract the the white background from the alpha pixels which kinda feels hard not gonna lie

**Comment by aismann** [comment]
That's easy, but it is not really a white background. Usuing the original maybe has a better qualtity?
![image](https://user-images.githubusercontent.com/8652787/174125046-b3f8ee93-4ff9-40e6-ab96-77687d5876b0.png)

**Comment by aismann** [comment]
Replace the white with black its looks uglier:
![image](https://user-images.githubusercontent.com/8652787/174125739-efd3cb3a-dad2-4c39-98e8-d20bfe8cae4c.png)

**Comment by DelinWorks** [comment]
I'm sure you can write a python program that sees if a pixel is closer to white the more transparent it will be

**Comment by aismann** [comment]
A native image with "2 colors" and no interpolation is better

**Comment by aismann** [comment]
> You have to loop over every pixel and see if it's saturated less than 0.5 and set it's transparency the more it's desaturated on a scale of 0 to 0.5, I'm sure that'll work 😀

Sure. But I'm note the owner. Maybe another one is want ;)
@halx99: Can you provide an official logo for using on adxe (not the logo on the github page of adxeproject)?

**Comment by DelinWorks** [comment]
> > You have to loop over every pixel and see if it's saturated less than 0.5 and set it's transparency the more it's desaturated on a scale of 0 to 0.5, I'm sure that'll work 😀
> 
> Sure. But I'm note the owner. Maybe another one is want ;) @halx99: Can you provide an official logo for using on adxe (not the logo on the github page of adxeproject)?

Don't worry I'll do it

**Comment by DelinWorks** [comment]
Use this texture for clear white backgrounds:

![image](https://user-images.githubusercontent.com/45469625/174136545-92e177e9-2a3d-4edd-9555-bbc43b2b63d2.png)

And use this for black backgrounds:

![image](https://user-images.githubusercontent.com/45469625/174136724-acda1f27-0810-45e9-8645-8d6df92ae513.png)

This is the python code tweak on it however you want:
```
from PIL import Image

input_image = Image.open("Untitled.png")
input_image = input_image.convert('RGBA')

pixel_map = input_image.load()
width, height = input_image.size

for i in range(width):
    for j in range(height):
        
        r, g, b, a = input_image.getpixel((i, j))
  
        alpha = int((sum([r,g,b])/3));

        pixel_map[i, j] = (int(r * ((255-alpha) / 255)), int(g * ((255-alpha) / 255)), int(b * ((255-alpha) / 255)), int((255 - alpha) * 2.4))

input_image.save("newLogo.png", format="png")
```

**Comment by halx99** [comment]
> > You have to loop over every pixel and see if it's saturated less than 0.5 and set it's transparency the more it's desaturated on a scale of 0 to 0.5, I'm sure that'll work 😀
> 
> Sure. But I'm note the owner. Maybe another one is want ;) @halx99: Can you provide an official logo for using on adxe (not the logo on the github page of adxeproject)?

Well, actually, the logo was generated by a website automatically. maybe needs redesign by someone.

**Comment by DelinWorks** [comment]
Totally agree, It needs a game engine Icon aesthetic to it not just any Icon, And it's really hard to think of one right out of the top of my head 😕

**Comment by aismann** [comment]
closed: 
There is another issue #673
