### ISSUE TITLE
create new project and build with engine prebuilt libs => COCOS2D_DEBUG was not define

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#663]
Im not sure...but my just now create new project with debug build has no CCLOG outputs.
Add COCOS2D_DEBUG=1 on the project files, recompile and CCLOG output was shown.

**Comment by aismann** [comment]
Here a screenshot (I created an new project again)
COCOS2D_DEBUG is not defined.
![image](https://user-images.githubusercontent.com/8652787/174427365-9509a9fb-681c-405a-ba13-d05abd71cdb8.png)
my settings (
![image](https://user-images.githubusercontent.com/8652787/174426994-028cb6ee-b34f-4183-83ed-713a50d4c00c.png)

**Comment by halx99** [comment]
Linking with prebuilt libs not sync preprocessers from enigine

**Comment by aismann** [comment]
Closed.
@halx99
[Improve project template [skip ci]](https://github.com/adxeproject/adxe/commit/95e8b68051e14671bef4bf3026c301f6f740299c)
