### ISSUE TITLE
[SimpleSnake] A coffee break 'snake' clone (PRs are always welcome)

### ISSUE THREAD

**Issue by aismann** [adxeproject/adxe#672]
CodeCleanup !!!!

Add:
- Restart button
- Credits page
- Save/Load HighScore
- Add Traps

**Comment by aismann** [comment]
Every help is welcome.

**Comment by DelinWorks** [comment]
How about you make the game where the snake gets longer and longer and it loses if it bites it's tail like the old nokia phone games

**Comment by aismann** [comment]
The new menu:
![image](https://user-images.githubusercontent.com/8652787/175782308-636dcfe1-ec76-4f10-9d53-07f6d613fac3.png)

**Comment by aismann** [comment]
> How about you make the game where the snake gets longer and longer and it loses if it bites it's tail like the old nokia phone games, and the high score is based on how many things it has eaten

There are so much snake apps on the world which to this so.
The fun factor, the challenge is it to reach the shortest time for eat 9 foods. More a coffee break game.
The player is fight to break his own highscore.

**Comment by DelinWorks** [comment]
> > How about you make the game where the snake gets longer and longer and it loses if it bites it's tail like the old nokia phone games, and the high score is based on how many things it has eaten
> 
> There are so much snake apps on the world which to this so. The fun factor, the challenge is it to reach the shortest time for eat 9 foods. More a coffee break game. The player is fight to break his own highscore.

yeah you're right

**Comment by DelinWorks** [comment]
how about you make it so that there is infinite levels and if the player doesn't consume the thing in some period he loses and then his level is considered the highscore

**Comment by aismann** [comment]
And this makes fun ;)
I play more SimpleSnake and not programming new stuff  ;)

**Comment by aismann** [comment]
> how about you make it so that there is infinite levels and if the player doesn't consume the thing in some period he loses and then his level is considered the highscore
That's what SimpleSnake will be:
Add own idea (e.g. different game goals)

**Comment by DelinWorks** [comment]
you mean multiple gamemodes?

**Comment by aismann** [comment]
> you mean multiple gamemodes?

Correct!

**Comment by aismann** [comment]
@halx99 
Is it ok "SimpleSnake" be part of the 'adxe' distribution?
Or should I make it on my own repository?

**Comment by DelinWorks** [comment]
Yeah I think making it your own repo is better and then when it's done you can merge it into adxe repo

**Comment by DelinWorks** [comment]
it should be a repo about examples that anyone can do a pull request to and add useful examples :)

**Comment by aismann** [comment]
> Yeah I think making it your own repo is better and then when it's done you can merge it into adxe repo it should be a repo about examples that anyone can do a pull request to and add useful examples :)
> 
> examples that explain some engine features and abilities.

Yes. So the snake example can be as it it. for everybody to use it for your own ideas.

I will SimpleSnake improve but that's is not part of adxe itself.
A hint (Topic: adxe} should be enough

**Comment by aismann** [comment]
I close here now.
