### ISSUE TITLE
[PROPOSAL] redecide game engine name.

### ISSUE THREAD

**Issue by DelinWorks** [adxeproject/adxe#673]
I think the game engine's name should be `Axe` because it's better than `Adxe` in the since that it's easier to pronounce by just removing the letter `d` and it's also named after a generic object (axe that's used to cut down trees) which can have a decent theme for a icon/logo. Only drawback is that it's a big change and a regex replacement might or might not be the solution. So what do you think? any suggestion would be appreciated :D

**Comment by aismann** [comment]
Look here: #327

**Comment by DelinWorks** [comment]
Yeah `Axe game engine` sounds nice and not used by this popular list https://en.wikipedia.org/wiki/List_of_game_engines (avoiding trademark issues) don't you think?

**Comment by halx99** [comment]
Many alternative names:
```txt
xsred
xsrend
sxe
redex
stare
stxe
starex
SGX.dll
trainx
mdrx
sgex
scex
zlrend
goldex
goldengine
diam
simrx
purfx
pufx
ogfx
sgfx
matfx
malf
mole
swer
swx
swxe
alos
aloxe
ovxe
wxe
fwkex
xefwk
gfwk
zlfwk
ZLF
owx
soulx
breed
glare
Xif
```

**Comment by DelinWorks** [comment]
yeah but they don't have a meaning as you can see, they're just random mashed letters that if you were to make a logo for wouldn't make since

**Comment by aismann** [comment]
If rename it than better this one:
aXe

**Comment by DelinWorks** [comment]
`aXe` is okay but why wasn't `adxe` called `adXe` then? maybe we shouldn't engrave the fact that it supports everything by making x uppercase and just say that it supports both 2D, 3D in the front page of the github repo. that would make much more sense don't you think?

**Comment by aismann** [comment]
The uppercase X makes only sense for Branding.
Tools etc don't need  upperase letter anywhere.

**Comment by DelinWorks** [comment]
okay nice that works out :)

**Comment by aismann** [comment]
> okay nice that works out :)
Tools having also no problem using adxe 😏

**Comment by halx99** [comment]
Mybe `axel` --> pixel

**Comment by aismann** [comment]
Axe, aXe ist okay for me.
Axel is not better as axde.
Tge reason for changing is only  making an better imagine in mind and corresbonding Icon, Splash Screen and so on.

**Comment by halx99** [comment]
`Axe` is ok, or `Axes` for logo can construct with 2 or 3 axe

**Comment by DelinWorks** [comment]
> > okay nice that works out :)
> > Tools having also no problem using adxe 😏

yeah great it will be gradually changed not at once to avoid problems

**Comment by DelinWorks** [comment]
> Axe, aXe ist okay for me.

Did you mean is or isn't 😂 I got confused

**Comment by aismann** [comment]
adxe, Axe, aXe,ADXE all is OK for me.

**Comment by DelinWorks** [comment]
This is a some what good concept art for the name that I came up with:

![image](https://user-images.githubusercontent.com/45469625/175826301-7880512e-e610-4f68-8e07-0a71884335ba.png)

Words feel a bit crammed or the font is off but overall I think it's nice :D

I've went out of my way to model a whole axe just to show you how much I suck at drawing 😂

![image](https://user-images.githubusercontent.com/45469625/175826448-fe2af472-9935-4fa4-8a4c-103a0b50e736.png)

**Comment by halx99** [comment]
> Mybe `axel` --> pixel

The means of `axle` mybe better than `axe` for design a logo

**Comment by DelinWorks** [comment]
> > Mybe `axel` --> pixel
> 
> The means of `axle` mybe better than `axe` for design a logo

True but an axle looks like a random car part, picking a simple object like a fruit or a tool

**Comment by aismann** [comment]
![Profilbild_AXT](https://user-images.githubusercontent.com/8652787/175863384-c067dabd-e54b-46cb-a4be-82b89c263dce.jpg)
![WoodcraftCampCarver24_02_2048x](https://user-images.githubusercontent.com/8652787/175863388-5bba42d3-f252-4af8-b481-2074cac9647c.jpg)
![wikinger-axt-aus-schaumstoff-grau-braun](https://user-images.githubusercontent.com/8652787/175863391-9ecf11d2-6a5f-4f29-a25a-69d349585eb2.jpg)

**Comment by DelinWorks** [comment]
> ![Profilbild_AXT](https://user-images.githubusercontent.com/8652787/175863384-c067dabd-e54b-46cb-a4be-82b89c263dce.jpg) ![WoodcraftCampCarver24_02_2048x](https://user-images.githubusercontent.com/8652787/175863388-5bba42d3-f252-4af8-b481-2074cac9647c.jpg) ![wikinger-axt-aus-schaumstoff-grau-braun](https://user-images.githubusercontent.com/8652787/175863391-9ecf11d2-6a5f-4f29-a25a-69d349585eb2.jpg)

It would be nice if it was simple with a limited color pallet

**Comment by aismann** [comment]
Pictures 1
Symetrie
Pictures 2:
Not all ist needed to Draw/Show
Pictures 3:
Mir fantasy und symetrie

**Comment by aismann** [comment]
And Last one:
Only the Word "Axe" ist big.
And the Pictures ist not there only a Icon

**Comment by aismann** [comment]
Or aXe 😏

**Comment by DelinWorks** [comment]
You mean make the letter X big in the logo?

**Comment by halx99** [comment]
But On Github: 8541 repository results has "engine-x" anywhere
![image](https://user-images.githubusercontent.com/6977319/175915490-a03cd661-a8ac-4e14-a0fe-37630290a2be.png)

**Comment by aismann** [comment]
Why not like this (is not a good work, but I want only show as example):

![image](https://user-images.githubusercontent.com/8652787/175935615-ce86d9b9-3582-4b1e-ac9d-e60aa934a0b9.png)

**Comment by aismann** [comment]
Maybe make it with lower case also (Im not an artist).
So we can see what looks better

**Comment by aismann** [comment]
Thats what I mean

**Comment by DelinWorks** [comment]
I really think that the colorful icon doesn't make sense, since you're embedding the axe logo in the name and not the picture part

**Comment by DelinWorks** [comment]
I came to a conclusion and been working on it for 2 hours and no matter how you position it it looks ugly no matter what, because the letter don't make sense when they're beside a colorful axe, so I think the above logo is the best:

![image](https://user-images.githubusercontent.com/45469625/176027247-c48697e4-c284-497d-b097-a1fdf129d159.png)

**Comment by DelinWorks** [comment]
How about now! coconuts on the ground to indicate the root project.

![image](https://user-images.githubusercontent.com/45469625/176062963-6dc2f30f-622c-48ff-a0ce-5347415c9eef.png)

**Comment by DelinWorks** [comment]
> But On Github: 8541 repository results has "axe" anywhere ![image](https://user-images.githubusercontent.com/6977319/175915490-a03cd661-a8ac-4e14-a0fe-37630290a2be.png)

As for the case of searches, you don't have to name the repo "axe" just name it something else like "axe-game-engine" or "amazing-x-engine" as to avoid replications

**Comment by aismann** [comment]
> ![image](https://user-images.githubusercontent.com/45469625/176028312-25c7e7ac-42b6-4ca1-a23d-6e31ee5dc5ee.png)
> 
Looks good for me. 
@halx99 what are you mean?

**Comment by aismann** [comment]
What about this one? Little more color.
![image](https://user-images.githubusercontent.com/8652787/176094412-44b9a2c2-2d10-4764-bde3-c94a4cd24475.png)

**Comment by DelinWorks** [comment]
meh it feels off a bit, like i said above text and colors don't mix will 😕

**Comment by aismann** [comment]
No proplem.

**Comment by halx99** [comment]
The axe could be tool or weapon, I'm not sure whether a good idea to use it as a game engine name.

**Comment by DelinWorks** [comment]
There is the `Valve Hammer Editor` game engine so I think it's okay

**Comment by aismann** [comment]
The name looks OK for me .
The Axe itself ist as @halx99 says a tool or a weapon too.

**Comment by aismann** [comment]
Maybe only an orange X as Icon.
And the Splash Screen should be having the Name without the picture of the Axe and the coconut

**Comment by DelinWorks** [comment]
Why didn't you say that in the beginning then? before we started designing the logo 😐

**Comment by halx99** [comment]
@rh101 Do you have any other idea?

**Comment by DelinWorks** [comment]
A good practice when naming things is to not adapt that change immediately, like naming the engine we shouldn't go and change every line that says `adxe` but rather change it gradually

**Comment by LotoXe112** [comment]
I think name axe and logo fit will with engine but I agree final decision should not rush

**Comment by aismann** [comment]
That's the look:
![image](https://user-images.githubusercontent.com/8652787/176701568-b26ed17b-cba0-469d-a7f9-d2892f7ddf23.png)

**Comment by DelinWorks** [comment]
The letter could use a bit of an outline but overall it's great!

**Comment by aismann** [comment]
> The letters could use a bit of an outline but overall it's great!

Only an orange X (on the logo) looks better I think. 
The crossing "Axe"s can be part of the splash screen maybe.

**Comment by Joilnen** [comment]
I guess Adxe is ok, makes it kind of unique.

**Comment by DelinWorks** [comment]
> I guess Adxe is ok, makes it kind of unique.

Honestly, thinking about it Adxe feels like it has been gotten used to and is actually a good name, and it's unique I'll give it that

**Comment by aismann** [comment]
> > I guess Adxe is ok, makes it kind of unique.
> 
> Honestly, thinking about it Adxe feels like it has been gotten used to and is actually a good name, and it's unique I'll give it that

@DelinWorks =>  Please close it 
So we can close this issue?   
I think the cloud as icon is ok?  (maybe you can make a cloud icon  too?)
For the splash screen we can use the "Logo" which you have created too?
Look here as example:
![image](https://user-images.githubusercontent.com/8652787/177494838-b5debd4e-78ad-4090-99cc-30a64bd4937f.png)

**Comment by DelinWorks** [comment]
No it's good this can stay.
