### ISSUE TITLE
Strange issue after latest Renderer changes commit

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#676]
- adxe version: Current dev branch
- devices test on: Windows 10
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 
Steps to Reproduce:

Prior to commit https://github.com/adxeproject/adxe/commit/1889180a75322a3b7e611f93d56f6e622c6cb92c, this code worked when being called hundreds of times in a loop for different sprites:

```
auto* sprite = Sprite::create(spriteFileName);
auto&& sprSize = sprite->getContentSize();
sprite->setPosition(sprSize / 2);
// We need to check for GL usage here, because flipping the sprite causes incorrect behaviour on iOS/MacOSX (Metal)
#if defined(CC_USE_GL) || defined(CC_USE_GLES)
sprite->setFlippedY(true);
#endif
auto* renderTexture = RenderTexture::create(static_cast<int>(sprSize.width), static_cast<int>(sprSize.height), PixelFormat::RGBA8);
renderTexture->beginWithClear(0, 0, 0, 0);
sprite->visit();
renderTexture->end();
```

After commit https://github.com/adxeproject/adxe/commit/1889180a75322a3b7e611f93d56f6e622c6cb92c, the code above no longer applies the Sprite texture to the RenderTexture.  If `RenderTexture::save` is called, then a 35x36 pixel white box is saved, regardless of what the true size of the RenderTexture should be.

The only way that I've managed to fix this is to add this line at the end of the above code:
`Director::getInstance()->getRenderer()->render();`

So it changes to this:
```
auto* sprite = Sprite::create(spriteFileName);
auto&& sprSize = sprite->getContentSize();
sprite->setPosition(sprSize / 2);
// We need to check for GL usage here, because flipping the sprite causes incorrect behaviour on iOS/MacOSX (Metal)
#if defined(CC_USE_GL) || defined(CC_USE_GLES)
sprite->setFlippedY(true);
#endif
auto* renderTexture = RenderTexture::create(static_cast<int>(sprSize.width), static_cast<int>(sprSize.height), PixelFormat::RGBA8);
renderTexture->beginWithClear(0, 0, 0, 0);
sprite->visit();
renderTexture->end();
Director::getInstance()->getRenderer()->render();
```

Is there a reason that the `Director::getInstance()->getRenderer()->render()` is now required, or was it just pure luck that it was working without that call to `render()`? 

Unfortunately, I couldn't reproduce this issue in a simple project, so it has to be something specific to how that section of code above is being called in my main project.  I'm still trying to figure out why it's happening, but at least I have it working again by adding the `Director::getInstance()->getRenderer()->render()` call.

**Comment by halx99** [comment]
Please try to restore the RenderTarget in CCRenderTexture.cpp like: 
```cpp
  // _renderTarget = backend::Device::getInstance()->newRenderTarget(
  //     _renderTargetFlags, _texture2D ? _texture2D->getBackendTexture() : nullptr,
  //     _depthStencilTexture ? _depthStencilTexture->getBackendTexture() : nullptr,
  //     _depthStencilTexture ? _depthStencilTexture->getBackendTexture() : nullptr);
  _renderTarget = _director->getRenderer()->getOffscreenRenderTarget();
  _renderTarget->retain();
```

change to 
```cpp
   _renderTarget = backend::Device::getInstance()->newRenderTarget(
       _renderTargetFlags, _texture2D ? _texture2D->getBackendTexture() : nullptr,
       _depthStencilTexture ? _depthStencilTexture->getBackendTexture() : nullptr,
       _depthStencilTexture ? _depthStencilTexture->getBackendTexture() : nullptr);
```

**Comment by rh101** [comment]
I'll test that out now.

**Comment by rh101** [comment]
> Please try to restore the RenderTarget in [CCRenderTexture.cpp line 200](https://github.com/adxeproject/adxe/blob/dev/core/2d/CCRenderTexture.cpp#L200):
> 
> ```c++
>   // _renderTarget = backend::Device::getInstance()->newRenderTarget(
>   //     _renderTargetFlags, _texture2D ? _texture2D->getBackendTexture() : nullptr,
>   //     _depthStencilTexture ? _depthStencilTexture->getBackendTexture() : nullptr,
>   //     _depthStencilTexture ? _depthStencilTexture->getBackendTexture() : nullptr);
>   _renderTarget = _director->getRenderer()->getOffscreenRenderTarget();
>   _renderTarget->retain();
> ```
> 
> change to
> 
> ```c++
>    _renderTarget = backend::Device::getInstance()->newRenderTarget(
>        _renderTargetFlags, _texture2D ? _texture2D->getBackendTexture() : nullptr,
>        _depthStencilTexture ? _depthStencilTexture->getBackendTexture() : nullptr,
>        _depthStencilTexture ? _depthStencilTexture->getBackendTexture() : nullptr);
> ```

This fixed the issue I was having, so I didn't need to call `Director::getInstance()->getRenderer()->render()`.

**Comment by halx99** [comment]
The changes explain:
- `getOffscreenRenderTarget`: all rendertexture share one render target, it's compatilbe old cocos2d-x v4/v3
- new RenderTarget: The rendertexture has own render target

**Comment by halx99** [comment]
> > Please try to restore the RenderTarget in [CCRenderTexture.cpp line 200](https://github.com/adxeproject/adxe/blob/dev/core/2d/CCRenderTexture.cpp#L200):
> > ```c++
> >   // _renderTarget = backend::Device::getInstance()->newRenderTarget(
> >   //     _renderTargetFlags, _texture2D ? _texture2D->getBackendTexture() : nullptr,
> >   //     _depthStencilTexture ? _depthStencilTexture->getBackendTexture() : nullptr,
> >   //     _depthStencilTexture ? _depthStencilTexture->getBackendTexture() : nullptr);
> >   _renderTarget = _director->getRenderer()->getOffscreenRenderTarget();
> >   _renderTarget->retain();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > change to
> > ```c++
> >    _renderTarget = backend::Device::getInstance()->newRenderTarget(
> >        _renderTargetFlags, _texture2D ? _texture2D->getBackendTexture() : nullptr,
> >        _depthStencilTexture ? _depthStencilTexture->getBackendTexture() : nullptr,
> >        _depthStencilTexture ? _depthStencilTexture->getBackendTexture() : nullptr);
> > ```
> 
> This fixed the issue I was having, so I didn't need to call `Director::getInstance()->getRenderer()->render()`.

That can comfirm, you code works on the second situation，but the latest feature for `Live2D` extension works on the first situation

**Comment by rh101** [comment]
Is it possible to somehow select which method we want to use, whether it uses a shared render target, or a new render target, perhaps by adding a new parameter to the RenderTexture `create` functions?

**Comment by halx99** [comment]
> Is it possible to somehow select which method we want to use, whether it uses a shared render target, or a new render target, perhaps by adding a new parameter to the RenderTexture `create` functions?

Yes, this solution sounds good

**Comment by rh101** [comment]
It is fine if the default is a shared render target, so something like:

`static RenderTexture* create(int w, int h, backend::PixelFormat format, bool sharedRenderTarget = true);`
or

`static RenderTexture* create(int w, int h, backend::PixelFormat format, bool newRenderTarget = false);`

etc  etc.

**Comment by halx99** [comment]
I prefer first one

**Comment by rh101** [comment]
Do you want me to implement the changes, or do you want to take care of it?

**Comment by halx99** [comment]
You can take the changes

**Comment by rh101** [comment]
No worries, I'll submit a PR soon, and yes the first way makes more sense, so `bool sharedRenderTarget = true` by default.

**Comment by rh101** [comment]
Ok, I'll implement that too.

**Comment by halx99** [comment]
Could implement as: `return _renderTarget == renderer->getOffscreenRenderTarget()`

**Comment by rh101** [comment]
> Could implement as: `return _renderTarget == renderer->getOffscreenRenderTarget()`

Good idea!
