### ISSUE TITLE
is adxe script still supported ? 

### ISSUE THREAD

**Issue by Joilnen** [adxeproject/adxe#684]
- adxe version: be6f1bc91141a037f58f5dfec797d3d1ab7c7f7d
- devices test on:
- developing environments
   - NDK version: 23.2.8568313

Steps to Reproduce:
~/adxe_devel/adxe29062022/tools/console/bin/adxe compile -p android -j 4 --app-abi armeabi-v7a

I got this error, "unable to find library -lpipewire-0.3":

---
nal/CMakeFiles/OpenAL.dir/core/mixer/mixer_c.cpp.o engine/thirdparty/openal/CMakeFiles/OpenAL.dir/core/mixer/mixer_neon.cpp.o  lib/libcommon.a -pthread /home/joilnen/Android/Sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/17/libOpenSLES.so -lpipewire-0.3 -llog -latomic -lm -latomic -lm && :
  ld: error: unable to find library -lpipewire-0.3
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  [710/1185] Building C object engine/thirdparty/png/CMakeFiles/png.dir/arm/palette_neon_intrinsics.c.o
  [711/1185] Building C object engine/thirdparty/png/CMakeFiles/png.dir/arm/filter_neon_intrinsics.c.o
  [712/1185] Building C object engine/thirdparty/unzip/CMakeFiles/unzip.dir/crypt.c.o
  [713/1185] Building C object engine/thirdparty/unzip/CMakeFiles/unzip.dir/ioapi.c.o
  [714/1185] Linking C static library lib/libogg.a
  ninja: build stopped: subcommand failed.
  
  CMake Warning at /home/joilnen/Android/Sdk/ndk/23.2.8568313/build/cmake/android-legacy.toolchain.cmake:416 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    /home/joilnen/Android/Sdk/ndk/23.2.8568313/build/cmake/android.toolchain.cmake:55 (include)
    proj.android/app/.cxx/Debug/5c6u5s6a/armeabi-v7a/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
    CMakeLists.txt:30 (project)
  
  
  Configuring Chipmunk2D version 7.0.3
  CMake Warning at /home/joilnen/adxe_devel/adxe/thirdparty/freetype/builds/cmake/FindHarfBuzz.cmake:99 (message):
    Required version (2.0.0) is higher than found version ()
  Call Stack (most recent call first):
    /home/joilnen/adxe_devel/adxe/thirdparty/freetype/CMakeLists.txt:253 (find_package)
  
  
  CMake Warning (dev) at /home/joilnen/adxe_devel/adxe/thirdparty/astc/CMakeLists.txt:136 (message):
    
    ISA_SIMD=none,ASTC_HAVE_AVX2_INTRINSICS=,ASTC_HAVE_SSE42_INTRINSICS=,ASTC_HAVE_SSE41_INTRINSICS=,ASTC_HAVE_SSE2_INTRINSICS=,ASTC_HAVE_NEON_INTRINSICS=
  This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by halx99** [comment]
What's your build devices? macOS or windows or linux?

**Comment by Joilnen** [comment]
Linux

**Comment by halx99** [comment]
I have check on macOS, it works

**Comment by halx99** [comment]
![image](https://user-images.githubusercontent.com/6977319/176830068-2bdda4f3-03c9-4747-83cd-1fae1ddaf115.png)

**Comment by Joilnen** [comment]
Have you used only android sdk and ninja ? I am not using android studio.

**Comment by halx99** [comment]
> Have you used only android sdk and ninja ? I am not using android studio.

Yes, only specific ABDROID_SDK should works

**Comment by Joilnen** [comment]
could be related with ninja version, no ?

**Comment by halx99** [comment]
you can refer to: https://github.com/adxeproject/adxe/blob/dev/tools/unix-ci/setup_android.py

**Comment by halx99** [comment]
I will try follow steps:
```sh
wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
unzip commandlinetools-linux-8512546_latest.zip
mkdir sdk
./cmdline-tools/bin/sdkmanager --list --sdk_root=`pwd`/sdk
./cmdline-tools/bin/sdkmanager --verbose --sdk_root=`pwd`/sdk platform-tools "cmdline-tools;latest" "cmake;3.18.1" "ndk;23.2.8568313" 

export ANDROID_SDK=`pwd`/sdk

mkdir projects
adxe new -p com.bytedance.hellocpp -d `pwd`/projects -l cpp --portrait HelloCpp
cd projects/HelloCpp
adxe compile -p android -j 4 --app-abi armeabi-v7a
```

**Comment by Joilnen** [comment]
Thank you, the package steam-native form arch linux install pipewire as dependency and the gradle seems to mess with that and try to compile it together the project so I uninstall that package and this compiled well.
