### ISSUE TITLE
Renderer::nextCallbackCommand() returns unclear CallbackCommand

### ISSUE THREAD

**Issue by solan-solan** [adxeproject/adxe#689]
- adxe version:
- devices test on:
- developing environments
   - NDK version: r19c
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 
Steps to Reproduce:

There is one issue , when _CallbackCommand_ which is stored to _Render::_callbackCommandsPool_ is returned with not reseted flags by the _Renderer::nextCallbackCommand()_ request.
As example, the issue begin if there was set __is3D_ flag for _CallbackCommand_, and the command was pushed to __callbackCommandsPool_. This flag will not be reset when the command will be reused in some other place where this flag is not needed.

----

Take a look please how this issue could be fixed:

![image](https://user-images.githubusercontent.com/73186496/176791091-50f3ac0e-38c3-4c8b-ae6d-ebfd44fc993c.png)
![image](https://user-images.githubusercontent.com/73186496/176791149-15477b8f-5dd6-43a2-8ada-e01ab111ad11.png)

**Comment by halx99** [comment]
Could you post a pr to fix it?

**Comment by solan-solan** [comment]
Thanks to fix it
