### ISSUE TITLE
[BUG] Angle `D3D11` `glEnableVertexAttribArray()` program state rendering error.

### ISSUE THREAD

**Issue by DelinWorks** [adxeproject/adxe#697]
This bug seems like it's up to google angle to fix it but just to throw it out there it seems sometimes when a shader is switched, it's vertex attributes do not switch from the old one to the new one, and an `OpenGL error 0x0502` error is thrown, this bug was discovered by making a mesh render in 2D queue `setForce2DQueue()` with a sprite that exists in the same scene but with a lower local z value than the 2D queued mesh.

Unexpected result: mesh will not be shown and an opengl error is thrown.

`CCRenderer.cpp:320`
![image](https://user-images.githubusercontent.com/45469625/176974837-2ddac620-764c-41b1-a5f0-c599735d9bc5.png)

When `flush2D` is called (which renders all sprites in a scene in a single batch to minimize draw calls), it calls `drawElements()` in the same sort order `GLOBALZ_XXX` as the mesh, they both set up their vertex attributes in:
`CommandBufferGL.cpp:283`
![image](https://user-images.githubusercontent.com/45469625/176974940-226a0e59-6af2-4bf3-b3a3-0a2b3da1ad5d.png)

Now that triangle batch is drawn with it's according vertex attributes, and here comes the turn to `drawMeshCommand()` which does the same thing and sets up it's vertex attributes according to the program state just like before, BUT an opengl es angle error is thrown `OpenGL error 0x0502` when the draw call is finally issued, which confused me as to how could a previous opengl state affect future states?

I don't know if that bug affects only D3D11 Angle or OpenGL ES devices and if both are affected then mobile devices are affected by this bug too.

**Comment by halx99** [comment]
Do you have a reproduce demo about this issue

**Comment by DelinWorks** [comment]
Somehow I can't reproduce the bug again with d3d11... 

The helloworld sprite seems to render fine behind the mesh of quads:

![image](https://user-images.githubusercontent.com/45469625/177008301-3293a591-0b78-4a60-a045-97d5c32c033d.png)

I think it's a vertex attribute problem, the bug is really confusing.

I'll close this issue for now.
