### ISSUE TITLE
[Android] 2D particle effect issue when application is running on real devices

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#698]
- adxe version: Current version https://github.com/adxeproject/adxe/commit/8806d7bdf77b003725ee68a17e3aad4ba70efee7
- devices test on: Android 8, Android 12 (HTC One M8 and Pixel 4a)
- developing environments
   - NDK version: r23
   - Xcode version: 12.4
   - VS/msvctools version: Visual Studio 2019(16.11)/14.29.30133
   - cmake version: 
Steps to Reproduce:

1. Compile cpp-tests for Android
2. Upload to real device
3. Click on test `37:Node: Particles`
4. No particle effects are displayed. Blank flickering colors or whole screen white textures in their place.

There is no issue on Windows or Android emulators.  This issue was confirmed when cpp-tests was run on the Android devices.

In my own application, the entire screen goes white, but I can still click through it, so the application isn't frozen.  It seems to be a rendering issue.

**Expected:**
![image](https://user-images.githubusercontent.com/8603230/177029445-6056c02c-a7e4-4d26-a8fa-2dde33fe6728.png)

**Actual:**
![image](https://user-images.githubusercontent.com/8603230/177029427-dcd26a9c-e0ba-43e4-bcf3-ba4fdf457edb.png)
![image](https://user-images.githubusercontent.com/8603230/177029472-4b752e8a-0eb8-4bba-a0f1-1a7c8a6ecd13.png)
![image](https://user-images.githubusercontent.com/8603230/177029477-b4107379-6915-45f0-8bf1-4d03bc78705d.png)

**Comment by halx99** [comment]
Maybe @DelinWorks can take a look

**Comment by DelinWorks** [comment]
I highly think #639 made this error, I'll see if i can replicate this in my phone.

**Comment by DelinWorks** [comment]
@rh101 Have you advanced through the 2D particle tests to see if the added changes from the PR mentioned above work?

**Comment by rh101** [comment]
> @rh101 Have you advanced through the 2D particle tests to see if the added changes from the PR mentioned above work?

What do you mean?

If you're asking about the rest of the tests in the `37:Node: Particles` test section, then if you open it up, you'll see that they all have issues.

I don't know what changes you're referring to in that PR.  That PR has already been merged, and if you need to add more changes or fix issues, they need to be put in a new PR.

**Comment by DelinWorks** [comment]
I was asking about if the cpp tests that were added in the PR #639 do they work? because the pictures you sent talked about tests that the mentioned pr didn't add

**Comment by rh101** [comment]
I'm not sure I understand why that would matter.  The changes in PR #639 affect the entire particle system, not just the test cases that were added in that PR.

All of the tests aren't working correctly, even the new ones added in that PR.  Particle test 7 seems to work, but has very bad stuttering, which was not present prior to PR.

**Comment by DelinWorks** [comment]
100% a platform dependant macro that missed up the rendering

**Comment by rh101** [comment]
Regardless of what is causing it, the issue needs to be addressed, because it's effectively broken the particle system on Android.  In my specific case, I've had to disable all particle effects in order to continue with the application development.  

For the time being, I'll have to create a separate branch in my fork and roll-back the changes made in PR 639 in order to continue development on my application until this issue is resolved.

**Comment by rh101** [comment]
I just had an idea, and tested it out.  It seems to be an issue of data size.

Android 64 bit (arm64-v8a) has problems, but Android 32 bit (armeabi-v7a) works fine.

Things like memory allocations and data size calculations need to be checked, because they'll most likely be the source of the issue.

**Comment by DelinWorks** [comment]
Don't worry I'll work on it now

**Comment by halx99** [comment]
@DelinWorks These `long` types should be changed to `int32_t`:

![image](https://user-images.githubusercontent.com/6977319/177061774-a14d6b15-a2f0-4d27-89cf-8ef386301c2f.png)

**Comment by DelinWorks** [comment]
do you mean `uint32_t`?

**Comment by rh101** [comment]
Changing all `unsigned long` usage in that class to `uint32_t` fixes the particle engine problem.

**Comment by halx99** [comment]
> do you mean `uint32_t`?

Yes

**Comment by DelinWorks** [comment]
I'm still building for arm64 :> it took 13 mins already my pc is junk

**Comment by DelinWorks** [comment]
Yeah this fixes it for me on my device galaxy a31
