### ISSUE TITLE
Concerns regarding RngSeed implementation

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#706]
At the moment the implementation uses calculations like this:

    int32_t range(int32_t min, int32_t max)
    {
        return floor(min + static_cast<float>(rand()) / (static_cast<float>(RNG_RAND_MAX / (max - min))));
    }

No focus on this part of the code:
`static_cast<float>(RNG_RAND_MAX / (max - min))`

Which is effectively `RNG_RAND_MAX / (max - min)`, an integer division, before it is typecast to a float.  

If you pass a value of min = 10, and max = 1000, you will get this:

RNG_RAND_MAX / (max - min) = 4294967295 / (1000 - 10) = **4338350**

Converting the result of that to a float is not required here, since the numerator has already been typecast to a float, the `static_cast<float>(rand())`.

That brings us to the next concern.  Should it actually have been this instead:

` static_cast<float>(RNG_RAND_MAX) / (max - min)`

Where it would result in a floating point division, and the end result for min = 10 and max = 1000 would be this:

static_cast<float>(RNG_RAND_MAX) / (max - min) = 4294967295.0F / (1000 - 10) =  **4338351**

What should be the correct implementation, since each ends up with a different result?  As it is, the code doesn't make sense, since the current implementation is doing an integer division, which is an integer result, and typecasting it to a float makes no difference whatsoever.

**Comment by rh101** [comment]
Also, the RngSeed.hpp is missing include statements, namely:

```
#include <cmath>
#include <limits.h>
```

It's compiling correctly as it is because of the order of compilation, but it should explicitly list the includes that it requires.

**Comment by DelinWorks** [comment]
I've been thinking about it too, it needs a major overhaul including making `max` arguments exclusive NOT inclusive.

**Comment by rh101** [comment]
If you're going to create a PR, please also typecast the result on the return statement to stop all the warnings coming up during compilation. For example:

    int32_t range(int32_t min, int32_t max)
    {
        return floor(min + static_cast<float>(rand()) / (static_cast<float>(RNG_RAND_MAX / (max - min))));
    }

Needs a cast added like this:

    int32_t range(int32_t min, int32_t max)
    {
        return static_cast<int32_t>(floor(min + static_cast<float>(rand()) / (static_cast<float>(RNG_RAND_MAX / (max - min)))));
    }

Otherwise, the compiler throws out a lot of warnings about the conversion.

**Comment by halx99** [comment]
Does the c++11 random library enough?

**Comment by rh101** [comment]
I personally use the C++ implementation in all areas of my app, similar to what's used in `cocos2d::RandomHelper`:

```
static std::random_device seed_gen;
static std::mt19937 engine(seed_gen());
```

Is there any specific reason not to use it this?

**Comment by halx99** [comment]
> I personally use the C++ implementation in all areas of my app, similar to what's used in `cocos2d::RandomHelper`:
> 
> ```
> static std::random_device seed_gen;
> static std::mt19937 engine(seed_gen());
> ```
> 
> Is there any specific reason not to use it this?

I have same question, @DelinWorks  could you explain the reason?

**Comment by DelinWorks** [comment]
Because it's independently seeded, with the C++ implementation you can seed the random number generator but that's for one instance, but with `RngSeed` you could have multiple distinctly seeded instances, `RngSeed` becomes extremely useful when combined with perlin noise algorithms, and can be used to make games like minecraft where the chunk position is used as a seed that is independent from other copies. Hope that explains it.

**Comment by rh101** [comment]
Do you mean creating multiple instances using the same seed?

**Comment by DelinWorks** [comment]
> > Because it's independently seeded, with the C++ implementation you can seed the random number generator but that's for one instance, but with `RngSeed` you could have multiple distinctly seeded instances,
> 
> Do you mean creating multiple instances using the same seed?

no, creating multiple instances with different seed, sorry wrong word `distinct`

**Comment by rh101** [comment]
I still don't quite understand what you mean, and why the C++11 random number generator cannot do what you're referring to.  Are there any articles that describe the issue?

**Comment by DelinWorks** [comment]
https://stackoverflow.com/a/20095001/9228093

The first reason it's used is the one I mentioned above. Also it's good for performance because it relies heavily on simple math operations and not states, it's in the particle system because it gives more frames per second than the traditional c++11 library.

**Comment by rh101** [comment]
Have you tested the performance of C++11 random generator for the use cases where performance may be an issue? 

If you have, and the C++11 implementation is not fast enough, then perhaps the RngSeed implementation can remain, but I feel that it should be rename it to something.  The reason for that is to reflect what it should be used for, because it may not be adequate for situations where better random distribution is required (such as random results in a gambling game etc).  

A comment should be added in the source as well to describe the use-cases or what it is or is not suitable for, for instance, it may be fine for animations, particle effects and such things, but I doubt that it would be suitable for anything else.

**Comment by DelinWorks** [comment]
> Have you tested the performance of C++11 random generator for the cases where performance may be an issue?
> 
> If you have, and the C++11 implementation is not fast enough, then perhaps the RngSeed implementation can remain, but I feel that it should be rename it to something. The reason for that is to reflect what it should be used for, because it may not be adequate for situations where better random distribution is required (such as random results in a gambling game etc).
> 
> A comment should be added in the source as well to describe the use-cases or what it is or is not suitable for, for instance, it may be fine for animations, particle effects and such things, but I doubt that it would be suitable for anything else.

I have tested it when I added the particle system features and `RngSeed` performs better than c++11 library

**Comment by DelinWorks** [comment]
> If you have, and the C++11 implementation is not fast enough, then perhaps the RngSeed implementation can remain, but I feel that it should be renamed to something else. The reason for that is to reflect what it should be used for, because it may not be adequate for situations where better random distribution is required (such as random results in a gambling game etc).

Would `FastRNG` be a good name?

**Comment by DelinWorks** [comment]
> A comment should be added in the source as well to describe the use-cases or what it is or is not suitable for. For instance, it would be fine for animations, particle effects and such things, but I doubt that it would be suitable for anything else.

True

**Comment by rh101** [comment]
> I have tested it when I added the particle system features and `RngSeed` performs better than c++11 library

I understand that it performs better, but I was referring to the suitability of the C++11 library, not so much about the comparison between the two.  Is the performance of the C++11 library not good enough for the particle effects system?

**Comment by rh101** [comment]
> Would `FastRNG` be a good name?

I think that's fine, more appropriate than RngSeed, and better reflects what it actually is.

**Comment by DelinWorks** [comment]
> > I have tested it when I added the particle system features and `RngSeed` performs better than c++11 library
> 
> I understand that it performs better, but I was referring to the suitability of the C++11 library, not so much about the comparison between the two. Is the performance of the C++11 library not good enough for the particle effects system?

Yes, `ParticleSystem` is a good example of why a simple RNG system is needed, for use cases like particle system where for each particle it has to generate 8 to 16 random numbers, this would add up! so a fast simple random number generator is used

**Comment by rh101** [comment]
Can this issue be closed, assuming you've carried out range and distribution testing on the new RNG changes to verify they are as expected?

**Comment by DelinWorks** [comment]
Yes, it can be closed. Everything's been dealt with.
