### ISSUE TITLE
ADXE and Spine

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#707]
The latest commit, https://github.com/adxeproject/adxe/commit/555f847c1f4890ebcab0af75feb0cc32b358f93a, which changed the sampler names, causes graphical issues when using the official Spine runtime.  I realise the built-in Spine code in ADXE was modified to work, but this really should be ported over to the official runtime.

I personally don't use the Spine version that is bundled with ADXE; the one I use is a slightly modified version of the runtime that is available from the official Spine runtime repo.

@halx99 is there any chance you could have a chat to the developers of Spine, and request that they add a new ADXE-specific folder to their runtime repo? This project has diverged from Cocos2d-x, and will continue to do so, and using the cocos2d-x runtime for ADXE no longer makes sense, and will just cause more problems down the line.

If they do agree to add a new runtime folder specific to ADXE, then changes can be pushed to the official runtime, and we won't have to deal with Cocos2d-x related compatibility.

**Comment by halx99** [comment]
The commit https://github.com/adxeproject/adxe/commit/91e57e7dd32e4c489a93426228d58d35791e0f37 will let user can continue use official spine runtime after post a merge-request to use backend defination sampler name for `SkeletonBatch`

**Comment by rh101** [comment]
Oh, that's excellent!

I thought that `SkeletonTwoColorBatch.cpp` would be affected too, but it is referring to its own shader, and not the backend shader, so that one isn't an issue.

**Comment by halx99** [comment]
> Oh, that's excellent!
> 
> I thought that `SkeletonTwoColorBatch.cpp` would be affected too, but it is referring to its own shader, and not the backend shader, so that one isn't an issue.

Yes

**Comment by halx99** [comment]
Refer to this PR: https://github.com/EsotericSoftware/spine-runtimes/pull/2104

**Comment by rh101** [comment]
All good, thank you.

**Comment by badlogic** [comment]
Oh, Axis looks awesome!
